### ISSUE TITLE
`home.sessionVariables` has no effect when using a graphical desktop environment

### ISSUE THREAD

**Issue by sigwinch28** [nix-community/home-manager#1011]
At the time of writing, the contents `home.sessionVariables` are placed in `~/.profile`.

As I use KDE Plasma, these variables never get loaded for me because:

- `/etc/profile` on NixOS 19.09 _does not_ source `~/.profile`
- sddm _does not_ source `~/.profile`
- Konsole and other terminal emulators start _non-login_ interactive shells by default (and therefore do not load `~/.bash_profile` or `~/.profile`, but `~/.bashrc` instead)

For example, if I set:
```
home.sessionVariables = { EDITOR = "emacs" };
```
I get:
```
[joe@mycomputer:~] $ echo $EDITOR
nano
```

My `~/.profile`, `~/.bash_profile`, and `~/.bashrc` files are all managed by home-manager and their contents are as follows:

```
# ~/.profile
# -*- mode: sh -*-

. "/home/joe/.nix-profile/etc/profile.d/hm-session-vars.sh"

```

```
# ~/.bash_profile
# -*- mode: sh -*-

# include .profile if it exists
[[ -f ~/.profile ]] && . ~/.profile

# include .bashrc if it exists
[[ -f ~/.bashrc ]] && . ~/.bashrc

```

```
# ~/.bashrc
# -*- mode: sh -*-

# Commands that should be applied only for interactive shells.
if [[ $- == *i* ]]; then
  HISTFILE="$HOME/.bash_history"
HISTFILESIZE=100000
HISTSIZE=10000

  shopt -s histappend
shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

  
fi

```

To make matters worse, it seems that NixOS doesn't make an authoritative decision about whether `~/.profile` (or actually, whether any other file) will be reliably sourced at login when using a graphical environment (https://github.com/NixOS/nixpkgs/issues/5200)

If I log in via the console or via SSH however, this _does_ count as a bash login shell and my environment variables are set correctly.

For now my current workaround is to put the following in my system's `/etc/nixos/configuration.nix` which applies a workaround at the system level:
```
environment.loginShellInit = ''
	if [ -e $HOME/.profile ]
	then
		. $HOME/.profile
	fi
'';
```

but I could just as easily put the following in my `home.nix`:
```
home.file.".xprofile".text = ''
	if [ -e $HOME/.profile ]
	then
		. $HOME/.profile
	fi
'';
```

I also think I could get around this by putting `xsession.enable = true;` in my `home.nix` which would add the necessary `if [ -e $HOME/.profile ] ...` code to my `~/.xprofile`.

Any comments or suggested solutions to this quirk between home-manager and NixOS, or anything in the documentation I have missed?

**Comment by tfc** [comment]
I have the same problem.

Adding the 

```
home.file.".xprofile".text = ''
	if [ -e $HOME/.profile ]
	then
		. $HOME/.profile
	fi
'';
```

snippet to my home manager config however does not work. When i do `source ~/.xprofile`, that works, but simply by logging in into gnome and looking up my env in the shell, i don't see this was sourced.

**Comment by mammothbane** [comment]
Completely untested, but you might try `systemd.user.sessionVariables` instead

**Comment by roosemberth** [comment]
I'm using this to address the issue, works like a charm:

```
    # Source home-manager environment
    environment.extraInit = concatMapStringsSep "\n" (user: let
      homedir = config.users.users.${user}.home;
    in ''
      if [ "$(id -un)" = "${user}" ]; then
        . "${homedir}/.nix-profile/etc/profile.d/hm-session-vars.sh"
      fi
    '') ["user1" "user2"]);
```

**Comment by onny** [comment]
> Completely untested, but you might try `systemd.user.sessionVariables` instead
cool this worked for me. But I have to note that I autostart my window manager Sway also with this command:
```
systemctl --user import-environment
```

**Comment by tfc** [comment]
> Completely untested, but you might try systemd.user.sessionVariables instead

@mammothbane unfortunately my gnome ignores this setting.

**Comment by Vonfry** [comment]
Could home-manager set systemd.sessionVariables with home.sessionVariables by default?

**Comment by li-maisiliym-xyz** [comment]
The right way to fix this is to wrap apps which need the socket, since giving an env var to an application that shoundnt use it is both wasteful and incorrect. This is why gnome stopped sourcing profile's, and is the way forward. Li's plan is to use systemd units to launch all apps. Gnome devs have been discussing this also.

**Comment by dotKuro** [comment]
I looked into the source of the zsh and bash nix expression respectivly and noticed that both of them are just sourceing the session variables incorrectly: They are sourcing them in the .zshrc/.bashrc, which only affects the actual shells. In order to have them more globally I'd suggest sourcing them in .bash_profile/.xprofile/.zsh_env respectivly.

**Comment by putchar** [comment]
Hello
i am having the same issue with bash

here is my snippet 
```bash
  programs.bash = {
    enable = true;
    sessionVariables = {
      VAGRANT_DEFAULT_PROVIDER="libvirt";
      TERM="xterm-256color";
      };
    };
``` 
should we depreciate this option in favor of `systemd.user.sessionVariables` ?

**Comment by berbiche** [comment]
cc @rycee

I think the variables in `bash.sessionVariables` are only loaded when run from an interactive shell which is why they are not loaded by your desktop environment.
Same goes for `home.sessionVariables` I think.

As for `systemd.user.sessionVariables`, this only applies to systemd services.

**Comment by rycee** [comment]
@berbiche Yeah, that's right. Except that `home.sessionVariables` is pretty much intended for any login session. If `xsession.enable` is enabled then HM will create an `~/.xprofile` file containing, among other things,

    . "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"

X login sessions should load this file and introduce the variables.

People who don't want HM to manage the X session can manually put that line in their `~/.xprofile` file (replacing `${config.home.profileDirectory}` by the appropriate value).

**Comment by colemickens** [comment]
Any word if `xsession.enable` works with the GNOME Wayland session?

**Comment by berbiche** [comment]
> @colemickens 
> Any word if `xsession.enable` works with the GNOME Wayland session?

AFAIK no. The Home Manager generated .xprofile file is not sourced by any Wayland display managers, including Gnome.

**Comment by colemickens** [comment]
Does it make sense to open something new for that scenario? Maybe I will later if no one protests or points me in a better direction.

**Comment by berbiche** [comment]
> Does it make sense to open something new for that scenario? Maybe I will later if no one protests or points me in a better direction.

Please do :)

**Comment by kira-bruneau** [comment]
This has been fixed in NixOS with NixOS/nixpkgs#185987.

We now source `~/.profile` in `xsessionWrapper`, but I think we'll eventually want to generalize this to load the actual login shell environment for the given `$SHELL`. The way we have it hard-coded right now is intended to emulate the login shell environment for sh - which is what we were partially already doing by sourcing `/etc/profile`.

**Comment by auroraanna** [comment]
@kira-bruneau So `home.sessionVariables` is supposed to work graphical sessions again? It doesn't for me…

**Comment by thall** [comment]
@auroraanna same for me.

**Comment by thall** [comment]
@auroraanna I have the same problem. 
My workaround:
```
programs.bash.initExtra = ''
  export EDITOR="vim"
'';
```

**Comment by dacioromero** [comment]
I don't think this should be closed.

I use KDE Wayland, SDDM, and Zsh and my `home.sessionVariables` aren't sourced by either SDDM or KDE. This means `programs.mangohud.enableSessionWide` won't work with any program started outside of a terminal.

Following https://userbase.kde.org/Session_Environment_Variables I've added the following to my configuration:

```nix
{ config, ... }: {
  xdg.configFile."plasma-workspace/env/hm-session-vars.sh".text = ''
    . "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"
  '';
}
```

This fixes `programs.mangohud.enableSessionWide`

---

I'm not sure if this is a bug with KDE, SDDM, or with how NixOS packages them seeing that I've read in several places that SDDM and maybe even KDE should source files like .zprofile and .zshenv.

https://wiki.archlinux.org/title/environment_variables#Per_Wayland_session

> However, [SDDM](https://wiki.archlinux.org/title/SDDM) sources startup scripts for login shells on Wayland sessions too.

https://github.com/sddm/sddm/blob/5d260e2328b7ed44232ed8b3368bd59194d30357/data/scripts/wayland-session#L26

> zshenv is always sourced automatically.

**Comment by auroraanna** [comment]
> This has been fixed in NixOS with [NixOS/nixpkgs#185987](https://github.com/NixOS/nixpkgs/pull/185987).
> 
> We now source `~/.profile` in `xsessionWrapper`, but I think we'll eventually want to generalize this to load the actual login shell environment for the given `$SHELL`. The way we have it hard-coded right now is intended to emulate the login shell environment for sh - which is what we were partially already doing by sourcing `/etc/profile`.

oh, does that only work in Xorg sessions? That would explain why it's still not working for me. I'm using Wayland.

**Comment by haizaar** [comment]
@dacioromero [solution](https://github.com/nix-community/home-manager/issues/1011#issuecomment-1452920285) is a great step forward but still has a caveat - whatever is defined in `environment.variables` will override your `home.sessionVariables`.

Here is why:
* Plasma will load your `${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh`, which will set `__HM_SESS_VARS_SOURCED=1`
* When you start a new bash instance, e.g. through konsole, it will load `/etc/bashrc` (since the bash was [compiled](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/bash/5.nix#L45) with `-DSYS_BASHRC="/etc/bashrc"`), which will source `/etc/profile` first thing and then the rest of of `/etc/bashrc`
* `/etc/profile` loads environment generated by `environment.variables`. Hence, for example, if you have `less` enabled, it will setup `LESSOPEN` through `environment.variables` and trying to override `LESSOPEN` with `home.sessionVariables` will not work - the former will be sourced on every interactive bash opened while `home.sessionVariables` will be sourced only once by plasma
* Even if you source `home.sessionVariables` in your `~/.bashrc` it will still not work since `__HM_SESS_VARS_SOURCED` is already set by plasma

At this stage I wouldn't put interactive shell related stuff in `home.sessionVariables`

**Comment by dacioromero** [comment]
SDDM was updated to 0.20.0 and is in nixos-unstable https://github.com/NixOS/nixpkgs/pull/239389 and it seems to source my .zshenv so I don't need my workaround. It'll probably have the same caveat that @haizaar pointed out though.

**Comment by mrshiposha** [comment]
The following worked for me:

```
let homeManagerSessionVars = "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh";
in {
    environment.extraInit = "[[ -f ${homeManagerSessionVars} ]] && source ${homeManagerSessionVars}";
}
```

**Comment by landure** [comment]
bash source `~/.bash_profile` when the shell is a login shell (pure console).
It source `~/.profile` at login if `.bash_profile` is missing.
Otherwise, it only source `~./bashrc`.

`home.sessionVariables` are written to `~/.nix-profile/etc/profile.d/hm-session-vars.sh`, sourced in `~/.profile`, which is sourced in `~/.bash_profile`.

`programs.bash.sessionVariables`  are written to `~/.profile`.
They should be written to `~/.bash_profile`, to only be set for bash.

Both settings suffers of the same issues.
Please note that `zsh` seems to load `.profile` in interactive shells.

This is a fix for loading `home.sessionVariables` for bash interactive shells:

```nix
let
  homeManagerSessionVars = "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh";
in
{
    programs.bash.initExtra = ''
        [[ -f "${homeManagerSessionVars}" ]] && source "${homeManagerSessionVars}"
    '';
}
```

Replace `initExtra` by `bashrcExtra` to load `home.sessionVariables` in all (interactive and non-interactive) shells.

**Comment by gdennie** [comment]
Seems like an insanely persistent and critical bug to not be able to reliably set environment variables in a system intended to control session environments. Just surprised, that's all, as I this stuff is hard.

The following eventually worked for me. It shows up in a new console.  Note the use of the single quotes around the prompt text to prevent interpretation of the escape code by the Nix language:
```
  programs.bash.enable = true;
  programs.bash.initExtra = ''
    PS1='\u@\h:\w\n>'
  '';
```
