### ISSUE TITLE
When using integrated with nixos "suggested commands" aren't very visible and/or ran automatically

### ISSUE THREAD

**Issue by 06kellyjac** [nix-community/home-manager#1115]
I've used home-manager a lot by hand. The suggested commands (systemctl --user restart x etc...) aren't too much bother to run.
But now I've integrated it into nixos using the channel & `home-manager.users.blah = ` approach it's not easy to see these suggested commands without running `systemctl status home-manager-blah.service` and reading from there.
And as far as I can see tell doesn't run these commands itself.

Am I doing things wrong?

**Comment by 06kellyjac** [comment]
I've got this one-liner to quickly pull the suggested commands. Suggestions for improvements welcome
`systemctl status home-manager-XYZ.service | awk '/Suggested commands/{getline; split($0,a,"]: "); print a[2]}'`

**Comment by 06kellyjac** [comment]
I'm guessing #1388 means most services going forward will be managed automatically

To integrate the home-manager modules with `sd-switch` properly do they need to add these?:

```
[Unit]
X-SwitchMethod=restart
```

```
[Unit]
X-SwitchMethod=stop-start
```

**Comment by rycee** [comment]
Usually you shouldn't have to do anything special to the definition of the service. The default behavior is to stop then start the service, which is OK in most cases.

However, I had to revert the #1388 change due to its reliance on dbus. If you want auto start you now have to go back to using `systemd.user.startServices = true` in your configuration but unfortunately it still adds Ruby as a dependency. This method will default to restarting the service instead of stopping then starting.

**Comment by 06kellyjac** [comment]
Does enabling `systemd.user.startServices = true` auto restart services like `sxhkd`? as that just kills all the processes launched using it :sweat_smile:
