### ISSUE TITLE
Configure oh-my-zsh custom folder through home-manager

### ISSUE THREAD

**Issue by piegamesde** [nix-community/home-manager#1224]
Currently, `programs.zsh.oh-my-zsh.custom` simply contains the path to a oh-my-zsh custom directory. It'd be way cooler if I could also specify the content of that directory from home-manager, similar to `programs.zsh.plugins`.

**Comment by chisui** [comment]
I do this like this:

```nix
{ config, pkgs, ... }:
let
  agnoster-nix-theme = builtins.fetchurl {
    url = "https://gist.githubusercontent.com/chisui/0d12bd51a5fd8e6bb52e6e6a43d31d5e/raw/a97b74ce17c5f1befabe266ccf02a972cab2911b/agnoster-nix.zsh-theme";
    sha256 = "1m7qqrp8z0glnq81c9ldzmm0r42rgdmw8nk9hvssbjphx5khk6z7";
  };
  customDir = pkgs.stdenv.mkDerivation {
    name = "oh-my-zsh-custom-dir";
    phases = [ "buildPhase" ];
    buildPhase = ''
      mkdir -p $out/themes
      cp ${agnoster-nix-theme} $out/themes/agnoster-nix.zsh-theme
    '';
  };
in {
  programs.zsh = {
    enable = true;
    ...
    oh-my-zsh = {
      enable = true;
      plugins = [ "git" ];
      theme = "agnoster-nix";
      custom = "${customDir}";
    };
  };
}
```

**Comment by kirinnee** [comment]
Sorry to revive this thread, but would this still be possible? In the case, I'm trying to add a custom plugin [go-task-completions](https://github.com/sawadashota/go-task-completions), but there's no real way of doing this since the `$ZSH_CUSTOM=""` is exported after the `plugins=(... )` within the `.zshrc` when using home-manager.

The around is currently using `extraConfig` to emulate the `custom` option, which defeats the existence of the `custom` options

**Comment by chisui** [comment]
Why do you need to use `ZSH_CUSTOM` for that? Couldn't you just add something like this:
```nix
let
  go-task-completion = fetchGitHub {
    ...
  };
in {
  ...
  programs.zsh.oh-my-zsh,extraConfig = ''
    fpath+=${go-task-completion}
  '';
}
```
