### ISSUE TITLE
swaylock does not unlock correctly

### ISSUE THREAD

**Issue by SeTSeR** [nix-community/home-manager#1288]
### Issue description

swaylock does not unlock properly when used as screenlocker without `security.pam.services.swaylock = {}` option. Home-manager could recommend set this option when enabling sway module or also enable nixos sway module.

See also: https://github.com/NixOS/nixpkgs/pull/89019

#### Maintainer CC

@rycee @alexarice

#### Technical details

```
λ ~/ nix-shell -p nix-info --run "nix-info -m"                                                                                                                              ~
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09.20200529.135073a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200521_00b562c`
 - channels(root): `"nixos-20.09pre223023.fce7562cf46"`
 - channels(smakarov): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by primeos** [comment]
From https://github.com/NixOS/nixpkgs/pull/89179#issuecomment-636351919 (to document this here as well):

My personal suggestion would be to document the following in the `enable` option of the `home-manager` module for Sway:
- `programs.sway.enable = true;` should be added to the NixOS configuration (https://github.com/NixOS/nixpkgs/pull/89019#issuecomment-634845631 and this issue)
- Everything else should be configured via the `home-manager` module (https://github.com/NixOS/nixpkgs/pull/89179)

**Comment by mightyiam** [comment]
I don't know how PAM works.

I would imagine that one of the goals of home-manager is to minimize dependence on the system.

I would ask two questions: In a "typical" PAM configuration, can a user-installed swaylock operate? I am assuming that the answer is no, because this is what this issue seems to be about and I experience this, as well. Frustrating, BTW, since there's no hint of this until trying to input my password for the 10th time. And then I used `systemd-cgls` to find swaylock's PID and then `kill <pid>` to unlock my desktop.

The second question I would ask is: what is the bare minimum that needs to be changed in a "typical" PAM system configuration that would enable a use-installed swaylock to operate? Additionally, I would try to make that *not specific to swaylock*, but general enough that this feature is available to user executables. Does anyone know?
