### ISSUE TITLE
Don't override upstream defaults in gpg.nix

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#1301]
### Issue description

`modules/programs/gpg.nix` writes a lot of options to the generated `~/.gnupg/gpg.conf` even if these options are not specified by the home-manager user. I think this is problematic because home-manager's defaults override the upstream defaults. For a security application as important as GnuPG, I think this approach is problematic.

If there is a good reason for home-manager to specify some other defaults, I think (1) they should be optional, and (2) there should be a link to some documentation explaining why these default values are better than the upstream ones.

In general, I suggest to have `null` as default value for options in most cases and to only generate lines in configuration files for non-null settings.

#### Maintainer CC

@offlinehacker 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09.git.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `""`
 - nixpkgs: `/home/cassou/Documents/projects/nixos/system`
```

**Comment by scottwillmoore** [comment]
I think this is a very valid issue to be raised. Especially since the options `--cert-digest-algo`, `--s2k-digest-algo`, `--s2k-cipher-algo` are set and the GnuPG man page states that this may "create a perfectly valid OpenPGP message, but one that cannot be read by the intended recipient."

> GnuPG tries to be a very flexible implementation of the OpenPGP standard. In particular, GnuPG implements many of the optional  parts of the standard, such as the SHA-512 hash, and the ZLIB and BZIP2 compression algorithms. It is important to be aware that not all OpenPGP programs implement these optional algorithms and that by forcing their use via the `--cipher-algo`, `--digest-algo`, `--cert-digest`-algo, or `--compress-algo` options in GnuPG, it is possible to create a perfectly valid OpenPGP message, but one that cannot be read by the intended recipient.

I also think that it would be better to leave the user with a vanilla configuration, unless they explicitly opt into the Home Manager recommendations with another option such as `useRecommendedSettings`. In addition, the recommended settings should be justified.

There is a workaround. These settings are set with `mkDefault` and can therefore be overridden. In addition, if the value is set to false the setting will not be included in the configuration. You can use the settings below to remove the settings provided by home manager by default.

```nix
{
  programs.gpg.settings = {
    cert-digest-algo = false;
    charset = false;
    default-preference-list = false;
    fixed-list-mode = false;
    keyid-format = false;
    list-options = false;
    no-comments = false;
    no-emit-version = false;
    no-symkey-cache = false;
    personal-cipher-preferences = false;
    personal-compress-preferences = false;
    personal-digest-preferences = false;
    require-cross-certification = false;
    s2k-cipher-algo = false;
    s2k-digest-algo = false;
    use-agent = false;
    verify-options = false;
    with-fingerprint = false;
  };
}
```

However, while this does work, the [`cfgText`](https://github.com/nix-community/home-manager/blob/9e565f0d9d41c19a94f55af205c328ec5177fc0a/modules/programs/gpg.nix#L11) is generated with [`toKeyValue`](https://github.com/NixOS/nixpkgs/blob/74640b818ed128160aab92ce68dd7aac135f6527/lib/generators.nix#L82) with a custom [`mkKeyValue`](https://github.com/nix-community/home-manager/blob/9e565f0d9d41c19a94f55af205c328ec5177fc0a/modules/programs/gpg.nix#L8) which uses [`optionalString`](https://github.com/NixOS/nixpkgs/blob/74640b818ed128160aab92ce68dd7aac135f6527/lib/strings.nix#L210) for non-string values. When a false value is provided, this does remove the setting, however it still includes a newline in the configuration. Therefore, you end up with an empty configuration but with 18 blank newlines...
