### ISSUE TITLE
Neovim plugin problem

### ISSUE THREAD

**Issue by pca006132** [nix-community/home-manager#1308]
### Issue description
`coc-nvim` package in unstable does not work using the `program.neovim`.
It would produce error messages like
```
Generating remote plugin manifest
[coc.nvim] creating data directory: /homeless-shelter/.config/coc
Error detected while processing function coc#rpc#start_server[13]..coc#util#get_data_home:
line   16:
E739: Cannot create directory /homeless-shelter: permission denied
vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /nix/store/2xh3r8lyp66qr4k501lhdzxpddi0i89f-neovim-0.4.3/rplugin.vim
Generating rplugin.vim failed!
builder for '/nix/store/rmnfvw5344n30hybkfi96fi108c5ing7-neovim-0.4.3.drv' failed with exit code 1
cannot build derivation '/nix/store/7mvrqiccwk0d986cvfykrcpf8vv8776r-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hkv4f9niq7ivxsizy3z4i24v8k539fal-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hkv4f9niq7ivxsizy3z4i24v8k539fal-home-manager-generation.drv' failed
```

However, it works fine using `pkgs.neovim.override`.

Related config (I used `pkgs.vimPlugins` to avoid error for using unstable): 
https://github.com/pca006132/dotfiles/blob/9ce86e678f352b8eb66e6982883c2f349895766a/home.nix#L106

Working version with `pkgs.neovim.override`: 
https://github.com/pca006132/dotfiles/blob/master/home.nix

I suspect this is related to wrapNeovim, but I am relatively new to nix so I am not sure.

#### Maintainer CC
(I am not sure if I should CC the maintainer of the neovim package or people touched the neovim module here, so I would just CC those touching the module here...)

@teto @Gerschtli  @rvolosatovs @rycee @kalbasit @leemhenson @jonringer  

#### Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1822.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(pca): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
not sure if that's enough to kil the builds but 2 errors are here:
```
E739: Cannot create directory /homeless-shelter: permission denied
vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.
```
I found coc a bit hard to use on nixpkgs so I am using neovim's builtin lsp instead. When I was using coc, I used to install it via vim-plug rather than via nix.

**Comment by jonringer** [comment]
```
E739: Cannot create directory /homeless-shelter: permission denied
```
is because $HOME was referenced during the build

**Comment by pca006132** [comment]
> ```
> E739: Cannot create directory /homeless-shelter: permission denied
> ```
> 
> is because $HOME was referenced during the build

Yes I know that is the direct cause. However, I think the problem is that why would it work for neovim but not wrapNeovim, is there any difference between the two? And what is the reason to use wrapNeovim instead of neovim?

**Comment by teto** [comment]
neovim = (wrapNeovim neovim-unwrapped) so they are similar (neovim is the result of calling wrapNeovim with the raw neovim package), it means neovim is a wrapper with a generated configuration. It tries to generate the manifest file for remote plugins but coc-nvim doesn't play nice with it, probably you should export HOME somewhere or modify coc_nvim so that it doesn't do that:
```
Error detected while processing function coc#rpc#start_server[13]..coc#util#get_data_home:
line   16:
E739: Cannot create directory /homeless-shelter: permission denied
```

**Comment by ceedubs** [comment]
It looks like this is because coc.nvim [uses $XDG_CONFIG_HOME](https://github.com/neoclide/coc.nvim/blob/9dfd3c611ad620e8ff9909c31e78e1b4cc40d320/autoload/coc/util.vim#L307) as a place to _write_ data. I'm guessing that the difference between `program.neovim` and `program.neovim.override` has to do with how/whether they are setting `$XDG_CONFIG_HOME`.

A somewhat hacky but easy workaround is to set something like `let g:coc_data_home = $HOME . '/.config/coc'` in your vimrc, and set the path to a non-$HOME path of your choice.

**Comment by teto** [comment]
there is now coc support in home-manager so I suppose it now works. Feel free to reopen if that's not the case.
