### ISSUE TITLE
sway module is not enabling dbus properly

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1370]
### Issue description

Via @berbiche's comment, here https://github.com/rycee/home-manager/pull/1329#issuecomment-653244734, I have discovered that the sway module doesn't seem to be enabling `dbus` properly by default.

In my config, I had `wrapperFeatures = { gtk = true; }`, and the sway module has `base = mkWrapperFeature true`, so it should have been on by default.

Yet, per @berbiche's instructions, I did in fact need one or both of the additional `extraSessionCommands` to get the `waybar` systemd unit to not boot loop.

I suspect this may explain other small things that have worked differently in the past, depending on how I've started sway.

#### Maintainer CC

cc: @alexarice @cole-h @rycee @rvolosatovs (recent committers, potential users)

#### Technical details

```
> nix-shell -p nix-info --run "nix-info -m"
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
# :P
```
(This is on head of h-m, stable nix.)

**Comment by alexarice** [comment]
I think [this line](https://github.com/NixOS/nixpkgs/blob/a2cdd1464b72082c45277c9d9f502c684668f510/pkgs/applications/window-managers/sway/wrapper.nix#L20) might be at fault. My bash isn't very good but it looks like there should be a "!" in there to me.

**Comment by alexarice** [comment]
Not sure if my first thought was correct but the module just passes the options straight to the nixos wrapper so I'd be surprised if you don't get the same issue without the hm module

**Comment by colemickens** [comment]
@alexarice I just recently adopted HM and can confirm I'd seen weird things before adopting it.

I had to restart my computer. Even after logging out and logging in, the session was tainted with a DBUS_SESSION_BUS_ADDRESS before I could even run anything (I think this is due to the systemctl import command in @berbiche's config that I ran).

```
#login
sway
# start termite
echo $DBUS_SESSION_ADDRESS
unix:abstract=/tmp/dbus-bTRJwVfgMT,guid=15002e2ca33fbfb8d45c6f4c5efe86ca
```

**Comment by colemickens** [comment]
In that same sway session though, systemd units see a different dbus address:

```
> systemctl --user show-environment | rg DBUS_SESSION
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

**Comment by berbiche** [comment]
> In that same sway session though, systemd units see a different dbus address:
> 
> ```
> > systemctl --user show-environment | rg DBUS_SESSION
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> ```

This is the reason I am exporting the `DBUS_SESSION_BUS_ADDRESS` variable in `extraCommands` otherwise tools like [playerctl](https://github.com/altdesktop/playerctl) (a tool that controls MPRIS players like Spotify, Firefox, Rhythmbox, Chromium, etc.) fail to work.

Now that I am looking at the lines pointed out by @alexarice, exporting the `DBUS_SESSION_BUS_ADDRESS` within the `extraCommands` resulted in Sway not running inside a `dbus-session`.

I will report back after testing Sway without the variable and the `systemctl --user import-environment` bit.

**Comment by berbiche** [comment]
The `DBUS_SESSION_BUS_ADDRESS` variable is not needed in the `extraCommands`. It is correctly set when Sway is launched with `dbus-session` (when enabling `wrapperFeatures = { base = true; };`)

**Comment by alexarice** [comment]
Are you both using a display manager? I've been using
```
waybar = {
      Unit = {
        Description = pkgs.waybar.meta.description;
        PartOf = [ "graphical-session.target" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.waybar}/bin/waybar";
        RestartSec = 3;
        Restart = "always";
      };
    };
```
and have had no dbus related problems.

**Comment by alexarice** [comment]
I also have this though
```
> systemctl --user show-environment | grep DBUS_SESSION
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-VUH8E5gMmK,guid=c19728d0396111c752f900325efef12f
> echo $DBUS_SESSION_BUS_ADDRESS
unix:abstract=/tmp/dbus-VUH8E5gMmK,guid=c19728d0396111c752f900325efef12f
```

**Comment by berbiche** [comment]
Waybar is available on a DBUS address if it is has access to DBUS. I don't know what API is exposed there though.

**Comment by alexarice** [comment]
Is there an easy way to reproduce the problems in this issue? I am using `nixos-unstable` and hm-master and haven't added any dbus related variables or options in home manager and all this seems to work fine (I am using playerctl from waybar without any issues)

**Comment by archseer** [comment]
Hi! I ran into the same issue with waybar not starting because it's waiting for the user DBus service to start.

```
# sample config
wayland.windowManager.sway = {
    enable = true;
    systemdIntegration = true; # beta
}
programs.waybar = {
    enable = true;
    systemd.enable = true;
}
```

The way systemd sets up DBUS_SESSION_BUS_ADDRESS is that it sets up `dbus.socket` which then starts `dbus.service` when the socket is first accessed (If you `systemctl --user enable dbus.service` it'll tell you the service isn't supposed to be explicitly enabled but possibly starts as a `.socket` dependency).

In the waybar definition, these two lines are unnecessary, and `Type=dbus` is enough:

https://github.com/nix-community/home-manager/blob/a3a0f1289acac24ce2ffe0481bf8cabd3a6ccc64/modules/programs/waybar.nix#L359-L360

[As explained by the docs:](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Implicit%20Dependencies)

- Services with `Type=dbus` set automatically acquire dependencies of type `Requires=` and `After=` on `dbus.socket`.

- Socket activated services are automatically ordered after their activating `.socket` units via an automatic `After=` dependency. Services also pull in all `.socket` units listed in `Sockets=` via automatic `Wants=` and `After=` dependencies.

Removing `Requisite`/`After` makes the service properly start for me.

(Since DBUS_SESSION_BUS_ADDRESS is set at login by systemd I think the sway wrapper feature might be unnecessary too.)

**Comment by berbiche** [comment]
@archseer can you open a PR? Thanks

**Comment by archseer** [comment]
Done, #1628. I think this issue should stay open for a bit longer, I'm trying to verify if everything works correctly if we drop the base wrapper on sway as well.

**Comment by archseer** [comment]
Okay, @rycee actually made the change so that [dbus is always socket activated](https://github.com/NixOS/nixpkgs/pull/97801), but it's not in a stable release yet.

The base wrapper around sway is obsolete:
https://github.com/NixOS/nixpkgs/blob/80e0a208926ac31d15327210e65f7980d6b08809/pkgs/applications/window-managers/sway/wrapper.nix#L14-L26

Because DBUS_SESSION_BUS_ADDRESS will always be set.

**Comment by berbiche** [comment]
I think the problem is resolved and this issue can be closed?
