### ISSUE TITLE
Option home-manager.users.<name>.home.file.<file>.target does not work as expected

### ISSUE THREAD

**Issue by sivizius** [nix-community/home-manager#1451]
### Issue description

Just setting the option `home-manager.users.<name>.home.file.<file>.target` result in:
```
error: The option `home-manager.users.<name>.home.file.<file>.source' is used but not defined.
```

Setting `home-manager.users.<name>.home.file.<file>.target` with `home-manager.users.<name>.home.file.<file>.text = ""` does not fail, but I it does not seem to create a softlink or file whet target set to `"$HOME/someFileInHome"`.
With `"~/someFileInHome"` it just creates a directory `"~"` in `$HOME` with broken links.
with `"someFileInHome"` it just fails with `Error installing file '<file>' outside $HOME`.

Setting `home-manager.users.<name>.home.file.<file>.source` does not seem to help either.

#### Maintainer CC

@rycee 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.15, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - channels(sivizius): `""`
 - nixpkgs: `/nix/store/zvahn557d48m0dc69h6i98av6dmks3m2-master.tar.gz`
```

**Comment by rycee** [comment]
You must specify one of `source` or `text`, otherwise you'll get the error message about `source` not being defined.

About the other issues, could you provide a concrete example? The file target should not include any shell variables or start with a `/`. E.g., `home.file.A.text = "B"` should create a symlink called `A` in your home directory pointing to a file containing the string `B`.

**Comment by sivizius** [comment]
I want to create a symlink to another existing file, I assumed this option is for this purpose.
