### ISSUE TITLE
`EDITOR="code --wait" home-manager edit` doesn't work

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#1496]
### Issue description

I have my `EDITOR` env variable set to `code --wait` (see eg https://stackoverflow.com/a/57144660/3880977), but home-manager isn't happy about this:
```
❯ EDITOR="code --wait" home-manager edit
/home/skainswo/.nix-profile/bin/home-manager: line 168: exec: code --wait: not found
❯
```

#### Technical details

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-45-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-21.03pre243353.6d4b93323e7"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

**Comment by cole-h** [comment]
That's probably because the `$EDITOR` env var is quoted in the `home-manager` script (thus making it look for a binary `code --wait`, not `code` with argument `--wait`):

https://github.com/nix-community/home-manager/blob/2c6a02374467a6fb074f548f89f8e8d1d6f2cd12/home-manager/home-manager#L168

A better idea would be to make a wrapper script that contains the following:

```sh
#!/usr/bin/env bash
exec code --wait "$@" # or ${pkgs.asdf}/bin/code
```

and set your `$EDITOR` to that.

**Comment by samuela** [comment]
@cole-h Yeah, that would definitely be a workaround. Although home-manager goes against the grain of what many other programs support with `EDITOR`, eg.
```
> EDITOR="code --wait" git commit
hint: Waiting for your editor to close the file... 
```
