### ISSUE TITLE
[Question] How do I handle secrets when managing configs containing passphrases in cleartext ?

### ISSUE THREAD

**Issue by 573** [nix-community/home-manager#1497]
I want to manage a searx/settings.yml in home.nix.

```
# runCommandEx.nix
# usage: $ cat $(nix-build runCommandEx.nix) | grep secret_key
with import <nixpkgs> { };
pkgs.runCommand "unsafish"
{
  input = pkgs.fetchFromGitHub {
    owner = "searx";
    repo = "searx";
    rev = "f0ca1c34833e2c0c79af68e699e646d77167a269";
    sha256 = "1lwin9jk6mgx39x73sap2d20wyxqfd4gylbmba9hjmiwz3ap9nvx";
  } + "/searx/settings.yml";
} ''
  sed \
  -e "s!port : 8888!port : 8889!g" \
  -e "s!debug : False!debug : True!g" \
  -e "s!secret_key : \"ultrasecretkey\"!secret_key : \"`${pkgs.openssl}/bin/openssl rand -hex 32`\"!g" \
  "$input" > "$out"
''

```

How can I prevent that the file with the generated passphrase lands in nix store ?

**Comment by cole-h** [comment]
You can't. All Nix-created files are added to the store world-readable. The only way around this is by creating secrets imperatively and pointing your software to its path, or using something like [`nixus`](https://github.com/infinisil/nixus) or [`nixops`](https://github.com/nixos/nixops), which have some mechanisms to deal with secrets without adding them to the store.

**Comment by 573** [comment]
Are there examples of how to point to the path of the imperatively generated file ? #257 mentions managing just symlinks, which should be sufficient, can you confirm that assumption ?

**Comment by cole-h** [comment]
It depends on the software. For example, there is the NixOS option `networking.wireguard.interfaces.<name>.privateKeyFile`, which will tell Wireguard to read the private key from that file. I don't know if searx has a setting that will let you change where it reads the secret key from. Symlinks will only work if the software has some way to get the secret from a path instead of having it be hardcoded into the file.
