### ISSUE TITLE
is there a way to restore home.conf?

### ISSUE THREAD

**Issue by MarkRBM** [nix-community/home-manager#1507]
unfortunately I just ruined my entire weekend but running `rm -rf ~` instead of `rm -rf ./~`

luckily I use home-manager and by following the restore steps in your wiki I was able to get my most recent home generation set up back so I don’t have to start from scratch with a bare bones nixos again.

However my home.nix was in my ~/.config/nixpkgs dir along with the rest of the files it used to build the most recent generation that I just restored.  Because I am a dumb dumb I had not pushed these files to git or anywhere else in a very long time.

Are these files sitting anywhere in the nix-cache or elsewhere that I could restore them from?

**Comment by rycee** [comment]
Ouch, sorry to hear that! Unfortunately the source Nix files will not end up in the Nix store by default. Some do set things up so that their configuration gets copied into the generation, e.g., by doing something like
```
home.file.".cache/hm-current-config".source = ./.;
```

So unfortunately I think you'll have to recreate the configuration as best you can using the latest HM generation as a base. If you need help reverse engineering a HM configuration that recreates some part of a file then feel free to join the #home-manager channel on freenode and we'll see what we can do.

**Comment by MarkRBM** [comment]
thank-you I think I have it all stitched together and my environment appears to be back to normal **except** for when I run home-manager switch I get the following error:

`The option value `home.file "in /home/mark/.nix-defexpr/channels/home-manager/modules/programs/zsh.nix" is not of type attribute set of submodules'.

I think it still works because my home directory is all set up but it still throws that error, any ideas on how to fix that one?

**Comment by berbiche** [comment]
Hi, I will close this issue as I believe it has been resolved, if you still need help feel free to reopen a new issue! :smiley:
