### ISSUE TITLE
Using InstallFirefoxAddon.py for firefox.extensions

### ISSUE THREAD

**Issue by demostanis** [nix-community/home-manager#1585]
I have very little experience with Nix, but have created a small Python script with the ability to install Firefox addons only using their name, which would remove the need to have all extensions in the NUR. I was wondering if it was compatible with Home Manager (is there a way to run a python script in Nix?) and if it could be implemented.

**Comment by evalexpr** [comment]
You don't need all the extensions in the NUR, it's possible to use something like `buildFirefoxXpiAddon` from https://gitlab.com/rycee/nur-expressions/-/blob/master/pkgs/firefox-addons/default.nix to install which ever Firefox addons you want, e.g.

```
x = buildFirefoxXpiAddon {
  pname = "x";
  url = "...";
}

firefox.extensions = [ x ];
```

**Comment by demostanis** [comment]
Oh that's cool, but wouldn't it be better to simply put the addon's name and that Home Manager searches it itself?

**Comment by demostanis** [comment]
Would be easier than having to specify a sha256sum, a name and an addon ID no one knows about. InstallFirefoxAddon does all that for you.

**Comment by colemickens** [comment]
@demostanis A more conventional approach would be a python script that processes a list of firefox extension names and then outputs a JSON or Nix file containing the metadata that Nix needs to build (including the sha256sum).

The sha256sum needs to be specified somewhere, statically, otherwise Nix can't build reproducably. To further emphasize this, while you can run a python script during a Nix build, it is sandboxed and cannot access the Internet at all...

**Comment by demostanis** [comment]
InstallFirefoxAddon requires internet access to work. What would be needed is to implement it in Nix, however I'm not sure there's a way to parse JSON Mozilla's search API and find the right string in the extension's source code (what InstallFirefoxAddon does)

**Comment by demostanis** [comment]
I read there's a new way of installing Firefox extensions in Nix, so I'm closing.
