### ISSUE TITLE
Investigate GitHub actions test time blow up

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#1610]
### Issue description

I have a feeling `pkgs.formats` is blowing up the pipeline.
~~Currently all packages using `pkgs.formats` lack tests.~~

See:
- https://github.com/nix-community/home-manager/search?q=formats
- #1609: https://github.com/nix-community/home-manager/actions/runs/364984690
- #1595: https://github.com/nix-community/home-manager/actions/runs/364972093

I can successfully run all tests locally without any _perceivable_ blow up in memory size or time.

#### Maintainer CC

@rycee 
@Infinisil (as the creator of `pkgs.formats`, do you have any idea as to how `pkgs.formats` could blow up the pipeline?)

**Comment by berbiche** [comment]
Looks like the tests started taking longer when `i3status-rust` was merged.
It uses `pkgs.formats` for its configuration.

**Comment by rycee** [comment]
I suspect the long times somehow were related to the code format test. Because that test copies the checked out repository to the Nix store it will cause the entire repo to be read into memory and presumably it at some point got too large for the builder to handle. Running it locally the max residency of that test was a bit above 500MiB, which doesn't seem too bad but perhaps the builders are very constrained.

In any case, I don't know why it started being slow instead of killing the job with an out of memory error but the jobs seem to run again, now that I removed the format test.

**Comment by berbiche** [comment]
I wonder whether #1624 would resolve this issue?
