### ISSUE TITLE
state version check for modules prevents pure flake build

### ISSUE THREAD

**Issue by codygman** [nix-community/home-manager#1657]
https://github.com/nix-community/home-manager/blob/e6a58a7e718ac5b21fa8bc9e937cc19bcd8d9293/modules/modules.nix#L217

Causes nrdxp/nixflk#30

A user in #nixos recommended this patch:

```


1 --- err.nix	2020-12-16 01:27:30.797262896 +0100
2 +++ fixed.nix	2020-12-16 01:28:37.174425479 +0100
3 @@ -1,5 +1 @@
4 -_module.args.pkgsPath = lib.mkDefault (
5 -  if versionAtLeast config.home.stateVersion "20.09" then
6 -    pkgs.path
7 -  else
8 -    <nixpkgs>);
9 +_module.args.pkgsPath = lib.mkDefault pkgs.path;
```

But after said they think you guys might have a good reason for this state version requirement.

**Comment by berbiche** [comment]
Flakes are only supported with the 20.09 release (the latest) and on master.
I recommend changing your `home.stateVersion` to reflect the latest version.

**Comment by berbiche** [comment]
@rycee should the default of "18.09" be updated in https://github.com/nix-community/home-manager/blob/master/modules/misc/version.nix to 20.03 or even 20.09?

**Comment by cole-h** [comment]
State versions should only be bumped after the user is certain they're not affected by any breaking changes (or have addressed everything in e.g. https://github.com/nix-community/home-manager/blob/master/doc/release-notes/rl-2009.adoc#state-version-changes).

The default is 18.09 because that's the NixOS version when state versions were introduced in home-manager.

**Comment by nrdxp** [comment]
I am the auhor of the project mentioned right above me. Since my repo is a template, users have to define their own users, meaning I have no way to easily set this in the template. Is there a simple way I am not aware of to define an option default for any given user, or could we add the funcitonality for home-manager to check the `system.stateVersion` on NixOS based systems?

**Comment by codygman** [comment]
> I am the auhor of the project mentioned right above me. Since my repo is a template, users have to define their own users, meaning I have no way to easily set this in the template. Is there a simple way I am not aware of to define an option default for any given user, or could we add the funcitonality for home-manager to check the `system.stateVersion` on NixOS based systems?

I figured it out recently and was planning on sending a PR but can't yet. Also it's not the NixOS state version but home managers.

This needs added to the user:

```nix
home-manager.users.nixos = {
    imports = [ ../profiles/git ../profiles/direnv ];
    home.stateVersion = "20.09";
  };
```

The caveat being that if anyone whose home manager config is incompatible with that state version they'll get errors.

My guess is that change and maybe a note in the documentation linking to the home manager state version changelog in case someone has problems is best.

Closing this issue since there's no problem with home manager here.
