### ISSUE TITLE
Release cycle change

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#1662]
### Issue description

In light of NixOS changing its release cycle (XX.05 & XX.11), I presume Home Manager will follow?
https://discourse.nixos.org/t/21-05-call-for-release-manager/10204

#### Maintainer CC

@rycee

**Comment by rycee** [comment]
Yeah, there is no point in having a different cycle. I'm not sure whether the next release will be called 21.03 or 21.05, though. Both Nixpkgs and Home Manager have already introduced 21.03 as the next release version. I guess we'll have to adjust to whatever version number Nixpkgs ends up having.

**Comment by bb010g** [comment]
https://github.com/NixOS/rfcs/pull/80 was accepted. The next NixOS release will be 21.05.

**Comment by rycee** [comment]
True, I saw that and realize that 21.05 is mostly decided but I'd prefer to wait on committing HM to 21.05 until the code in Nixpkgs actually says 21.05.

Anyway, I don't think it'll be any issues switching HM to the new release cycle since we have not yet made any changes tied to the 21.03 state version.

**Comment by berbiche** [comment]
https://github.com/NixOS/nixpkgs/pull/107565

**Comment by jonringer** [comment]
Yes, we are shifting the mention of everything to `21.05`. Some modules make a reference to `stateVersion = "21.03"` which will probably stay and it will be treated as a phantom release.
