### ISSUE TITLE
VSCode Live Share can't join session

### ISSUE THREAD

**Issue by analognightmare** [nix-community/home-manager#1667]
### Issue description

I install VSCode with the Live Share extension like this:

```
  programs.vscode = {
    package = unstable.vscode;
    enable = true;
    extensions = [
      unstable.vscode-extensions.bbenoist.Nix
      unstable.vscode-extensions.vscodevim.vim
      unstable.vscode-extensions.matklad.rust-analyzer
      unstable.vscode-extensions.ms-vsliveshare.vsliveshare
    ];
  };

```

And when I start VSCode I can log into my GitHub account but when trying to join a session I get this error:

![2020-12-19-104705_476x128_scrot](https://user-images.githubusercontent.com/20466293/102696000-648b4900-41e8-11eb-8077-d9433041a55a.png)

When trying to host/share my own session it doesn't do anything and there's (visible) no error (message) either.

Any idea what I am doing wrong here? Please let me know what other technical information I can provide.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.14, NixOS, 20.09.2290.647cc06986c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(user): `"home-manager-20.09, nixpkgs-unstable-21.03pre258655.00941cd747e"`
 - channels(root): `"nixos-20.09.2290.647cc06986c, nixpkgs-unstable-21.03pre258655.00941cd747e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

```
code --version
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
```

Live Share extension seems to be:

```
ms-vsliveshare.vsliveshare-1.0.3375
```

**Comment by rycee** [comment]
Unfortunately I don't know anything about this. Perhaps @jraygauthier, the Nixpkgs maintainer of the extension has seen this error before?

**Comment by jraygauthier** [comment]
The extension was working fine at the time it was merged. I am not a regular user of the extension nor am I a user of home manager (yet). I will take some time later to check if I can reproduce by using the latest nixpkgs version of the package. Currently on stable 20.09 using same version of code as @analognightmare.

**Comment by rycee** [comment]
Thanks! I'm not a user of vscode or live share so I'm really poorly equipped to debug this. You can see how HM is wiring in the extensions here: https://github.com/nix-community/home-manager/blob/2901044520fbed466eea8b91df55183297eacd47/modules/programs/vscode.nix#L119-L135

I tried editing one of the HM tests to also install this extension and it shows that the extension ends up in

    ~/.vscode/extensions/ms-vsliveshare.vsliveshare

while keybindings end up in

    ~/.config/Code/User/keybindings.json

**Comment by Sir4ur0n** [comment]
Have you tried using https://github.com/msteen/nixos-vsliveshare/ ? I need to run `fix-vsliveshare` sometimes after a NixOS/Home Manager upgrade but other than thatm it seems to work well.

It may be great to integrate it automatically in Home Manager, or at least document it though

**Comment by jraygauthier** [comment]
Using vscode 1.51.1 (from 20.09 `13f19ce5d43edd43dd8efc8166105003e74ad520`) with live share extension v1.0.2902 from nixpkgs latest (`e24bf9062b4b23f4c11f57399d11ad73c86e0828`) everything still works fine. I can start a collaborating session from one windows and attach to it from another windows. I am however not installing it through home manager but using nixpkgs's way as follow:

```nix
(vscode-with-extensions.override {
  vscodeExtensions = [pkgs_latest.vscode-extensions.ms-vsliveshare.vsliveshare]
})
```

Why I am using `pkgs_latest` is because the extension was not merged soon enough so that it is part of the stable branch.

Note that it is possible to easily test latest code + extension in isolation using either one of the following:

```bash
$ nix-shell -I nixpkgs=. -p 'with import <nixpkgs> {config={allowUnfree = true;};}; vscode-with-extensions.override {vscodeExtensions = with vscode-extensions; [ms-vsliveshare.vsliveshare];}'
```

````bash
$ nix-build -I nixpkgs=. -E 'with import <nixpkgs> {config={allowUnfree = true;};}; vscode-with-extensions.override {vscodeExtensions = with vscode-extensions; [ms-vsliveshare.vsliveshare];}'
```

Maybe you will be able to reproduce. If so, it might indicate some dependency we fail to capture / patch as part of the extension nix package.

**Comment by jraygauthier** [comment]
Some hypothesis as to why it might not work in the context of home-manager: 

if I understood well by looking at `home-manager/modules/programs/vscode.nix`, creates a writable directory at `~/.vscode/extensions/ms-vsliveshare.vsliveshare` for the extension dir  which is the root of a tree of symlink to the actual extension files in the nix store. 

The extension has been tested in the context of a read-only extension directory.

It might be that in the context of a writable extension dir, the extension succeeds in writing some files which it couldn't previously (when tested in the context of a read-only directory) breaking some of the patches that makes the extension work in the context of nix.

Some vscode extensions (such as this one) require some extensive sometimes brittle patching to work with nix and a read-only nix store. 


@analognightmare: You can validate the above hypothesis by making your extension directory read-only and see if it works better.

Otherwise, if the above still does not work, it would greatly help if you activate the logging for your extension (vscode user settings):

```json
    "liveshare.diagnosticLogging": true,
    "liveshare.diagnosticMode": true,
```

retry you join operation and provide us with the logs under *output* tab for *Visual Studio Live Share* and *Log (Extension Host)*.

I / we then might be able to provide some more help and maybe provide fix this particular use case.

**Comment by cideM** [comment]
Just chiming in to say that I have the same problem. When installed the Nixpkgs way

```
with pkgs.vscode-extensions; {
  home.packages = [
    (pkgs.vscode-with-extensions.override {
      vscode = latest;
      vscodeExtensions = [
        ms-vsliveshare.vsliveshare
      ];
    })
  ];
}
```

it works, when installed the HM way it doesn't. I haven't had time to debug this though.

**Comment by berbiche** [comment]
@cideM Thanks for the sample code. I finally got live share to work on Nix! :smile: 

Here's the complete configuration I use to make it work with `programs.vscode` and Codium (the OSS build of vscode):

``` nix
let
  # Change this line to the vscode version you wish to use
  package = pkgs.vscodium;

  extensions = with pkgs.vscode-extensions; [
    ms-vsliveshare.vsliveshare
  ];

  finalPackage = (pkgs.vscode-with-extensions.override {
    vscode = package;
    vscodeExtensions = extensions;
  }).overrideAttrs (old: {
    inherit (package) pname version;
  });
in
{
  programs.vscode = {
    enable = true;
    package = finalPackage;
    extensions = [ ]; # The default value is the empty list but make sure to leave this empty!
  };
}
```

**Comment by wmertens** [comment]
How can I have partly home-manager managed extensions and partly own extensions?

**Comment by wmertens** [comment]
self-answer: using the  with-extensions you can't because they point to a generated set in the store and vscode only uses a single extensions dir.
How about making the with-extensions wrapper symlink the required extensions into the user extensions dir?

**Comment by wmertens** [comment]
Turns out that that's exactly what the wrapper is doing, however, vscode auto-update instantly overwrites the vslive extension with a broken version :confounded:

**Comment by wmertens** [comment]
So, halfway-ok solution:

Use this configuration in home.nix:
```nix

  programs.vscode = {
    enable = true;
    extensions = with pkgs.vscode-extensions; [
      bbenoist.Nix # Obviously ;)
      ms-vsliveshare.vsliveshare
      # whatever else you want
    ];
  };
```

Then VSCode should have the extension, and it will auto-update it when a newer version appears, breaking it. So turn off auto-update.

Any time you want to update, you afterwards need to run the profile activation again. To do so, run `home-manager instantiate`, read the derivation to find the output, and run the activation script again.

:point_right: it would be nice to have a `home-manager activate` command for this. :point_left:
