### ISSUE TITLE
The format script shouldn't have a manually maintained list of exclusions

### ISSUE THREAD

**Issue by peterhoeg** [nix-community/home-manager#1672]
### Issue description

The `format` script contains a long list of exclusions supposedly due to "open
pull requests". This clearly doesn't scale and we should simply just require the
use of `nixpkgs-fmt`.

An argument could reasonably be made that if a particular file ends up super
ugly, that it should be excluded, but it is *far* easier for everyone to simply
stick to a standard. nixpkgs-fmt isn't perfect but a standard means less
bike-shedding and this way we can all spend time on nicer things than code
formatting.

Cc: @rycee

**Comment by rycee** [comment]
The script is progressively getting smaller and is simple for me to maintain, I more or less autogenerate it from the GitHub API. At some point we can remove the remaining exception but for now I don't mind maintaining it. I think even if we remove all the exceptions, it makes sense to keep a format script since asking people to run

    find . -name '*.nix' -exec nixfmt {} +

is a bit more ugly than asking them to run `./format`. Also, since the script pins Nixpkgs, everybody gets the same version of nixfmt and its way of formatting.

Oh, just for completeness, HM uses [nixfmt](https://github.com/serokell/nixfmt), not nixpkgs-fmt.

**Comment by berbiche** [comment]
Superseded by #1953
