### ISSUE TITLE
support input method engines such as fcitx

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#169]
I have been fixing fcitx program. It is installed systemwide but this is typically the kind of program I would rather configure via home-manager.

I wonder if nixos/modules/i18n/input-method/fcitx.nix could be reused in via blackholing some variables and overriding/aliasing others ? 
```
    environment.variables = {
      GTK_IM_MODULE = "fcitx";
      QT_IM_MODULE  = "fcitx";
      XMODIFIERS    = "@im=fcitx";
    };
    services.xserver.displayManager.sessionCommands = "${fcitxPackage}/bin/fcitx";
```

**Comment by rycee** [comment]
I had a quick look at the NixOS input method modules and they do indeed seem reasonable to use on a per-user basis. So I'd be happy to add something like that to HM. Unfortunately, it's unlikely that I'll find the time to do it myself since I'm starting a full-time freelance project after the new year and will be very short on time.

FWIW my configuration includes `home.sessionVariables.GTK_IM_MODULE = "xim";` and as far as I can tell it works fine in all gtk applications.

**Comment by spirobel** [comment]
when I do this 

> home.sessionVariables.GTK_IM_MODULE = "xim";

everything starts to lag.[https://wiki.archlinux.org/index.php/Fcitx]( https://wiki.archlinux.org/index.php/Fcitx) also mentions this.
But if i dont do it I can only switch keyboard layouts with **fcitx-configtool**.
**xkb-switch** or **fcitx-remote** does not work anymore.
I wonder why this is the case.

**Comment by teto** [comment]
still interested

**Comment by pca006132** [comment]
Hi, how is the state of this issue? I also want to install it for my user (without system-wide installation), is there any example configuration for this?

**Comment by Kranzes** [comment]
Take a look at https://github.com/nix-community/home-manager/pull/2110 :eyes:

**Comment by chuahou** [comment]
Given that #2110 has been merged, should this be closed?

**Comment by Kranzes** [comment]
Sure!

**Comment by rycee** [comment]
@mainrs That is correct, it will be part of the 21.11 release.
