### ISSUE TITLE
pam session variables are being deprecated

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#1691]
> I didn't add it given that reading user environments with pam_env is [deprecated][1],  and from what I can gather, is already disabled on major distros. I guess we can add it if many users still rely on it, but it's likely going to stop working sooner or later.
>
> [1]: https://github.com/linux-pam/linux-pam/commit/ecd526743a27157c5210b0ce9867c43a2fa27784

_Originally posted by @midchildan in https://github.com/nix-community/home-manager/pull/1659#discussion_r550418172_

cc: @rycee

**Comment by rycee** [comment]
Interesting. Yeah, I guess that means that the pam setup in HM also is deprecated. It's a bit unfortunate since that's, as far as I know the only way to set environment variables early in the login process.

In any case, I'll have a look at marking the `pam.sessionVariables` option as deprecated. Thanks for the ping!
