### ISSUE TITLE
Files linked before zfs file system is mounted

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/home-manager#1710]
### Issue description

As the title describes, the files are being linked to several home directories before the zfs datasets are mounted; this only happens for certain users, however. Will setting the home directories of the failing users to be mounted before the successful users (in `config.fileSystems.<directory>.options`) work?

**Comment by cole-h** [comment]
FYI: your title and body are conflicting; "Files linked *after*..." vs "the files are being linked to several home directories *before*...". Could you please clarify which of these two it is?

**Comment by shadowrylander** [comment]
Oof; you're right; they're being linked before some fileSystems are mounted. I'll change what's applicable.

**Comment by berbiche** [comment]
If you are using HM as a NixOS module, you can add a dependency on the zfs path with systemd mounts to each service.

This seems like something that falls outside the scope of HM.
How should Home Manager handle this?

**Comment by shadowrylander** [comment]
Would it be possible for the module to check if zfs support is needed, based on the boot or filesystem options? Then it can potentially add the zfs path itself.

**Comment by berbiche** [comment]
Given a user named "foo", the NixOS module will create an activation script for "foo" if `home-manager.users.foo` is configured.

This activation script is actually a systemd service so you can configure the service to wait for the mount point to be available.

See this SO about systemd mounts; https://unix.stackexchange.com/q/246935

 You can add the dependency to the generated systemd service:
`systemd.services."home-manager-foo".after = [ "home-foo.mount" ]`
`systemd.services."home-manager-foo".requires = [ "home-foo.mount" ]`

I have not tested this configuration because I don't have a system to reproduce this at the time.

> Would it be possible for the module to check if zfs support is needed, based on the boot or filesystem options? Then it can potentially add the zfs path itself.

You are free to open a PR with this functionality.

**Comment by rycee** [comment]
The unit already contains `RequiresMountsFor = $HOME`:
https://github.com/nix-community/home-manager/blob/ae8cb242f2e450c525274732af58b3050399f5bd/nixos/default.nix#L135
which should be equivalent to adding `after` and `requires` on the necessary mount units.

This is not exactly correct in some cases, though, just matches the typical setup. I suspect that the correct solution would be to go through all `home.file` entries and add a `RequiresMountsFor` for each `fileSystems.<name>.mountPoint` that is a prefix of a `home.file` path.

**Comment by shadowrylander** [comment]
Both make sense; however, rather than as a NixOS module, I have begun using home-manager standalone, which should also solve the problem, if in a roundabout way. Should this issue therefore be closed, or kept open until a proper solution is implemented?
