### ISSUE TITLE
can't set EDITOR in X

### ISSUE THREAD

**Issue by krey** [nix-community/home-manager#183]
I have set my editor to `vim` using

```nix
home.sessionVariables.EDITOR = "vim";
```

Home Manager bakes this setting into `~/.nix-profile/etc/profile.d/hm-session-vars.sh`. This script is never run twice, because it's guarded by the variable `__HM_SESS_VARS_SOURCED`.

I added 
```sh
echo $__HM_SESS_VARS_SOURCED
```

to the top of my `.zshenv` and observed the following:

- In the ttys, it prints an empty line when I log in
- In X, it prints `1` when I open a terminal emulator

So the issue is, somewhere in the process of starting X, `~/.nix-profile/etc/profile.d/hm-session-vars.sh` is sourced and then it cannot be sourced again, and then `/etc/zshenv` sets my editor to `nano` :(

**Comment by rycee** [comment]
I'm not really familiar with zsh but looking around it seems `/etc/zshenv` and `.zshenv` are poor places to put session variables since they are sourced on each shell startup. I found [an example file](http://zsh.sourceforge.net/Contrib/startup/std/zshenv) which states

> It (the zshenv file) should NOT normally contain commands to set the command search path, or other common environment variables unless you really know what you're doing.

For example, if I run

```console
$ EDITOR=vim zsh -c 'echo $EDITOR'
```

I would expect it to print "vim" and not whatever is set in `/etc/zshenv`. @krey Does it print "nano" for you? As far as I can tell the `zprofile` files are sourced only for login shells so they would seem better suited for session variables.

In any case perhaps setting `programs.zsh.sessionVariables.EDITOR = "vim";` is a workaround for now?

@uvNikita Maybe you have some insights?

**Comment by krey** [comment]
It prints `vim`. This makes sense because neither of the two files that set `EDITOR`:
- `/etc/zshenv`
- `~/.nix-profile/etc/profile.d/hm-session-vars.sh` which is called from `.zshenv`
will run more than once, as they're guarded by variables `__ETC_ZSHENV_SOURCED`  and `__HM_SESS_VARS_SOURCED` respectively.

To start the X server, `.xprofile` is sourced, which calls `~/.nix-profile/etc/profile.d/hm-session-vars.sh`.
Now the `EDITOR` is set to `vim`.

Then I fire up `xterm` and `zsh` sources  `/etc/zshenv`. This loads the system-wide default settings, and sets the `EDITOR` to `nano`. Then `zsh` sources `.zshenv` which calls `~/.nix-profile/etc/profile.d/hm-session-vars.sh`, but it's already been called and won't run for a second time. `EDITOR` is still `nano`.

**Comment by rycee** [comment]
Ah, right. Because you are running the `EDITOR=vim zsh -c 'echo $EDITOR'` from inside zsh. I tried adding
```
programs.zsh.enable = true;
```
to my system configuration and then I get
```console
$ echo $SHELL
/run/current-system/sw/bin/bash
$ EDITOR=vim zsh -c 'echo $EDITOR'
nano
```
I think the problem is that `/etc/zshenv` contains the
```
. ${config.system.build.setEnvironment}
```
line when I think it actually belongs to `/etc/zprofile`.

**Comment by uvNikita** [comment]
@rycee I also found this [thread](https://www.zsh.org/mla/users/2003/msg00512.html) on the same issue, but I'm still not sure which place is better for session variables. I guess it depends on the variables. For instance, such ones as `ZDOTDIR` and `ZSH_CACHE_DIR` should probably stay in zshenv file, while others, user-defined ones, should go to `.zprofile`.

So one way to go could be that we will manage `.zshenv` through various module options (like zdotdir and cacheDir) and will put there only such "system" vars, but ones defined in `zsh.sessionVaribles` we will put into `.zprofile` since this option is mostly designed for interactive shell variables. This should also fix workaround for history options since `.zprofile` is sourced after `.zshrc`.

**Comment by rycee** [comment]
Hmm, yeah. This is a thorny issue. I'm suspecting that this code from `/etc/bashrc` is a key part of why everything seems to work in Bash:

```sh
# If the profile was not loaded in a parent process, source
# it.  But otherwise don't do it because we don't want to
# clobber overridden values of $PATH, etc.
if [ -z "$__ETC_PROFILE_DONE" ]; then
    . /etc/profile
fi
```

I can't find anything similar in the system zsh files.

For `ZDOTDIR` and `ZSH_CACHE_DIR` specifically maybe they are a bit like the `HISTSIZE` and  `HISTFILE` variables in that they are not necessary to be exported at all? If this is the case I guess they definitely should be in the `.zshenv` file and without an `export` keyword since they are not relevant to subprocesses.

**Comment by Infinisil** [comment]
I'm having the same issue, and it's really really weird, because `echo $EDITOR` prints `nano`, but when I go inspect the env vars for the zsh process directly (pressing e in htop) I get `vim`. Only child processes seem to show `nano` in htop.

**Comment by Infinisil** [comment]
I looked through everything zsh is sourcing, and there isn't a single line setting it to `nano`. However I found out that `/etc/profile` is sourcing a file that sets `nano`. It's not sourced by zsh, so I'm not sure, but that's probably the only place on my machine where `nano` is set.

**Comment by rycee** [comment]
@Infinisil Did you run the zsh inside an X terminal emulator? If so then I believe the zsh process would get the environment from the .xprofile script, which sources `~/.nix-profile/etc/profile.d/hm-session-vars.sh`, which I assume contains `export EDITOR=vim`. But subprocesses of your zsh will get the environment set by `/etc/zshenv`, which includes `export EDITOR=nano`.

I made a few comments about this in the https://github.com/NixOS/nixpkgs/issues/33219 issue. In particular https://github.com/NixOS/nixpkgs/issues/33219#issuecomment-359242913 and https://github.com/NixOS/nixpkgs/issues/33219#issuecomment-359243153.

I'm still curious about https://github.com/NixOS/nixpkgs/issues/33219#issuecomment-359932274, btw :-)

**Comment by gilescope** [comment]
Can we have a home-manager setting that says always run the script rather than it just being run once? Mostly I just want to set env variables in a shell agnostic manor. (I'm seeing the same fun and games from a fish perspective)

**Comment by Infinisil** [comment]
On a related note, I've been using this patch for nixpkgs in order to have `environment.variables` apply without having to relog (all new shells will have the updated value)

**Comment by pinpox** [comment]
Did you find a solution to this? It is still relevant, no matter what I try I can't set `$EDITOR` to something else than nano

**Comment by ghostbuster91** [comment]
fyi: In my case moving the `EDITOR` variable from `home.sessionVariables` to `zsh.sessionVariables` fixed the issue. (https://github.com/ghostbuster91/dot-files/commit/4aab173d7e3073c82e743853afa2a265bd87e82d)
