### ISSUE TITLE
Conditionally-defined modules are problematic

### ISSUE THREAD

**Issue by Shados** [nix-community/home-manager#1906]
## Problems
home-manager [*conditionally* defines a bunch of modules](https://github.com/nix-community/home-manager/blob/cc60c22c69e6967b732d02f072a9f1e30454e4f6/modules/modules.nix#L24-L214) dependent on whether the current platform is Linux or Darwin. This, unfortunately, makes maintaining a cross-platform set of default configurations extremely awkward.

For example, you can't simply gate platform-specific configuration behind a `mkIf` like so:
```nix
{ config, lib, pkgs, ... }:
{
  config = lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
    services.lorri.enable = true;
  };
}
```
Because attempting to do so will fail on Darwin with ``The option `services.lorri' does not exist``.

You also can't conditionally *import* things like so:
```nix
{ config, lib, pkgs, ... }:
{
  imports = lib.optionals pkgs.stdenv.hostPlatform.isLinux ./lorri.nix;
}
```
Because attempting to do so will trigger an infinite recursion (on either Linux or Darwin).

Additionally, this also results in the [online manual](https://nix-community.github.io/home-manager/options.html) showing all the Linux-only module options, but none of the Darwin-only ones.

From looking around at existing issues, it's clear to me that other people want to maintain personal cross-platform defaults, and that these same problems have cropped up previously<sup>[1](https://github.com/nix-community/home-manager/issues/8) [2](https://github.com/nix-community/home-manager/issues/895) [3](https://github.com/nix-community/home-manager/issues/1337)</sup>.

## Suggestions
1. Unconditionally define modules regardless of platform
2. Write platform-specific assertions to e.g. present a friendly error message if a Darwin user attempts to set `services.lorri.enable = true;`
3. Come up with a standard method of annotating modules with a list of the platform(s) they support, then display this information in the manual, and use it to implement the above assertions

**Comment by berbiche** [comment]
I personally worked around this limitation of the module system of nixpkgs by using `_module.args`/`extraSpecialArgs`/`specialArgs` to set parameters like `isDarwin` and `isLinux`, and have them available in module function heads `{ config, pkgs, lib, isLinux, isDarwin, ...}`.

**Comment by rycee** [comment]
Generally speaking I would suggest avoiding the use of conditionals to configure based on platform, hostname, username, etc. Instead I would suggest having one `home.nix` per deployment target and using imports to perform "additive" configuration. For example, for places I manage using the standalone installation I have my configurations in files named `$HOSTNAME.$USER.nix`, these I then symlink to `~/.config/nixpkgs/home.nix`.

A `home.nix` that is deployed on a darwin host can then be set up to only import modules that work with darwin. See [How to set up a configuration for multiple users/machines?](https://rycee.gitlab.io/home-manager/index.html#_how_to_set_up_a_configuration_for_multiple_users_machines) for a little more.

**Comment by Shados** [comment]
@rycee yes, I am aware that is currently one of the viable options for doing this kind of thing, but I think it needlessly complicates managing a cross-platform configuration by enforcing a file-level boundary between platforms. I'd much rather manage this in the same way as anything else, through the module system. It's also a little amusing to me that you "suggest avoiding the use of conditionals to configure based on platform", given that's effectively what HM is doing with its conditional imports :P.

And, clearly, this doesn't help with the platform-specificness of the HM docs, nor does it provide for nicer error messages.

@berbiche while that works, I'd say it's a fairly gnarly hack.

**Comment by ambroisie** [comment]
I'm going to chime in with my opinion and rationale for preferring assertions to conditional imports.

1. Working around the issue by using `_module.args` is indeed a hack, and I would rather avoid it.
1. Having to link files into place is stateful, even if it happens only once I would rather avoid it.
1. Having a "profile" per user/machine/OS and importing files to activate option is not a viable long-term strategy, it's actually the reason that the NixOS module system was created. "Import hell" is a term that exists for a reason, and it is just as unmanageable as activating options based on hostname/username/etc...
1. Using conditional imports breaks users who want to gate options behind `mkIf` and use the module system as it was intended
1. It hides options from the manual, meaning that users of an OS that is not the one being used to build it are left to figure it out on their own.
1. The error message is not as intuitive as a simple assertion would be: "this option does not exist" does not explain the reason why it does not exist, but an assertion saying "services.lorri is not compatible with your OS" is immediately obvious.

It is easy to write simple helpers that could be added to the extended library to write the assertion message:

```nix
config = lib.mkIf cfg.enable {
assertions = lib.hm.linuxOnly "my.option.name.enable";
};
```

This can then be further refined to, for example, defining maintainer options which dictate which platforms a module supports, automatically using that information to create the assertions  and document them in the manual.

If the issue with this is the man-power to migrate the current modules to use assertions instead, I volunteer to write the patches that will convert from conditional imports to assertions. If it is because of documentation issues, I say that we should not let perfect be the enemy of good. Otherwise, I do not see any downsides to migrating from our current approach to using assertions.

**Comment by berbiche** [comment]
I would also like to see this fixed.

The problem is that it's not as simple as adding an `mkIf isLinux` because we use `types.attrs` for certain crucial options (`home.sessionVariables`, etc.) and `mkIf` doesn't work with these (if you put an mkIf at the top, it gets "pushed down" to individual options).

If we can get around this problem then next would be the documentation.

**Comment by berbiche** [comment]
> 
> 
> @berbiche why do we use those types?

Because `types.attrs` is never evaluated and to use `mkIf` you need a type that is evaluated.

I wonder whether `types.lazyAttrsOf` could be used instead. They allow `mkIf` to work I think.

**Comment by ambroisie** [comment]
@berbiche I just did a quick experiment, replacing `types.attrs` by `lazyAttrsOf anything` (or similar when appropriate), every test keeps running (except for one neovim test that seems to be failing even without any changes...)

**Comment by rycee** [comment]
Sorry about the delay, I made a PR to remove the loading restriction. I'll look into fixing the documentation as well.
