### ISSUE TITLE
Consider adding probot/stale

### ISSUE THREAD

**Issue by sumnerevans** [nix-community/home-manager#1957]
### Issue description

Consider adding https://github.com/probot/stale to the repo.

The nixpkgs repo uses it with the following config: https://github.com/NixOS/nixpkgs/blob/master/.github/stale.yml

**Comment by berbiche** [comment]
I started contributing to the HM project nearly a year ago with the hope of reducing the number of open PRs but there is still many components of HM I am not intimate with.

Many open PRs are stale and waiting for an input from the author (they haven't been labelled and triaged accordingly).
I think probot would be good to check whether the author of the PR/issue is still active.
If the author is still active then a maintainer should try to review/merge the updated PR, otherwise we can close the PR and someone else will pick up the work.

As for the tool itself, I think the default `daysUntilStale` of 60 days is reasonable.

**Comment by sumnerevans** [comment]
I've been trying to contribute the last few weeks as well, but I find it pretty difficult to sort through all of the issues and PRs for ones that are still relevant.

One thing that I think would be helpful for PRs marked as stale is discouraging people from making a "this still matters to me" comment and instead encourage people to create a new PR.

**Comment by teto** [comment]
I dont mind if someone puts in the work.

**Comment by sumnerevans** [comment]
I would be willing to put in the work. I will prepare an MR, but somebody with more permissions will have to add the bot.
