### ISSUE TITLE
barrier: tray not shown.

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#2066]
Hey, for me the barrier tray is not shown despite being configured to `true`, and `--no-tray` is not present in `systemctl --user status barrierc.service`.

Does the option work for you?

I suspect the tray stuff only has an effect if `barrier` is invoked, but [the module](https://github.com/nix-community/home-manager/blob/ab64dc32493996c24607eab2cae6663466ddfb8a/modules/services/barrier.nix#L62) invokes `barrierc`.

_Originally posted by @nh2 in https://github.com/nix-community/home-manager/pull/1968#issuecomment-853010000_

**Comment by berbiche** [comment]
cc: @Kritnich

**Comment by Kritnich** [comment]
I can reproduce this. Unfortunately, as far as I am aware, `barrier` does not accept flags hence I went with `barrierc`. Maybe something specific must be done for it to recognize the system tray. I will investigate further.

**Comment by Kritnich** [comment]
I asked around and it seems that the tray icon was removed from the CLI-only wrappers a long time ago, which kind of makes sense because `barrierc` doesn't open a GUI application that you can interact with anyways. The `--no-tray` flag is a remnant of this.

A way to make the tray icon work would be to completely rewrite the module to use `barrier` directly with a generated config file. In my opinion, it would be best to just remove the `tray` option to avoid confusion and leave it as it is, because if you define your client using the module you wouldn't want to fiddle around with the GUI application anyways.

I am open for other suggestions though.

**Comment by berbiche** [comment]
> it would be best to just remove the tray option to avoid confusion and leave it as it is

Fine with me.

How likely will a user's barrier configuration change?
If it's a software that you don't need to constantly tweak, then I suppose an immutable configuration would be good.

You are free to choose the solution, though if you have the time to spare the second solution would be better.

**Comment by Kritnich** [comment]
I gave the latter solution a try but the configuration file for the GUI application is completely undocumented, so I am defaulting back to simply removing the `tray` option because I don't have any drive to reverse engineer this at the moment.
