### ISSUE TITLE
Xcursor module not follow XDG specification

### ISSUE THREAD

**Issue by SeraphyBR** [nix-community/home-manager#2081]
### Issue description

I believe this module should be creating the file in ".icons/default/index.theme", according to https://wiki.archlinux.org/title/Cursor_themes#XDG_specification, just like lxappearance does. 
Without this file my AwesomeWM will not use the cursor theme.

#### Maintainer CC

@rycee 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.11pre293730.1ca6b0a0cc3 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre293730.1ca6b0a0cc3, home-manager, nixpkgs-21.03pre249813.26d3fbf2156"`
 - channels(seraphybr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
CC: @league

**Comment by league** [comment]
Thanks for the report. I'm not currently using this module, since I switched to KDE Plasma a few months ago. However I see the notes on the ArchWiki page you linked. **Can you add something like the following to your config,** and see if it does the right thing? If so, it would be easy to add to this module…

```nix
    home.file.".icons/default/index.theme".text = ''
      [icon theme]
      Inherits=${config.xsession.pointerCursor.name}
    '';
```

I'm not sure whether `index.theme` is intended to have other settings that could be clobbered by this. There doesn't seem to be a facility in home-manager (yet) for updating that file from various settings, so we'd be replacing it wholesale – if that makes sense. Thanks.

**Comment by SeraphyBR** [comment]
Yes it works, I ended up doing it in my config as a temporary solution
![image](https://user-images.githubusercontent.com/33378179/121081384-0ca2c780-c7b3-11eb-8d7e-72cfa60e9c17.png)

**Comment by Narice** [comment]
this doesn't work for me and I don't know why :/
I am using the[ `Qogir Cursors`](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/data/icons/qogir-icon-theme/default.nix#L27) theme:
```
        pointerCursor = {
            package = pkgs.qogir-icon-theme; # FIXME: default cursor on i3 instead of qogir
            name = "Qogir Cursors";
        };
```
I am on i3 + plasma.
On all gui applications, the cursor works, but on i3 or alacritty, the cursor is the default one (theme-less).
my .Xresources has this inside (autogenerated from the xcursor module):
```
Xcursor.size: 32
Xcursor.theme: Qogir Cursors
```
`.icons/default/index.theme` is the only file I have in `.icons`
is the space in the theme name the cause of the problem and in this case, what can I do about it, or am I supposed to have a `Qogir Cursors` folder in my `.icons` directory?
@SeraphyBR what do you have in your .Xresources?

**Comment by Narice** [comment]
actually alacritty might not be affected, just i3 which seems to [take its cursor directly from the .Xresources](https://faq.i3wm.org/question/734/cursor-themes/index.html) file.

**Comment by Narice** [comment]
ok fixed it, the space was the culprit.
this is the thing that doesn't work because it is not quoted:
https://github.com/nix-community/home-manager/blob/666eee4f72979b0ebbd2e065a3846d7a8a16895c/modules/xcursor.nix#L61-L65
also, my icon directory is `Qogir` and not `Qogir Cursors`, `Qogir Cursors` is the theme name as stated in the [`theme.index`](https://github.com/vinceliuice/Qogir-icon-theme/blob/master/src/cursors/src/index.theme) file.
having the pointerCursor.name = "Qogir" resolves both problems.
It should probably be noted somewhere on the documentation.
Also, I do think that `${cfg.package}/share/icons/${cfg.name}/cursors/${cfg.defaultCursor}` up above should be quoted.

**Comment by SeraphyBR** [comment]
try to set the cursor theme using lxapperance, see if it identifies the theme, if it works on i3 and how was the file it generated, I'm not on the pc at the moment

**Comment by SeraphyBR** [comment]
and also as you are using plasma together, it may be influencing and the way to set the cursor may be different

**Comment by Narice** [comment]
with `pointerCursor.name = "Qogir"` instead of `pointerCursor.name = "Qogir Cursors"` it works perfectly fine now so it's all good :smile:
Thanks for the messages :wink:
