### ISSUE TITLE
Neovim: `programs.neovim.extraConfig` broken

### ISSUE THREAD

**Issue by workflow** [nix-community/home-manager#2100]
This breaks `programs.neovim.extraConfig`.

_Originally posted by @lugray in https://github.com/nix-community/home-manager/pull/2058#issuecomment-858976186_

**Comment by teto** [comment]
this is kinda useless as a bug report. Mind explaining what's going on + detailing nixpkgs/home-manager revision ? even better add a test in tests/modules/programs/neovim/default.nix so that we can reproduce avoid the issue in the future ?

**Comment by lugray** [comment]
I have extraConfig set to the contents I needed for my init.vim, which was the recommended path.  After #2058, which removes a line adding that, with other things, to customRC, it looks like extraConfig is unreferenced except in comments and docs.

**Comment by teto** [comment]
is your init.vim generated at all ? there is a test that checks if extraConfig is written and it passes (and it works here) so we have to narrow down the differences between your setup and HM testing.
The line that got removed, it's because extraConfig is passed here https://github.com/teto/home-manager/blob/8136aeb637934c787658d6f6c49c32f97831d658/modules/programs/neovim.nix#L229 so probably you are using a nixpkgs revision incompatible with that version of home-manager.

**Comment by lugray** [comment]
Ah, I see. Yes, my nixpkgs is more than 16 days old.

**Comment by workflow** [comment]
I'm using `neovim` from the current stable `21.05` channel.

At least the projects README states that `Home Manager targets NixOS unstable and NixOS version 21.05 (the current stable version)`
Oh, but I see there's also a `release-21.05` branch. Is that expected to match the 21.05 channel, and `home-manager` `master` maps to `nixpkgs-unstable`?
Perhaps we could document that, until flakes.

**Comment by teto** [comment]
I believe home-manager master is supposed to track nixos-unstable instead (that's the nixpkgs tests are run against) though I wish we used flakes to be able to upgrade in locksteps. So yeah you should switch to that other branch release-21.05.
