### ISSUE TITLE
meta: writing files to $HOME vs passing the nix store file directly to a command

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#2107]
### Issue description

What is Home Manager's stance on writing files to the user's HOME instead of using them directly in the command definition?

NixOS does the latter and avoids writing files (edit: in `/etc`, `/var/lib`, etc.) as much as possible I think.

Example: 
https://github.com/nix-community/home-manager/blob/b270fcef2fdbf9144c1f4b3528d35b455e116082/modules/services/window-managers/bspwm/default.nix#L51-L69

Related discussion:
https://github.com/nix-community/home-manager/pull/2095#issuecomment-858563522

#### Maintainer CC

@rycee @sumnerevans

**Comment by ncfavier** [comment]
FWIW, my personal stance is that putting files in predictable locations is fine when those files are used directly by the user and not just by applications. For example, `/etc/set-environment` in NixOS to reload the environment, or in this case `~/.config/bspwm/bspwmrc` (or `~/.config/bspwmrc`?) to reload the bspwm configuration.

But of course I second your question.

**Comment by sumnerevans** [comment]
My opinion is that if the application is designed to be launched by users independent of hm, we should place the config in the home directory. For example, for `git`, that should be put in the home directory since git will not look to the nix store for configs by default.

On the other hand, things like systemd services (where the users don't ever interact with it directly) should probably just reference the generated config in the nix store.

**Comment by TheOPtimal** [comment]
What if this option was configurable? What about `home.symlinkConfigsToHome` or something similar

**Comment by berbiche** [comment]
I think @sumnerevans' opinion is the right solution.
