### ISSUE TITLE
Inconsistent state after updating 20.03 to 21.05

### ISSUE THREAD

**Issue by Ralith** [nix-community/home-manager#2108]
After updating a 20.03 system to 21.05, using home-manager from nixpkgs on both, my environment seems to be corrupt. For example, the emacs service launches `/nix/store/7mshz7qnf2bqwj33g9d6g7frf3a3yawr-emacs-with-packages-27.2/bin/emacs`, but `.nix-profile/bin/emacs` addresses `/nix/store/ff2zqfkxb83zyfxllf555sngn7l4rkdz-emacs-with-packages-27.2/bin/emacs`. The former comes from `/nix/store/61cnr1m0p9730g9j2v13kz455gngljih-home-manager-path`, while the latter comes from `/nix/store/h09hsy8dygpngq7yzd5ff8ylahhfw6wr-home-manager-path`. The former seems to be at least partly composed of outdated emacs packages which don't load properly, while the latter seems to be current/correct.

**Comment by berbiche** [comment]
Hi @Ralith,

Are you using `services.emacs.enable`?
If not I presume the emacs systemd service leaked from the package and ended up in your `~/.config/systemd/user/`.

**Comment by Ralith** [comment]
I am using `emacs.enable = true;`, and `programs.emacs` for all my emacs configuration.

**Comment by Ralith** [comment]
For an additional, non-emacs-related, data point, `home-manager switch` prints `/nix/store/ppslyk8hkjgnywys8ripb6n9r4snf3n5-home-manager-generation`, but `home-manager generations` always displays
```
2021-06-11 17:38 : id 95 -> /nix/store/d7v63qrvyh4snnrpkgi8yl2bdlw8kfvz-home-manager-generation
```
even after adding/removing packages.

**Comment by berbiche** [comment]
Some users reported having a broken nix store and resolving the issue by uninstalling and reinstalling HM.

Can you try that?

**Comment by Ralith** [comment]
Removing home-manager from my configuration.nix `environment.systemPackages`, rebuilding, restoring it, and rebuilding again, had no apparent effect.

**Comment by berbiche** [comment]
Do you have Home Manager in `nix-channel --list` and `sudo nix-channel --list`?

**Comment by Ralith** [comment]
I have no user channels, and the only root channel is `nixos https://nixos.org/channels/nixos-21.05`.

**Comment by berbiche** [comment]
Last idea: can you try running `home-manager uninstall`?

cc: @rycee

**Comment by rycee** [comment]
Yeah, this seems quite curious.

@Ralith, could you paste the output of running `home-manager -v switch`? Hopefully something in it will hint why it's not actually moving to the new generation.

**Comment by Ralith** [comment]
```
> home-manager -v switch
trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
/nix/store/8ipfag66ajr3n1135sl2h3k3yjzixlqy-home-manager-generation
Starting home manager activation
Sanity checking Nix
Sanity checking oldGenNum and oldGenPath
This is a live run
Using Nix version: nix-env (Nix) 2.3.12
Activation variables:
  oldGenNum=95
  oldGenPath=/nix/store/d7v63qrvyh4snnrpkgi8yl2bdlw8kfvz-home-manager-generation
  newGenPath=/nix/store/8ipfag66ajr3n1135sl2h3k3yjzixlqy-home-manager-generation
  newGenNum=96
  newGenGcPath=/nix/var/nix/gcroots/per-user/ralith/current-home
  genProfilePath=/nix/var/nix/profiles/per-user/ralith/home-manager
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
error: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dconf.service not found.
```

**Comment by rycee** [comment]
@Ralith Interesting. Does it help if you add `home.packages = [ pkgs.dconf ]` to your HM configuration?

**Comment by Ralith** [comment]
No effect, even after multiple `switch`es. Same error, same old/new generation numbers, same old generation path (though the new one differs).

**Comment by rycee** [comment]
Humm, curious. You should now have a `~/.nix-profile/share/systemd/user/dconf.service` file, which should be visible to systemd. Ah, perhaps you need to run `systemctl --user daemon-reload` then `home-manager switch` again?

**Comment by Ralith** [comment]
That did the trick, thanks! I guess the weird inconsistent state was due to the activation not being fully transactional.

**Comment by efim** [comment]
Somehow I started getting this error
efim@efimnefedow-LT:~/dotfiles-nixos$ home-manager switch  --flake ~/dotfiles-nixos/.#work-laptop 
```

This is Ubuntu machine with home-manager

warning: Git tree '/home/efim/dotfiles-nixos' is dirty
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
error: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dconf.service not found.
```

research lead me here.

For me `systemctl --user daemon-reload` doesn't help

I do seem to have systemd service file for "dconf.service":
```
efim@efimnefedow-LT:~/.nix-profile/share/systemd/user$ ls
dconf.service  dunst.service  syncthing.service
```

but systemctl doesn't see this service:
```
efim@efimnefedow-LT:~/.nix-profile/share/systemd/user$ systemctl --user start dconf.service
Failed to start dconf.service: Unit dconf.service not found.
```

While both "dunst.service" and "syncthing.service" seems to be found fine

I've tried to fully uninstall home-manager, and installed it again.
There seem to be same error persisting.

I am not sure how systemd is configured, so that it doesn't see that "dconf.service"

My configuration in flake form is here: https://github.com/efim/dotfiles/blob/master/machines/work-laptop/home-for-flake.nix

I think new configuration gets loaded on system reboot, that's more than unfortunate, but not the end of the world.

If there's anything I can try to fix this, please let me know.
I'd greatly appreciate any help

**Comment by efim** [comment]
@rycee 
I do have `targets.genericLinux.enable = true;`, but I think config worked well without it and maybe (?) problem started after I tried to add it to config, so that App files from nix packages would get visible in Ubuntu

And while introspecting configuration all looks fine
```
nix-repl> outputs.homeConfigurations.work-laptop.config.xdg.systemDirs.data
[ "${NIX_STATE_DIR:-/nix/var/nix}/profiles/default/share" "/home/efim/.nix-profile/share" "/usr/share/ubuntu" "/usr/local/share" "/usr/share" "/var/lib/snapd/desktop" ]
nix-repl> outputs.homeConfigurations.work-laptop.config.targets.genericLinux.enable           
true
```

but in the terminal I see
```
efim@efimnefedow-LT:~$ echo $XDG_DATA_DIRS
/nix/store/hrz40cxyx68d22jk552wd2v58cnf3wdh-emacs-gcc-28.0.91/share:/nix/store/ydckdz6qc010fclx3hrksa62yjphrl19-gtk+3-3.24.30/share/gsettings-schemas/gtk+3-3.24.30:/nix/store/0rhbw783qcjxv3cqln1760i1lmz2yb67-gsettings-desktop-schemas-41.0/share/gsettings-schemas/gsettings-desktop-schemas-41.0:/nix/store/hrz40cxyx68d22jk552wd2v58cnf3wdh-emacs-gcc-28.0.91/share:/nix/store/ydckdz6qc010fclx3hrksa62yjphrl19-gtk+3-3.24.30/share/gsettings-schemas/gtk+3-3.24.30:/nix/store/0rhbw783qcjxv3cqln1760i1lmz2yb67-gsettings-desktop-schemas-41.0/share/gsettings-schemas/gsettings-desktop-schemas-41.0:/usr/local/share:/usr/share:/var/lib/snapd/desktop
```
i.e no `.nix-profile`

----- small step towards fixing things?
Previously in attempt to get app data I've mindlessly added
`export XDG_DATA_DIRS=\"$HOME/.nix-profile/share:$XDG_DATA_DIRS\"` to `bash.profileExtra`

I've removed that line, only kept `  targets.genericLinux.enable = true;`
attempted to switch and rebooted, now it's
```
echo $XDG_DATA_DIRS
/nix/store/m0c7z6llaqm4pczgqp64a05nszz3jj88-rofi-emoji-2.2.0/share:/nix/store/6pwg357yyh43aklmxnh2zlwi21dbwfv2-hicolor-icon-theme-0.17/share:/nix/store/dbdxq88vvpid22vmf67v2qm8jncqvbbw-rofi-1.7.2/share:/nix/store/ydckdz6qc010fclx3hrksa62yjphrl19-gtk+3-3.24.30/share/gsettings-schemas/gtk+3-3.24.30:"/home/efim/.nix-profile/share:"/home/efim/.nix-profile/share:/nix/var/nix/profiles/default/share:/home/efim/.nix-profile/share:/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/local/share:/usr/share:/var/lib/snapd/desktop""
```
for some reason with extra " everywhere

I'm not sure why

Tried to manually set that env var to cleaned-up value without "
and do "systemctl daemon-reload"

but "dconf.service" is still not being found, and "nome-manger switch" can't be done

Unfortunately I've tried to reinstall "home-manager" so I don't have my previoius generations, maybe switching to those could have helped
It seems that I've broken something, but at the very least if there's a sure way to do a clean reinstall - that would be more than enough of a solution

**Comment by efim** [comment]
I think I have unstable workaround for my situation

What helped is going through the following steps:
- adding `dconf.enable = false;` removing `profileExtra` line and ` targets.genericLinux.enable = true;` line
(without disabling dconf switch didn't work
- this allows me to apply changes to configuration
- but this disables icons, App files integration.
- adding ` targets.genericLinux.enable = true;` and switching
- rebooting

now I seem to have App files, icons and gnome theme from the config
`/home/efim/.nix-profile/share:` is in XDG_DATA_DIR 
and even though `systemctl --user status dconf` is still "not found"

But it seems that when I have `  targets.genericLinux.enable = true;`
i will get `error: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dconf.service not found.` on switch again
