### ISSUE TITLE
Separate flake outputs by system

### ISSUE THREAD

**Issue by tejing1** [nix-community/home-manager#2161]
The `home-manager` command's flake output search sequence under `homeConfigurations` should be `user@hostname`, `user:system`, `user`, rather than just `user@hostname`, `user`, as it is now.

Pros:
- allows a flake to expose a home-manager configuration in a form that's not host-specific, but is cross-architecture.
- backward compatible with existing flakes
- the character `:` is unlikely to be in a username, due to its use as a separator in `/etc/passwd` and many other places.

Cons:
- not particularly uniform with how this issue is handled in other flake outputs
- incompatible with `flake-utils.lib.eachSystem` and `flake-utils.lib.eachDefaultSystem`... home-manager should perhaps expose a library function to generate these easily.

Related to #1783 and #1856.

Comments?

**Comment by ambroisie** [comment]
Out of curiosity, how different are your configurations that you would need a different one for each `system`?

I would just have the same configuration and alias them using `user@hostname` instead, in that case.

**Comment by tejing1** [comment]
The idea is more that they're exactly the same, except for what system the binaries are built for. It should be possible to have a flake that exposes a home-manager configuration that can be installed on both an x86_64 PC and a raspberry pi, without having to have outputs specifically named by host.

**Comment by berbiche** [comment]
What you propose is a new lookup scheme to use when trying to find the "default" flake output configuration?

This scheme would save you a few characters that could be defined in a shell alias.

I don't see the point personally since you can name your configurations however you want i.e. `home-manager switch --flake .#aarch64`.

**Comment by berbiche** [comment]
What you propose is a new lookup scheme to use when trying to find the "default" flake output configuration?

This scheme would save you a few characters that could be defined in a shell alias.

I don't see the point personally since you can name your configurations however you want i.e. `home-manager switch --flake .#aarch64`.

**Comment by tejing1** [comment]
Of course, you can always do whatever you want with a bit of extra coding, but by that argument, why have a default at all?

I guess my issue here is that, in my view, the current default `flake#homeConfigurations.username` naming scheme doesn't quite achieve the apparent intention. It seems to be intended as the generic (that is, not tweaked for the particularities of of any specific host) version of that user's config, but it *isn't* actually fully generic, because it "bakes in" a choice of system. I would argue that a user environment for a given user doesn't really inherently have an associated system, except when it inherits it from a particular choice of host.

Maybe I'm the only one who sees a problem there, but that's why I'm suggesting this.

**Comment by Pacman99** [comment]
We've run into a similar problem while designing home-manager integration in [digga](https://github.com/divnix/digga). We want to create this concept of "portable users", which is a hm config for the same user that can be used on many devices. This requires those users to be "system spaced". I like the proposal for user:system, I don't think homeConfigurations should be system spaced by default since it doesn't make sense to do it for user@host, but only for portable users.

**Comment by blaggacao** [comment]
I happen to be exactly in the same boat coming to a very similar conclusion and was just short of raising this issue here upstream.

> `flake#homeConfigurations.username`  naming scheme doesn't quite achieve the apparent intention.

I fully share this analysis. It feels like an unfinished API.

I'd though propose to defult to:

```
homeConfigurations.aarch64.username
homeConfigurations.user@host
```

So this keeps compatible with how flake outputs are usually system-spaced.

**Comment by tejing1** [comment]
> I'd though propose to defult to:
> 
> ```
> homeConfigurations.aarch64.username
> homeConfigurations.user@host
> ```
> 
> So this keeps compatible with how flake outputs are usually system-spaced.

My only issue with this is that having the `user@host` configs at a different hierarchical level from the system-spaced ones feels... odd. It might be the right thing to do anyway though, since it fits in much better with the rest of the flake output schema.

**Comment by ant-arctica** [comment]
I'm also not the biggest fan of having configurations at different levels (I think elco said somewhere that this should be restricted to `legacyPackages`). The `@host` addressing scheme was chosen to prevent that. But I agree that `:arch` would make it annoying to integrate home-manager with other flake tools.
(`flake-utils.lib.eachDefaultSystem` wouldn't work with home-manager).
So, if we introduce:
```
homeConfigurations.aarch64.user
```
ons possibility would be to also introduce:
```
homeConfigurations.host.user
```
and deprecate:
```
homeConfiguartions.user(@host)
```
This approach has some drawbacks (`.` is a valid character in usernames, so interpreting things like: `flake#firstname.lastname` becomes complex), but it's worth considering.

**Comment by blaggacao** [comment]
I'm down for this proposal.

I beleive `flake#host."firstname.lastname"` would work.

**Comment by ambroisie** [comment]
Regarding dots in usernames, I believe that the usual solution is to instruct the user to quote the arguments correctly, i.e: `-- flake 'flake#"first.lastname"'`

**Comment by tejing1** [comment]
> ```
> homeConfigurations.aarch64.user
> homeConfigurations.host.user
> ```

Completely mixing the system and host namespaces like this doesn't seem like the best move to me, though something as simple as
```
homeConfigurations.@host.user
```
would fix that while following the same concept.

Assuming we're willing to deprecate what's currently being done, another, probably better, option would be to use a separate top-level attribute for the by-host and the by-system configs.
This has the additional advantage that when defining both types in a single flake, no deep update is required to combine the `eachDefaultSystem` portion with the rest of the outputs.

**Comment by blaggacao** [comment]
> This has the additional advantage that when defining both types in a single flake, no deep update is required to combine the eachDefaultSystem portion with the rest of the outputs.

Since there _cannot_ be any top level name clash, a deep update is not strictly  required when taking the shape of the attribute sets into account.

I think to settle this in the most standard compliant way, we could do:

```
homeConfigurations.aarch64.user
homeConfigurations.aarch64.user@host
```
Remember, that also host specific users are effectively arch-spaced.

Iiuc a host specific user can be more /different than a portable user, since they can additionally consume host config values.

**Comment by tejing1** [comment]
> Since there _cannot_ be any top level name clash, a deep update is not strictly required when taking the shape of the attribute sets into account.

I don't quite follow. It seems to me that as long as you have host-specific configs (which cannot be put inside `eachDefaultSystem`) and per-system configs (which should be put inside `eachDefaultSystem`) both under `homeConfigurations`, then the simple
```nix
{
homeConfigurations.host.user = foo;
} // eachDefaultSystem (system: {
homeConfigurations.user = bar system;
})
```
structure for the outputs cannot work.

> Remember, that also host specific users are implicitly arch-spaced.

They are, but we *don't* want to be putting them inside `eachDefaultSystem` since only 1 arch makes sense.

**Comment by blaggacao** [comment]
Agreed, can this be our emerging consensus?

```
homeConfigurations.aarch64."firstname.lastname"
homeConfigurations."@host.example.com"."firstname.lastname"
homeConfigurations.x86_64-linux."firstname.lastname"
```

**Comment by tejing1** [comment]
> Agreed, can this be our emerging consensus?

It still doesn't solve the deep update problem.
```
homeConfigurationsBySystem.aarch64."firstname.lastname"
homeConfigurationsByHost."host.example.com"."firstname.lastname"
homeConfigurationsBySystem.x86_64-linux."firstname.lastname"
```
would do so, though I'm terrible at naming things, so feel free to suggest nicer attribute names.

**Comment by blaggacao** [comment]
What about?
```
homeConfigurations."host.example.com"."firstname.lastname"
portableHomeConfigurations.aarch64."firstname.lastname"
portableHomeConfigurations.x86_64-linux."firstname.lastname"
```

**Comment by ambroisie** [comment]
I fail to see how deep updates are an issue, the first version by @blaggacao seems like the cleanest to me.

**Comment by tejing1** [comment]
> I fail to see how deep updates are an issue, the first version by @blaggacao seems like the cleanest to me.

It's this:
```
{
  homeConfigurationsByHost.hostname.username = foo;
} // flake-utils.lib.eachDefaultSystem (system: {
  homeConfigurationsBySystem.username = bar system;
})
```
vs this:
```
nixpkgs.lib.recursiveUpdate {
  homeConfigurationsByHost.hostname.username = foo;
} (flake-utils.lib.eachDefaultSystem (system: {
  homeConfigurationsBySystem.username = bar system;
}))
```

... and now that I look at it, it really isn't that bad. You'll always have nixpkgs available in any flake that defines home-manager configurations anyway.

**Comment by blaggacao** [comment]
Nice, so it looks like we can have consensus on the following format ?

```
homeConfigurations.aarch64.user
homeConfigurations.user@host
homeConfigurations.x86_64-linux.user

homeConfigurations.aarch64."firstname.lastname"
homeConfigurations."firstname.lastname@host.example.com"
homeConfigurations.x86_64-linux."firstname.lastname"
```

**Comment by tejing1** [comment]
I'm still not a fan of the irregular hierarchy levels, but I can't claim that's anything but an aesthetic preference.

**Comment by blaggacao** [comment]
> I'm still not a fan of the irregular hierarchy levels, but I can't claim that's anything but an aesthetic preference.

At least it keeps the door wide open to transition to `portableHomeConfigurations`, should we and up deciding so :smile:

**Comment by blaggacao** [comment]
I just discovered a "hard" issue with mixing name spaces:

Implementing checks (system-spaced) with something like `lib.mapAttrs (n: v: v.activationPackage) self.homeConfigurations` is not possible any more. If `self.homeConfigurations` is (partially) set within the system loop, this even will result in infinite recursions, since the checks have to be set within the systems loop (except using two independent system loops which are then emrged, but this might get a bit out of hand, then).

To avoid that infinite recursion problem we can use `homeConfigurations` & `portableHomeConfigurations`.

**Comment by Pacman99** [comment]
If we want to system-space portable home manager configs perhaps those should just be exported as their activation packages. So `homeConfigurations` is on par with `nixosConfigurations` in that it just exports one config meant for a user on a host. And something like `hmActivationPackages` or `packages.hmUsername` can carry the idea of a portable hm activation. Since for portable configs we really only care about the activation package - their just packages!. This way theres a clear separation between portable and regular configs and we follow the standard flake spec.

**Comment by blaggacao** [comment]
> And something like hmActivationPackages or packages.hmUsername can carry the idea of a portable hm activation. 

After some more research and fixing, I unhid https://github.com/nix-community/home-manager/issues/2161#issuecomment-880100345 which proposes intent-based `homeConfigrations` and `portableHomeConfigurations`.

I prefer to expose the config, though, and accessor the `activationPackage` contract the same way as in `homeConfigurations`, so that the logic and implementation can be otherwise analogue (modulo arch-spacing).

**Comment by blaggacao** [comment]
A naming scheme that also optimizes for sorting:
```
├───homeConfigurations: unknown
├───homeConfigurationsPortable: unknown
├───homeModules: unknown
```
