### ISSUE TITLE
bug: programs.taskwarrior.dataLocation = /absolute/path creates $HOME/absolute/path

### ISSUE THREAD

**Issue by bjornfor** [nix-community/home-manager#2207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

My taskwarrior configuration uses an absolute path for `programs.taskwarrior.dataLocation` (I point it to `/var/lib/syncthing/taskwarrior-data/.task`).

The result is a properly configured path in `taskrc`, but also the unfortunate side effect of creating `$HOME/absolute/path/.keep`, which is a symlink to the nix store. The path is wrongly placed in $HOME instead of /absolute/path (and I don't want the .keep symlink either).

`programs.taskwarrior.dataLocation` is mapped to `home.file`, so we should perhaps discuss how that API should handle abspaths.

Perhaps the simpler short-term solution is stopping `programs.taskwarrior.dataLocation` from _creating_ that path (taskwarrior will create it on first use, I hope).

### Maintainer CC

@rycee for `modules/files.nix` and @minijackson for `modules/programs/taskwarrior.nix`.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.122, NixOS, 20.09.git.359e654 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - nixpkgs: `/etc/current-nixpkgs`
```

**Comment by rycee** [comment]
I can't answer for taskwarrior, but I have for a long time wanted to relax the limitation of only supporting files in the home directory. At some point I'll get to it and then you should be able to have HM write to any absolute path (assuming your user has write privileges there). Until then I'm afraid that there is no way to do it through `home.file`, you'd have to create the directory manually through an activation script block.

About the presence of a `.keep` file, it is unlikely that these will disappear soon since `home.file` only knows how to handle symbolic links. So to create a directory from a HM configuration you must do it by creating a symlink within that directory.
