### ISSUE TITLE
Document the `htop` helper functions and options properly

### ISSUE THREAD

**Issue by NobbZ** [nix-community/home-manager#2279]
### Description

Some time ago the `htop` module changed from a set of well defined options to a single option that has to be used through some helper functions to create the nested set of options.

Neither the functions nor the structure of the set of options are properly documented.

Can this documentation please be provided?

**Comment by sumnerevans** [comment]
Are you referring to the change from https://github.com/nix-community/home-manager/pull/1844 by @bjpbakker?

**Comment by NobbZ** [comment]
Not sure if it is that.

I'm talking about whatever change removed `programs.htop.meters.{left,right}` in favor of some undocumented function calls and forced me into this commit:

https://github.com/NobbZ/nixos-config/commit/5ff0dc6

**Comment by bjpbakker** [comment]
That's a fair point and sorry for having this undocumented way of configuring. I hoped the given example would help, but it's not sufficient.

I'm planning to re-add the meters as options, but since they will be in a different format then what they were, they first had to be deprecated. In unstable they are now dropped since earlier this week, and I plan to move on with the module soon.

Meanwhile you could use the following in your configuration to get your right meters back.

```
settings = {
  detailed_cpu_time = true;
} // (with config.lib.htop; rightMeters [
      (bar "Battery")
      (text "Tasks")
      (text "LoadAverage")
      (text "Uptime")
]);
```

**Comment by NobbZ** [comment]
Even though the example has improved, I think documentation is still lacking.
