### ISSUE TITLE
M1 Macs using MacOS need a symbolic link pointing from home packages to ~/Applications/Nix/Apps/:

### ISSUE THREAD

**Issue by zeta-00** [nix-community/home-manager#2290]
Opening home-manager nix packages from the terminal is a hassle, being able to open an app directly from MacOS dock/launcher would be very convenient, or at least a folder like how it's implemented in the nix-darwin repo:
 
https://github.com/LnL7/nix-darwin/blob/a7492a8c76dcc702d0a65cd820a5f9baa8702684/modules/system/applications.nix#L29

Thanks in advance for the help!

**Comment by rycee** [comment]
I guess this would be fixed by enabling this code: https://github.com/nix-community/home-manager/blob/9029fd2b9de2147480efab55f351343f4fed73b9/modules/targets/darwin/linkapps.nix

But I suppose it is still blocked by nix-darwin?

**Comment by ggPeti** [comment]
This has been discussed in a few places already. Relevant links:
https://github.com/LnL7/nix-darwin/issues/139
https://github.com/LnL7/nix-darwin/issues/214
https://github.com/LnL7/nix-darwin/issues/337
https://github.com/nix-community/home-manager/issues/1341
https://discourse.nixos.org/t/mac-applications-installed-by-nix-are-not-loaded-by-spotlight/14129/2
and the mentioned nix-darwin pull request:
https://github.com/LnL7/nix-darwin/pull/226
But @rycee the config in your gist would not be enough. Turns out symlinks are not picked up by Spotlight, but osascript aliases are: https://github.com/nix-community/home-manager/issues/1341#issuecomment-761021848

**Comment by ggPeti** [comment]
In summary merging LnL7/nix-darwin#226 and incorporating something like https://github.com/nix-community/home-manager/issues/1341#issuecomment-761021848 would make mac applications installed via home-manager appear in Spotlight.
