### ISSUE TITLE
Rofi module longer works on unstable

### ISSUE THREAD

**Issue by Kranzes** [nix-community/home-manager#2317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

On nixpkgs-unstable, The `rofi` package was updated to version [1.7.0](https://github.com/davatorium/rofi/releases/tag/1.7.0) which has plenty of breaking changes that make a lot of the rofi home-manager module options not work, for example the deprecation of the options: lines, width and line-padding. It seems like the rofi home-manager module will need a rework for it to work well with the newest version of rofi.

### Maintainer CC

@thiagokokada

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `""`
 - channels(kranzes): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by thiagokokada** [comment]
I am thinking what would be the best way to solve this issue.

We could simply remove the deprecated options, this would be the easiest way to do (BTW, does someone has a list of all deprecated/removed options?). You can already use `extraConfig` with Rofi to set any arbitrary config to it (without validation) anyway, so I don't think we should add new options to this module (they mostly exist to avoid breaking changes, but now it seems inevitable).

Since we are already breaking changes, maybe we could simply migrate this to use [RFC42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) `rofi.settings` instead of what we currently have. However this module also has some peculiarities, and I don't know if they would fit RFC42 well.

Any opinions here @rycee @berbiche @sumnerevans ?

**Comment by thiagokokada** [comment]
BTW, my current config (https://github.com/thiagokokada/nix-configs/blob/master/home-manager/rofi.nix) seems to work well with Rofi 1.7.0 (needed to remove [those shortcuts](https://github.com/thiagokokada/nix-configs/blob/master/home-manager/rofi.nix#L63-L64) since something also seems to be binding to them and my theme is broken, but no warnings or anything).

So maybe just removing the deprecated options :thinking: ? @Kranzes, do you have a list of deprecated options?

**Comment by Kranzes** [comment]
I believe that using something like RFC42 would be pretty damn good if it works correctly.
