### ISSUE TITLE
LOCALE_ARCHIVE is unconfigurable and unconditional

### ISSUE THREAD

**Issue by arcnmx** [nix-community/home-manager#2333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

home-manager unconditionally inserts `pkgs.glibcLocales` into the closure without any mechanism for disabling, configuring, or trimming it down in the way that nixos does (see `i18n.supportedLocales` and related options). This adds something like 200MB to the closure size with no way to turn it off.

(to be fair there are workarounds like using package overlays or setting disabledModules but still, this should be an option!)

### System information

```markdown
host os: `Linux 5.14.2, NixOS, 21.11 (Porcupine)`
```

**Comment by berbiche** [comment]
Thanks for the report.

If you would like to submit a PR then you are welcome too!

**Comment by arcnmx** [comment]
I haven't had a chance to come up with a PR yet but it's still relevant you mean bot :<

**Comment by elohmeier** [comment]
This is my current workaround reg. this issue:

```
{ nixosConfig, ... }:
{
  # workaround https://github.com/nix-community/home-manager/issues/2333
  disabledModules = [ "config/i18n.nix" ];

  home.sessionVariables.LOCALE_ARCHIVE_2_27 = "${nixosConfig.i18n.glibcLocales}/lib/locale/locale-archive";
  systemd.user.sessionVariables.LOCALE_ARCHIVE_2_27 = "${nixosConfig.i18n.glibcLocales}/lib/locale/locale-archive";
};
```

This can be used when home-manager is used as a NixOS module and will use the trimmed down version from NixOS, effectively reducing the closure size for home-manager.

**Comment by AndrewKvalheim** [comment]
I use the NixOS option [`i18n.glibcLocales`](https://nixos.org/manual/nixos/stable/options.html#opt-i18n.glibcLocales) to configure my locale. `LOCALE_ARCHIVE` successfully reflects my configurtion, but Home Manager overshadows it with the higher priority `LOCALE_ARCHIVE_2_27` carrying an incorrect value.

Since this was added just to support [non-NixOS](https://github.com/nix-community/home-manager/pull/1650), can we disable it in NixOS?
