### ISSUE TITLE
bug: Nix 2.4 isn't unstable anymore - Readme needs to be updated

### ISSUE THREAD

**Issue by rmst** [nix-community/home-manager#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

>  Note that Nix 2.4 (nixUnstable) is not yet supported.

Nix 2.4 is the default installation now on https://nixos.org/download.html. It'd be nice to acknowledge that and to provide/link to instructions on how to install 2.3 instead

### System information

```markdown
this isn't relevant here
```

**Comment by flyfloh** [comment]
As a side-note: I was able to install home-manager with Nix 2.4 today by manually adding a `<nixpkgs>` channel.

**Comment by Eason0210** [comment]
I got this error when update nix-channel：
```
➜  ~ nix-channel --update                                                                                                                                   ~
querying info about '/nix/store/rsibrnyzzffd7kscw636plrpr23j093f-home-manager' on 'https://cache.nixos.org'...
downloading 'https://cache.nixos.org/rsibrnyzzffd7kscw636plrpr23j093f.narinfo'...
this derivation will be built:
  /nix/store/1md76zxhq04xp9fhn1y6nfy9if6ng56a-home-manager.drv
building '/nix/store/1md76zxhq04xp9fhn1y6nfy9if6ng56a-home-manager.drv'...
error: unsupported builtin function 'unpack-channel'
error: unsupported builtin function 'unpack-channel'
builder for '/nix/store/1md76zxhq04xp9fhn1y6nfy9if6ng56a-home-manager.drv' failed with exit code 1
error: build of '/nix/store/1md76zxhq04xp9fhn1y6nfy9if6ng56a-home-manager.drv' failed
error: program '/nix/store/c3mvzszvyzakvcp9spnjvsb8m2bpjk7m-nix-2.4/bin/nix-build' failed with exit code 100
➜  ~ nix-channel --list                                                                                                                                     ~
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

Nix 2.4 with nix-Darwin on Mac 12.0

**Comment by rycee** [comment]
The original cause for that note in the README was issue https://github.com/nix-community/home-manager/issues/1561. I also tried setting up a vm with nix 2.4 (actually 2.4pre20211006_53e4794) and was able to install OK and some light use didn't turn up any problems. So perhaps that issue no longer applies to 2.4?

**Comment by idmyn** [comment]
It seems to be an issue on macOS, at least: https://github.com/nix-community/home-manager/issues/1080#issuecomment-961585732

**Comment by rycee** [comment]
Yeah, I asked in the Nix Matrix channel but didn't get much response. As far as I can tell it is an issue in Nix, not HM.

**Comment by idmyn** [comment]
really weird but I just ran `nix-channel --update` from a fish shell that I'd installed with `nix-env -iA nixpkgs.fish` and it worked smoothly... 

I was previously running it from zsh (not totally sure what the state of my zsh environment was)

**Comment by Anderssorby** [comment]
Is there a way to use nix 2.4 with home-manager? I get this conflict with `nix profile` and `nix-env` and I had to revert. Is there a fork of home-manager which supports `nix profile`?

**Comment by knl** [comment]
I don't use channels, so home-manager is making sure that my environments have the same nixpkgs I use in home-manager. Today I updated to the latest nixpkgs to get nix-2.4 and did `home-manager switch`. Then I did `nix upgrade-nix`, to be greeted with:

```
error: packages '/nix/store/s1y6gzqrmhygmqwj1xrs9i3sl1md9w1v-home-manager-path/share/zsh/site-functions/_nix' and '/nix/store/c3mvzszvyzakvcp9spnjvsb8m2bpjk7m-nix-2.4/share/zsh/site-functions/_nix' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

I this this might be a similar issue that @Anderssorby is mentioning -- last night I was trying to get nix 2.4 and I also saw some errors about nix profile, but only after the aforementioned error.

**Comment by rycee** [comment]
@knl You probably have Nix installed in your profile though some other means, for example through `home.packages`. I don't know how `upgrade-nix` works but I imagine it is doing something equivalent to `nix-env -iA`, which could cause this conflict error.

**Comment by seqizz** [comment]
Switched to the new version on stable release with:
```
nix.package = pkgs.nixFlakes;
nix.extraOptions = ''
  experimental-features = nix-command flakes
'';
```
And had the error while upgrading:
```
Oops, nix-env failed to install your new Home Manager profile
```
Sorry if it's not totally relevant or I am missing something obvious. Also reverted.

**Comment by TheLonelyGhost** [comment]
While only a rug over the hole in the floor, I uninstalled home-manager, upgraded nix, then reinstalled home-manager (to the same conflict, but localized it to somewhere in `programs.zsh`, even with `enableCompletion = false`).

I hit the above error plus some error messaging indicating I should run `nix-env -q` to get more info:

```shell
➜ nix-env -q
home-manager-path
nix-2.4
```

Given this, it seemed I would want the zsh completions that come with the nix command itself, so I ran `nix-env --set-flag priority 3 nix-2.4`:

```shell
➜ nix-env --set-flag priority 3 nix-2.4
setting flag on 'nix-2.4'
building '/nix/store/6pdk8qbkwh1pqzc5zq4fn1dwnic2mapb-user-environment.drv'...
```

No more error after that! Upgraded nix command and it doesn't conflict with `home-manager switch`

**Comment by mtalexan** [comment]
The issue here has to do with a change released in Nix 2.4 that adds `nix profile`. It's intending to replace `nix-env` and the two commands are incompatible since they both set the `~/.nix-profile` symlink in different ways.  Whichever you first used, `nix-env` or `nix profile` sets the `~/.nix-profile` symlink and determines which one your system is issue.  You can't switch between them (maybe there's a way to migrate?).

Home Manager exclusively uses `nix-env`, though #2461 above is changing that.  So if you've installed anything with `nix profile` before installing Home Manager, it will fail with the error that `nix-env` is incompatible with `nix profile`. The only fix for it is to stop using `nix profile` and re-setup everything with `nix-env`.  The simplest way to do this is to delete your `~/.nix-profile` symlink and then manually re-install everything you had in your profile before.

**Comment by TheLonelyGhost** [comment]
I think there's a lot of confusion here. Yes the `nix-env` vs `nix profile` approaches are incompatible. The latest `nix` (or even default one for new installs) doesn't force you to use `nix profile`. Plus you don't need to install anything to start using flakes.

A deal with home manager is that it helps ease the transition away from ad-gif `nix-env` / `nix profile` commands to install or otherwise change things.

My previous comment seemed to gloss over an important detail: derivations for home-manager and nix command are fighting over who should own a file that gets symlinked somewhere under `~/.nix-profile`. Since they're equal priority (5) you need to choose one of the two derivations to win out and allow them to lay down their version of that file. Doing that sets the priority of a given derivation (nix command for me) higher than the other ones if there is another conflict.

The priority is global so any other conflict between nix command and another thing will have nix command win out (given default priority is 5), but I find that acceptable in this specific circumstance.

This also makes sense given this specific file is a helper to make using the nix command easier. I'd want closer to the officially supported one over an enthusiast's version of it, most often.

**Comment by mtalexan** [comment]
@TheLonelyGhost I think I follow your point, but I also think you're getting lost in irrelevant details a bit too. The nix commands themselves (`nix-env` `nix profile`) are indeed defined in the profile/environment itself as the minimum base set of packages. However, they generate incompatible output structure into the same profile folder. You can't just sitch between which is the higher priority one, you also would have to swap out the contents of the profile folder(s) they track their data in.

Home Manager absolutely should focus on supporting the currently available Nix features over the experimental ones. However, in the current Nix stable release (2.4) both `nix-env` and `nix profile` are available, and as mentioned above they both manage a user environment/profile in mutually exclusive ways. Prior to Nix 2.4, `nix-env` was certainly the way an assistive project like Home Manager could/should setup the user profile which is why it's currently done with that tool. With the release of Nix 2.4 this changed though. Nix now directs users to call `nix profile` rather than `nix-env` (documentation still being migrated), and it's a stated goal that the `nix-env` and similar commands will be deprecated in a future release. This is further exacerbated by the fact that there are also major in-demand features on the horizon that Home Manager *is* compatible with (flakes), and the deprecation of `nix-env` is (unnecessarily?) bundled with the instructions for how to setup to use that new feature in almost all documentation.

The base Issue from OP here is that they followed the stable Nix installation documentation, then tried to install Home Manager and it fails. This is currently only caused by an updated workflow instruction for Nix that uses a tool Home Manager is incompatible with, but the solution is non-trivial. The `nix-env` and `nix profile` aren't compatible, can't simply be swapped, and don't seem to have a simple migration method (uninstall nix to clear that you used `nix profile` first, then re-install and use `nix-env` first before re-running your configuration.nix or default.nix?).

**Comment by TheLonelyGhost** [comment]
@mtalexan I don't think it's in the weeds since I installed from scratch (single-user mode, WSL) both nixpkgs and home-manager. It works as long as you only use `nix-env` or home-manager for installing packages. I'm proof of that by having done a fresh install from a clean OS.

My previous comments were to get it to work at all, given the file conflict. The problem seems to be more than "does it work", as you stated. The happy path and default suggested method in the nix docs themselves suggest a path that would break things for home-manager. It suggests `nix profile` now, I gather, so it becomes more important for home-manager to support the upgrade given lack of backward compatibility.

It's not _if_ the status quo still works with a new version of the nix command, it's how well it works and how smooth the user experience for people newly coming to home-manager.

**Comment by zhujinxuan** [comment]
> I don't use channels, so home-manager is making sure that my environments have the same nixpkgs I use in home-manager. Today I updated to the latest nixpkgs to get nix-2.4 and did `home-manager switch`. Then I did `nix upgrade-nix`, to be greeted with:
> 
> ```
> error: packages '/nix/store/s1y6gzqrmhygmqwj1xrs9i3sl1md9w1v-home-manager-path/share/zsh/site-functions/_nix' and '/nix/store/c3mvzszvyzakvcp9spnjvsb8m2bpjk7m-nix-2.4/share/zsh/site-functions/_nix' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
> ```
> 
> I this this might be a similar issue that @Anderssorby is mentioning -- last night I was trying to get nix 2.4 and I also saw some errors about nix profile, but only after the aforementioned error.

Hi, for the priority problem.  You can solve it by:
```
    programs.zsh.enableCompletion = false;
```
to disable the nix-zsh-completion added by home-manager

**Comment by rycee** [comment]
Should be resolved with https://github.com/nix-community/home-manager/pull/3065.
