### ISSUE TITLE
Enable overwriting backup files and support multiple backups

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#2504]
### Description

I'd like two additional features from `home-manager` regarding [backup files]:
1. Force overwrite option - potentially dangerous
2. Multiple backups, incrementing the suffix index as needed

_Originally posted by @johnrichardrinehart in https://github.com/nix-community/home-manager/issues/2452#issuecomment-968927222_

<br>
Moving this here so I can close the other issue.

**Comment by teto** [comment]
isn't that a bit farfetched to support upstream ? what's your usecase ?

**Comment by johnrichardrinehart** [comment]
@teto It's described in detail in the referenced issue, but summarily, here, the use case is this: processes can overwrite files that are managed by `home-manager` such that a subsequent system build will fail to apply. If it's known that `home-manager` is expected to manage these files then overwriting them is the preferable solution. Currently what's done in this case is that the file is removed and `home-manager` is executed again.

This feature request is an implicit request to automate what is, now, a chronic, manual process.

**Comment by berbiche** [comment]
The first feature request is pretty simple to implement: add an option under `home.<some-option>` that will be the default value of `home.file.*.force`.

The second request would need to be done here https://github.com/nix-community/home-manager/blob/de54d513c74bf8f4f3a58954b80b5f690639fe72/modules/files.nix#L177-L181

Personally, I think implementing the first request could be practical to remove everything that was modified outside of Home Manager.
As for the second request, I don't see the benefit of creating multiple backups with incrementing numbers. How do you know which file is the most "recent" one between `$file.1` and `$file.2`?

**Comment by johnrichardrinehart** [comment]
> As for the second request, I don't see the benefit of creating multiple backups with incrementing numbers. How do you know which file is the most "recent" one between $file.1 and $file.2?

If the number is incrementing then the most recent would be the one with the greatest numerical value as the suffix, no?

Personally, I prefer 1. and have no "need" for 2. It arose as an alternative solution in the event that 1. would not be accepted. But, in terms of design: the current implementation of `-b` acts differently for the first execution (when it creates a new backup file) than it does for subsequent executions (when it fails because the backup file already exists). There is something dissatisfying about the inability of `-b` to "generalize" over the state of the system in this way. In my head, a "beautiful" solution would be able to generate a backup file regardless of the system state - the incrementing numerical extension was one idea that allowed for that (kind of like how browsers deal with the same filename being consecutively downloaded multiple times to the same folder).
