### ISSUE TITLE
bug: Hm hardcodes the Nix profile path 

### ISSUE THREAD

**Issue by thufschmitt** [nix-community/home-manager#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Home-manager hardcodes the path to the user’s Nix profiles ([here](https://github.com/nix-community/home-manager/blob/5f6364fc28065d6b26423512e14207ce0bffb27a/modules/lib-bash/activation-init.sh#L5)). However this path is essentially a Nix internal thing, and might change in a future release (https://github.com/NixOS/nix/pull/5226/), meaning that Nix won’t create the directory anymore, so new hm installations will be broken.

I think the right way™ to do this would be to make home-manager use its own profile directory (using `--profile /some/path`) so as not to depend on the Nix one

### Maintainer CC

cc @rycee 

### System information

```markdown
(Not really relevant, but since it’s required 😛)
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.16, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.5pre20211201_f3f32f0`
 - nixpkgs: `/nix/store/ibmzdbh1k4s2mvi79x3l37z7dhk320c8-94hsmqk3nrx26yd46crlw5aygiya6pj4-source`
```

**Comment by rycee** [comment]
Sure, we could do that, but does `--profile` introduce the path as a garbage collection root?

**Comment by regnat** [comment]
Yes of course. It’s using the same mechanism as the `result` symlink of `nix-build` to create a transparent gc-root that gets removed once the profile is removed

**Comment by ambroisie** [comment]
Not stale.

The change has landed in Nix, some users (e.g: me) might want to declutter their `$HOME`.

**Comment by rycee** [comment]
I think this is resolved now.

**Comment by SharzyL** [comment]
It seems that I am still impacted by ths issue.

After https://github.com/NixOS/nix/pull/5588, if enabling `use-xdg-base-directory` nix option and `~/.nix-profile` does not exist, the profile is created in `$XDG_STATE_DIR/nix/profile` instead of `~/.nix-profile`.

Currently hm hardcodes `home.profileDirectory` to `~/.nix-profile`. All configurations using `home.profileDirectory` will find them accessing a non-existing directory. Maybe hm should add an option to set profile directory?

**Comment by SharzyL** [comment]
Should I open a new issue or reopen this issue?

**Comment by flokli** [comment]
I'm also still affected by this issue - see https://github.com/NixOS/nix/issues/7930#issuecomment-1703788164.

This is using home-manager as a NixOS module, without enabling any `use-xdg-base-directory` options, on Nix 2.17.0.

**Comment by puffnfresh** [comment]
@flokli I hit this too but the problem was me: I was using a flake.nix with an old home-manager in the flake.lock. I had run `nix flake update home-manager` which didn't do what I thought it did, so it didn't update.

I couldn't be bothered figuring out the weird Nix UI to do what I wanted so I just ran `nix flake update` and everything is working great.

**Comment by flokli** [comment]
@puffnfresh these two weeks ago I tried with an up to date home-manager repo.
