### ISSUE TITLE
Pass argumnets from the flake to `home.nix` using `_module.args` instead of `extraSpecialArgs`?

### ISSUE THREAD

**Issue by ShamrockLee** [nix-community/home-manager#2717]
According to NixOS/Nixpkgs [`lib/modules.nix`](https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L92-L95)

> This (`specialArgs`) should only be used for special arguments that need to be evaluated when resolving module structure (like in `imports`). For everything else, there's` _module.args`. If `specialArgs.modulesPath` is defined it will be used as the base path for disabledModules.

Should change the way how variables are passed, either by instructing users to pass extra arguments through `_modules.args`, or by creating another parameter to do the job?

**Comment by ShamrockLee** [comment]
This is growing important as `extraArgs` got deprecated in favor of `config._module.args`.

**Comment by ncfavier** [comment]
Could you be more precise? As far as I can see we're not using the deprecated `extraArgs`, but we are using `specialArgs` [here](https://github.com/nix-community/home-manager/blob/87d30c164849a7471d99749aa4d2d28b81564f69/modules/default.nix#L34-L36). This doesn't seem to be a problem because, apart from `modulesPath`, the user is free to choose to pass extra arguments via `extraSpecialArgs` or via `configuration._module.args`.

**Comment by ShamrockLee** [comment]
#3023 shows a way to allow users to pass through arguments in the form of `configuration._module.args`.

**Comment by ShamrockLee** [comment]
See https://github.com/nix-community/home-manager/pull/3023#issuecomment-1155480440 .
