### ISSUE TITLE
ask: how to install specified version package

### ISSUE THREAD

**Issue by detailyang** [nix-community/home-manager#2796]
Hello guys.

I'm newbie to the home-manager and nix.  **Just want to know how to install the specified  package**. found the clang via `nix-env -qa clang` as the following:

```bash
clang-10.0.1
clang-10.0.1
clang-11.1.0
clang-11.1.0
clang-11.1.0
clang-12.0.1
clang-12.0.1
clang-13.0.0
clang-13.0.0
clang-14.0.0-rc1
clang-14.0.0-rc1
```

and install directly via nix-env with `nix-env -i clang-13.0.0`. But it cannot install via home-manager as the following:

```nix
{lib, pkgs, config, ...}:
{
	nixpkgs.config.allowUnfree = true;      

	home.packages = with pkgs; [
		clang-13.0.0
	];

	programs.home-manager = {
		enable = true;
	};
}
```

when running `home-manager switch`, it says:

```
❯ home-manager switch                                                                                                         
error: undefined variable 'llvm-13'

       at /Users/detailyang/.config/nixpkgs/home.nix:15:13:

           15|             clang-13.0.0
             |             ^
           16|             llvm-13.0.0
(use '--show-trace' to show detailed location information)

```

**Comment by berbiche** [comment]
Hi,

The packages listed by your nix-env command cannot be used as-is since they are not valid nix identifiers.

The clang 13 and llvm 13 packages are available under the name `clang_13` and `llvm_13`.
They are also available under `llvmPackages_13.clang` and `llvmPackages_13.llvm`.

I recommend using the following commands to search for packages:
- `nix-env -f '<nixpkgs>' -qaP <package>`
- `nix search nixpkgs <package>`
- <https://search.nixos.org/packages>

**Comment by detailyang** [comment]
@berbiche Thanks gotcha. 

Consider it resolved. 

>
there was a related issue [https://discourse.nixos.org/t/specifying-package-version-in-shell-nix/8513/2](https://discourse.nixos.org/t/specifying-package-version-in-shell-nix/8513/2)
