### ISSUE TITLE
bug: Stale bot closes valid issues

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The stale bot is closing issues that are valid, issues that are even still labeled as `triage` as nobody ever looked at them.

It also lies to users when it says closed issues can be reopened. Even the issue author can't reopen a closed issue, it requires someone with repo privileges to do this.

More generally, the stale bot only serves to disrespect users and discourage us from filing issues. Why should I take the time to write up an issue if it sits there without anyone triaging it for 3 months, and then is closed with no recourse for reopening it? It's a waste of my time.

The only purpose a stale bot serves is to artificially deflate the issue count and pretend like there are fewer issues. If you're just trying to focus on issues people care about, that can be done by labeling the issue as stale and _not closing it_. People can then filter out stale issues if they're looking for stuff to focus on. But "this issue hasn't had activity in X time" isn't an indicator of issue importance anyway, it's just an indicator as to whether the issue is under active discussion.

### System information

```markdown
N/A
```

**Comment by rycee** [comment]
I think that is fair enough. Unless there is strong opposition then I'd be happy to accept a PR that changes the behavior to not close stale issues.

**Comment by sumnerevans** [comment]
As the person who implemented stalebot in the first place, I'm fine with it just labeling as stale rather than closing. I think it's still valuable to have a message when marking as stale to remind the person who opened it to close it if the problem has been resolved.

For context on the original change, there were many issues that were super old, and had comments like "has this been resolved for you" and then no response for months. The bot was able to close most of those issues allowing more focus on actual problems that hadn't been solved. But its closing power seems unnecessary at this point now that the issue list is under control.

PR incoming...

**Comment by lilyball** [comment]
Thank you. Also I would like to apologize for the rather harsh tone of this issue. I was feeling rather cranky as I had just discovered that I was one day late to keeping one of my still-valid issues open, but that's not a reason to adopt such a tone.
