### ISSUE TITLE
Issue: Some apps don't find the cursor icons 

### ISSUE THREAD

**Issue by leiserfg** [nix-community/home-manager#2812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Some apps (at least Firefox) don't find the xcursors, I make it work by setting
`XCURSOR_PATH=$HOME/.nix-profile/share/icons` and I think that's in fact the solution, but I don't know where to put it in a PR as it (in theory) should work for wayland as well (not only x11).

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.25-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(leiserfg): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/leiserfg/.nix-defexpr/channels/nixpkgs`
```

**Comment by berbiche** [comment]
@polykernel is this something your PR #2891 could fix?

**Comment by polykernel** [comment]
@berbiche Yes, it can but I am unsure on where the variable should be set because there isn't a standard interface for graphic sessions in home-manager. I think it can be set in `home.sessionVariables` which may not be appropriate depending on the user's graphic session configurations, but as per https://github.com/nix-community/home-manager/issues/1011#issuecomment-850889575 this is the preferred way to manage variables for any login session. What do you think?

**Comment by berbiche** [comment]
> I think it can be set in `home.sessionVariables` which may not be appropriate depending on the user's graphic session configurations

That's the best solution we currently have.

**Comment by nim65s** [comment]
Hi,

I used `home.pointercursor` and correctly have `export XCURSOR_PATH="$XCURSOR_PATH${XCURSOR_PATH:+:}/home/gsaurel/.nix-profile/share/icons"` in my `.nix-profile/etc/profile.d/hm-session-vars.sh`, but eg. firefox & kitty still can't get the cursors on login.

My current workaround is to set `".icons".source = ~/.nix-profile/share/icons;` in `home.file`.

**Comment by polykernel** [comment]
Thanks for the report. I have added a symlink from `$HOME/.icons` to the home-manager profile icons directory and moved the index.theme file for the default theme in https://github.com/nix-community/home-manager/pull/4281.
