### ISSUE TITLE
himalaya: allow using `maildir` or `notmuch` backend instead of `IMAP`

### ISSUE THREAD

**Issue by ambroisie** [nix-community/home-manager#2888]
### Description

`himalaya` has landed support for [`maildir` and `notmuch`](https://github.com/soywod/himalaya/issues/295). One should be able to use either `imap`, `maildir`, or `notmuch` instead of the current behaviour which is to configure `imap`.

I'm not sure what the best way to do so would be. For example, should we simply default to using `maildir` if an account has `mbsync` enabled, etc... ? I don't know what other modules do for such a scenario.

**Comment by ambroisie** [comment]
Still relevant.

**Comment by soywod** [comment]
Does https://github.com/nix-community/home-manager/pull/3332 fix this issue? If not, then could you explain a bit more (I am not sure to fully understand what you meant @ambroisie).

**Comment by ambroisie** [comment]
@soywod no indeed it can be closed now, I just forgot about this issue at the time.

**Comment by jhvst** [comment]
`notmuch` is still broken: if `himalaya` is compiled with `notmuch` support, the option cannot be enabled since it's not part of the current home-manager enum. Could `notmuch` be added if both `mbsync` and `notmuch` are enabled for a given account? Not sure what would be the best way to see if `himalaya` is compiled with the support for `notmuch` -- it's currently not the default in nixpkgs.
