### ISSUE TITLE
Support a extraPackages for Helix

### ISSUE THREAD

**Issue by anthr76** [nix-community/home-manager#2923]
### Description

Similar to how neovim does and a few others. It can be useful for adding language servers.

**Comment by Philipp-M** [comment]
Yeah I also thought about something like this already, it's a little bit more effort though, since for neovim there is `pkgs.wrapNeovimUnstable` to wrap a custom PATH variables into the neovim package (via a shell script AFAIK).

But regarding language servers it's already possible to sandbox them directly with `programs.helix.languages`

e.g. like this:

https://github.com/Philipp-M/nixos-config/blob/2201d13cb061a88978fc6a6134f9cb1f39e2e60b/home/modules/cli/helix.nix#L95

**Comment by arnarg** [comment]
I naively do it like this: https://github.com/arnarg/config/blob/0309e47240ea652b01557289b0d43ee6d2654a2c/home/development/helix/default.nix#L6-L40

I'm not sure if there are any cons to my approach but it would be nice if this was implemented in home-manager of course.

**Comment by Nyabinary** [comment]
Currently, the wrapper overrides the stuff you install via a nix dev shell for example, is there any way to make it not do that? For example I want rust-analyzer-nightly to override rust-analyzer-stable when I'm in a divenv that requires nightly rust analyzer.
