### ISSUE TITLE
bug: Flake config cannot use unfree packages despite nixpkgs.config.allowUnfree = true

### ISSUE THREAD

**Issue by schuelermine** [nix-community/home-manager#2942]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

I have a flake config ([source](https://github.com/schuelermine/home-manager-configuration)) and as of nixpkgs c777cdf5c564015d5f63b09cc93bef4178b19b01 and home-manager 538343be863cb0b9e9f1471e6dc09e0e140c7b3d unfree packages refuse to evaluate despite a `nixpkgs.config.allowUnfree = true;` in my config.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220503.cbe587c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220428_4bb111c`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Try adding ``--impure``.

**Comment by schuelermine** [comment]
@Artturin NixOS/nixpkgs@a585b1c70900a1ecf0a782eb0f6f09d405e5e6e3 doesn’t work either.

**Comment by Pablo1107** [comment]
For someone encountering this same issue, a workaround is to add this your nixpkgs config:
`nixpkgs.config.allowUnfreePredicate = (pkg: true);`

This will allow any unfree package to be installed until this issue is resolved.

**Comment by Artturin** [comment]
please provide a reproducer

**Comment by cmm** [comment]
@Artturin this fails when you do `home-manager build --flake .#test`:
```
{
  inputs.home-manager = {
    url = "github:nix-community/home-manager";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, home-manager }: let
    system = "x86_64-linux";
    allowUnfree = { nixpkgs.config.allowUnfree = true; };
  in {
    nixosConfigurations.test = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = [
        {
          fileSystems."/" = { device = "/dev/disk/by-uuid/b906a306-ee7f-4603-b7b4-f20a46face83"; };
          boot.loader.systemd-boot.enable = true;
        }

        allowUnfree

        ({ pkgs, ... }: {
          environment.systemPackages = [ pkgs.unrar ];
        })
      ];
    };

    homeConfigurations.test = home-manager.lib.homeManagerConfiguration {
      inherit system;
      username = "test";
      homeDirectory = "/home/test";
      configuration.imports = [
        allowUnfree

        ({ pkgs, ... }: {
          home.packages = [ pkgs.unrar ];
        })
      ];
    };
  };
}
```

**Comment by schuelermine** [comment]
> please provide a reproducer flake

Example: `github:schuelermine/home-manager-configuration/39aa0d5726a3309c287961b19f7aae75319fff08`

**Comment by jtojnar** [comment]
If I am reading the code correctly:

1. home-manager will pass the `pkgs` argument given to `lib.homeManagerConfiguration` [straight](https://github.com/nix-community/home-manager/blob/5427f3d1f0ea4357cd4af0bffee7248d640c6ffc/flake.nix#L70) to `modules.nix`.
2. Then an inline module  `modules.nix` will [set the value as a default](https://github.com/nix-community/home-manager/blob/f9f4c8e1e77c7447db5f7edd6b8d343b4c864550/modules/modules.nix#L311) for `_module.args.pkgs` (the `pkgs` argument passed to modules).
3. Also `nixpkgs.nix` module will [set the same argument with a higher priority](https://github.com/nix-community/home-manager/blob/5427f3d1f0ea4357cd4af0bffee7248d640c6ffc/modules/misc/nixpkgs.nix#L131) (obviously, [`mkDefault`](https://github.com/NixOS/nixpkgs/blob/58770a334d23bd3ea17b640b250d506da2316644/lib/modules.nix#L895) has higher number=lower priority than [`mkOverride defaultPriority`](https://github.com/NixOS/nixpkgs/blob/58770a334d23bd3ea17b640b250d506da2316644/lib/modules.nix#L911))
  - The value will be a newly instantiated Nixpkgs based on the path of the original `pkgs` attribute. It needs to be re-instantiated so that the value of `nixpkgs.config` home-manager option can be passed to it.

It looks like this changed since https://github.com/schuelermine/home-manager-configuration/commit/39aa0d5726a3309c287961b19f7aae75319fff08 (the  `lib.homeManagerConfiguration` did not previously require `pkgs` argument). Is this still an issue, @schuelermine?

**Comment by schuelermine** [comment]
Yes, this is still an issue. In this state: https://github.com/schuelermine/home-manager-configuration/tree/9dd9765757f1870f55ed988e058199b9644dc331 my home-manager configuration does not work.

**Comment by jtojnar** [comment]
Hmm, you are right, I managed to reproduce it with Michael’s config from above, updated to the new format as well:

```nix
{
  inputs.home-manager = {
    url = "github:nix-community/home-manager";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, home-manager }: let
    system = "x86_64-linux";
    allowUnfree = { nixpkgs.config.allowUnfree = true; };
  in {
    nixosConfigurations.test = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = [
        {
          fileSystems."/" = { device = "/dev/disk/by-uuid/b906a306-ee7f-4603-b7b4-f20a46face83"; };
          boot.loader.systemd-boot.enable = true;
        }

        allowUnfree

        ({ pkgs, ... }: {
          environment.systemPackages = [ pkgs.unrar ];
        })
      ];
    };

    homeConfigurations.test = home-manager.lib.homeManagerConfiguration {
      pkgs = nixpkgs.legacyPackages.${system};
      modules = [
        {
          home = {
            username = "test";
            homeDirectory = "/home/test";
            stateVersion = "22.11";
          };
        }

        allowUnfree

        ({ pkgs, ... }: {
          home.packages = [ pkgs.unrar ];
        })
      ];
    };
  };
}
```

**Comment by Pablo1107** [comment]
I remove my `allowUnfreePredicate` and leave only the `allowUnfree` and tried installing `zoom-us` via my flake dotfiles and the issue seemed to be resolved, no error appeared.

**Comment by lunik1** [comment]
Same here, appears to be resolved.

**Comment by Pablo1107** [comment]
> I remove my `allowUnfreePredicate` and leave only the `allowUnfree` and tried installing `zoom-us` via my flake dotfiles and the issue seemed to be resolved, no error appeared.

Nevermind, I was testing on a macOS system. Now I just tried the same on a Linux system but the issues persists.

Anyone else can test?

**Comment by lunik1** [comment]
I removed it on my Linux system and had no issue

**Comment by ncfavier** [comment]
This should work:

```nix
homeConfigurations.test = home-manager.lib.homeManagerConfiguration {
  pkgs = import nixpkgs {
    inherit system;
    config.allowUnfree = true;
  };
  modules = [ ... ];
};
```

`homeManagerConfiguration` [uses](https://github.com/nix-community/home-manager/blob/176e455371a8371586e8a3ff0d56ee9f3ca2324e/flake.nix#L83) the provided `pkgs`'s `config` to build its own `pkgs`, so `nixpkgs.config` should not be used in that situation. The fact that `allowUnfreePredicate` works is an accident: the default `pkgs.config` does not include `allowUnfreePredicate` because it is not defined in the [nixpkgs config module](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/config.nix), so the value you specify via `nixpkgs.config` will not get overridden by `pkgs.config`.

Ideally we should allow `homeManagerConfiguration` to not take a `pkgs` argument, in which case nixpkgs configuration would be configured modularly with `nixpkgs.config`, just like `nixpkgs.lib.nixosSystem`.

Note that there's a similar-but-different issue with NixOS: https://github.com/NixOS/nixpkgs/issues/118115

**Comment by kamalmarhubi** [comment]
I don't believe this is resolved as of cc6745b35fefe48624ebf573382e1e0e4a6fe85e. Repro:

```
cd "$(mktemp -d)"
nix flake init --template github:nix-community/home-manager
curl -sSL -O 'https://gist.githubusercontent.com/kamalmarhubi/5f35b5227ece3644982105ac6eeadb29/raw/7b417610fa160d64df41d1cc3a8723d82e9a4a06/home.nix' > home.nix
nix build .#homeConfigurations.jdoe.activationPackage
```

<details><summary>Output</summary>

```
error: Package ‘1password-cli-2.18.0’ in /nix/store/ain1lgmwvhc90yhw1rki6c7xhb0jp2hj-source/pkgs/applications/misc/1password/default.nix:67 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "1password-cli"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```
</details>

```
$ nix flake metadata
Resolved URL:  path:/private/var/folders/6f/g2lg4n1x7pzcq9zck4hdgspc0000gn/T/tmp.M1bCBfhq
Locked URL:    path:/private/var/folders/6f/g2lg4n1x7pzcq9zck4hdgspc0000gn/T/tmp.M1bCBfhq?lastModified=1686181065&narHash=sha256-P8j3hVbmPOfUUhkwQKYgsS%2fVlnd2m4E8Ydf19LDhm5Y=
Description:   Home Manager configuration of Jane Doe
Path:          /nix/store/lw8ixb349nym7gzcwkl7f4qw5mfm9h4m-source
Last modified: 2023-06-07 19:37:45
Inputs:
├───home-manager: github:nix-community/home-manager/cc6745b35fefe48624ebf573382e1e0e4a6fe85e
│   └───nixpkgs follows input 'nixpkgs'
└───nixpkgs: github:nixos/nixpkgs/4729ffac6fd12e26e5a8de002781ffc49b0e94b7
```

**Comment by GetPsyched** [comment]
Thanks!

**Comment by atropos112** [comment]
I came to linux ecosystem (and later nixos specifically) wanting to move away from proprietary madness forcing me to look for ways to bypass unnecessary limitations. Just to see a stupid flag like this, making me jump hoops because some guy wanted people to use free software, I will use whatever software I want and forcing such stupid flag is just causing problems.

**Comment by sedlund** [comment]
hi @atropos112 - I am also new to nix as well, but also a 30+year unix professional.  home-manager is not forcing anything, the allowUnfree flag is upstream in nixpkgs.  there is/was(?) just a language peculiarity here that is causing a mishap that I resolved with a comment within this thread but am still monitoring for some reason.  Everyone is trying to do their best.  If you are still having a problem it may be best to convey that information for others to help.

**Comment by atropos112** [comment]
I am sorry for being unclear. My anger is not towards creators/maintainers of home-manager I am still finding out how this works but am repeatedly fascinated about what it is allowing me to do. My anger is towards whomever created this idiotic flag. It feels like a rug-pull, you set up your stuff, devote time to it and then choose to use software someone didn't give their blessing to so now you have to spend hours figuring out how to bypass their flag.

**Comment by GetPsyched** [comment]
> I am sorry for being unclear. My anger is not towards creators/maintainers of home-manager I am still finding out how this works but am repeatedly fascinated about what it is allowing me to do. My anger is towards whomever created this idiotic flag. It feels like a rug-pull, you set up your stuff, devote time to it and then choose to use software someone didn't give their blessing to so now you have to spend hours figuring out how to bypass their flag.

Huh? How is having the choice to use unfree software bad?

**Comment by eclairevoyant** [comment]
Github issues are not your personal blog, if you want to complain just to complain this is the wrong place for it.

**Comment by atropos112** [comment]
https://github.com/nix-community/home-manager/issues/2942#issuecomment-1826348273
Having such flag is not bad, having it set to false by default is bad, especially when it becomes problematic as to how to actually make it consistent across the configuration.

https://github.com/nix-community/home-manager/issues/2942#issuecomment-1826348422
you are correct, ill stop now sorry.

**Comment by sedlund** [comment]
To be more straightforward.   This is bug tracker, not a conversation forum.  I find that a lot of new people to software dev do not understand the distinction.  This is not for your feelings but for logical conversation to present issues, logs, output, and ideas on how to resolve issues, or make a product better.

**Comment by nhooey** [comment]
I created this StackOverflow question to help everyone figure this out for the various different scenarios of using Nix:

* [StackOverflow: How to allow "unfree" packages in Nix, for each situation?: {NixOS, Nix, Nix with Flakes, Nix with Flakes and Home Manager}](https://stackoverflow.com/questions/77585228/how-to-allow-unfree-packages-in-nix-for-each-situation-nixos-nix-nix-wit)

Since GitHub issue comments are structured more like a forum of endless posts sorted by time instead of a proper question & answer site.
