### ISSUE TITLE
programs.starship.enableNushellIntegration

### ISSUE THREAD

**Issue by genofire** [nix-community/home-manager#3058]
enable starship in nushell.

**Comment by MordragT** [comment]
Still important :)

**Comment by rycee** [comment]
Agreed.

**Comment by Occhioverde** [comment]
Sorry to post on an closed issue, but I felt like opening a new one would be kinda pointless.

I wanted to report that, as of today, setting `programs.starship.enableNushellIntegration = true;` generates an invalid configuration that throws the following error:

```
Error: nu::parser::unknown_flag (link)

  × The `term size` command doesn't have flag `-c`.
    ╭─[init.nu:10:1]
 10 │     # jobs are not supported
 11 │     let width = (term size -c | get columns | into string)
    ·                             ┬
    ·                             ╰── unknown flag
 12 │     ^/nix/store/n2inix3sv19ci7z81wz0hvk52prvqc1v-starship-1.11.0/bin/starship prompt $"--cmd-duration=($env.CMD_DURATION_MS)" $"--status=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
    ╰────
  help: use term size --help for a list of flags
```

This is a known issue in starship/starship#4507, and it will be fixed in the next release, but I wanted to ask whether is possible to replace `starship init nu | save ~/.cache/starship/init.nu` with `starship init nu | sed "s/size -c/size/" | save ~/.cache/starship/init.nu` in `env.nu` (as described in the first comment of the issue I just linked) to temporary fix this problem.
