### ISSUE TITLE
Allow different keepassx packages

### ISSUE THREAD

**Issue by turion** [nix-community/home-manager#306]
KeePassX is not very actively maintained, but the community fork KeePassXC (`pkgs.keepassxc`) is. This should either be the standard package choice, or the user should be able to choose. If you agree, I'll try and prepare a PR.

**Comment by rycee** [comment]
I would like to use keepassxc and have looked at it a few times but didn't see any straight-forward way to use it as a service because it missed the `-min` and `-lock` command line options that keepassx has. I haven't checked recently, maybe there is a way to use keepassxc now?

I any case, if you are willing to have a look at it I'd be grateful 🙂

**Comment by voidIess** [comment]
what does "minimized" mean? Will there be a tray icon or does it just mean, that there will be a minimized window? I think that would be something which could be addressed by a wrapper script? Also keepassxc allways starts locked. isnt that the idea of a password manager?

Id like to create a module for keepassxc, since im using it on a daily basis and had some issues with not having it integrated into my desktop env properly. :)

**Comment by turion** [comment]
I lost track of this, and I'll happily review your PR, @voidIess  :)

> what does "minimized" mean? Will there be a tray icon or does it just mean, that there will be a minimized window?

I think a tray icon. There is no command line option for that afaik, but if you want a tray icon you can configure that in the settings.
