### ISSUE TITLE
Somehow set session variables in unmanaged X sessions

### ISSUE THREAD

**Issue by rycee** [nix-community/home-manager#307]
If Home Manager is not managing the X session then there is a risk that session variables will not be set when the user logs in.

The solution is possibly to expand the installation instructions.

This is a continuation of #292.

**Comment by turion** [comment]
If you want to know my opinion:

I think that Home Manager should detect from the global config whether the X session is managed there and in that case supply its own `.xprofile`. The user can add additional config with a hook like `extraConfig`, or there could be the option for the user to supply their own file. But the default should be that Home Manager supplies it.

I personally wouldn't expand the installation instructions. I found them already intimidating enough to deter me from Home Manager for a few weeks.

**Comment by rycee** [comment]
By global config, do you mean the NixOS system configuration (the one typically found in `/etc/nixos/configuration.nix`)? If so we cannot readily use the global configuration in Home Manager since we also want to support non-NixOS distros (and even macOS for those so inclined). Indeed, as far as I know the behavior also differs between display managers on the same distro. And from what I can tell, some source `~/.profile` and then independently source `~/.xprofile` 🙂

So it's a bit tricky and I'm thinking that it would be best for my nerves to just dump that responsibility on the user (via the installation instructions) until some robust solution presents itself.

**Comment by turion** [comment]
Ah right, I've been NixOS-centric. But I think that wasn't relevant anyways, because no NixOS package (or other package on any system) would ever create or modify `~/.xprofile`, right? So what I said there was a bit beside the point, which simplifies the issue.

So nothing else except Home Manager and the user create or modify `~/.xprofile`, and the window manager reads it. If Home Manager manages the X session then everything runs fine. If Home Manager doesn't, it can still create an `~/.xprofile`, and I think it's a good idea because it's consistent with how `~/.profile` is handled. Different shells handle this file differently, I think. If a display manager sources `~/.profile` first and then `~/.xprofile`, that should be fine in general if all it does is just setting environment variables. We could even do something like this:

* Add something like this to `~/.profile`
```bash
PROFILE_DOTFILE_READ = 1
```
* Add something like this (up to bash errors) to `~/.xprofile`:
```bash
if ! $PROFILE_DOTFILE_READ
then . "$HOME/.profile"
fi
```

**Comment by turion** [comment]
There is already the code in place to create such an `~/.xprofile` file:

https://github.com/rycee/home-manager/blob/9f0fdc68a9b81fb71d9ee6502614c90eb81ef17d/modules/xsession.nix#L105

We could add an option `xprofile.enable` that creates this file with the default content even if `xsession.enable == false`, and add `xprofile.additionalConfig`. If that's a good approach, I'm happy to give it a try.

**Comment by turion** [comment]
Or even inserting the default content could be an additional option `xprofile.defaults`.

**Comment by KlausDevWalker** [comment]
> There is already the code in place to create such an `~/.xprofile` file:
> 
> https://github.com/rycee/home-manager/blob/9f0fdc68a9b81fb71d9ee6502614c90eb81ef17d/modules/xsession.nix#L105
> 
> We could add an option `xprofile.enable` that creates this file with the default content even if `xsession.enable == false`, and add `xprofile.additionalConfig`. If that's a good approach, I'm happy to give it a try.

Your reply save me from a urge of anger hahaha thanks to point that out. It's a shame home-manager still didn't implement options like the suggested above.

**Comment by turion** [comment]
@rycee maybe it's time to reevaluate my last two comments? I'm happy to contribute.
