### ISSUE TITLE
ability to install multiple python3 versions

### ISSUE THREAD

**Issue by NorthIsUp** [nix-community/home-manager#3114]
### Description
many tools rely on differing versions of python and python versions should be able to co-exist in an install. It would be cool to be able to install a version of python and specify to _not_ install the extra symlinks such as `python`, `python3`, or `idle`.

**Comment by rycee** [comment]
This is not really in the scope of Home Manager, typically your user environment should not contain any interpreter.

If you are packaging some software then make sure the package references the full Nix store path of the needed Python interpreter. On the other hand, if you are developing a Python application then use a `shell.nix` or `flake.nix` in the project to set up a custom environment.

**Comment by carlthome** [comment]
Understandable that this use case is considered out-of-scope, but it would have been nice to have a replacement for `pyenv` that's based on nix.

I'm working in a team that uses Python for ML R&D that is not 100% onboard the nix train yet. I lack political buy in to introduce a shell.nix or flake.nix to team repos (yet 
🤞) so would like to do it in incremental steps.

Unfortunately we'll always need older versions of Python since cloud training jobs are built around Docker Hub images for TensorFlow and PyTorch (that lag behind for years).

For code autocompletion in local development to work, I need old Python versions available for `pipenv sync`, however currently getting
```
error: builder for '/nix/store/8yw3fnjgh6k0syarg00nm3dv4rgl12yq-home-manager-path.drv' failed with exit code 255;
       last 1 log lines:
       > error: collision between `/nix/store/4h7n4af8z6bqjhisn5xf1h1bljan44yk-python3-3.9.15/bin/idle' and `/nix/store/w8cwx6nmx9whd8jbsjd4yqpv708ck9jp-python3-3.8.15/bin/idle'
       For full logs, run 'nix log /nix/store/8yw3fnjgh6k0syarg00nm3dv4rgl12yq-home-manager-path.drv'.
error: 1 dependencies of derivation '/nix/store/lbak5xmy9adgmwcg1spb5xfkacbz5nmb-home-manager-generation.drv' failed to build
```
when trying to include multiple Python versions in the same `home.packages` list.
