### ISSUE TITLE
bug: services.polybar.script clobbers PATH in service environment

### ISSUE THREAD

**Issue by zeorin** [nix-community/home-manager#3121]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The way that `services.polybar.script` sets the `PATH`:

```systemd
[Install]
WantedBy=tray.target

[Service]
Environment=PATH=/nix/store/rzl2jg26mia8vrbhbz9p7szsc79ivjv3-polybar-3.6.3/bin:/run/wrappers/bin
ExecStart=/nix/store/j2lq9s80rmacgdcvcn97nywggyz6fp5n-polybar-start/bin/polybar-start
Restart=on-failure
Type=forking

[Unit]
Description=Polybar status bar
PartOf=tray.target
X-Restart-Triggers=/nix/store/q8as5klzkdhp8lcrrw3jhc9lz09ml5ip-polybar.conf
```

clobbers the existing `PATH` you'd expect to be there. E.g. none of the `coreutils` are available, which are usually available in any Nix-created shell script. This is very counter-intuitive.

I was trying to set a [polybar launch script for multiple monitors](https://github.com/polybar/polybar/issues/763) like this:

```nix
{ pkgs, ... }:

{
	services.polybar.script = ''
		# Launch bar on each monitor
		for m in $(polybar --list-monitors | cut -d":" -f1); do
			MONITOR=$m polybar --reload top &
		done
	'';
}
```

which failed silently, but this works:

```nix
{ pkgs, ... }:

{
	services.polybar.script = ''
		# Launch bar on each monitor
		for m in $(polybar --list-monitors | ${pkgs.coreutils}/bin/cut -d":" -f1); do
			MONITOR=$m polybar --reload top &
		done
	'';
}
```

### Maintainer CC

@uvNikita 

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.05 (Quokka), 22.05.2051.174e938d593`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(zeorin): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,


Typically the PATH environment variable is __empty__ in a systemd service (besides having systemd binaries in the PATH).
If you use `systemctl --user show-environment`, you will see that the global environment for all services running in your session does not contain anything besides what is mentioned above.

I believe the behaviour you are describing is normal and is exactly as should be expected.
The fact the PATH is overriden is (afaik) only because there has been multiple issues raised by people that were not used to an empty PATH.

**Comment by zeorin** [comment]
> The fact the PATH is overriden is (afaik) only because there has been multiple issues raised by people that were not used to an empty PATH.
:joy: Mea culpa

**Comment by berbiche** [comment]
I forgot to say that you are not wrong either 😅!
Overriding the PATH also leads to surprising behavior when the PATH is set at the session level (`systemctl --user {import,set}-environment PATH`)

**Comment by zeorin** [comment]
Ah yes, that's true… I did notice that by default the `PATH` would be set to `${pkgs.systemd}/bin` if it weren't overwritten. Should this be re-opened?

**Comment by berbiche** [comment]
I believe we are unlikely to resolve the issue definitely given Home Manager has already done a compromise by setting a fixed `$PATH` (which could be reversed at a later time).
Therefore, the issue should remain close for the time being

**Comment by CarlosMendonca** [comment]
I'd advocate for not hard-coding the `$PATH` variable on polybar's systemd configuration as explained [here](https://github.com/nix-community/home-manager/issues/1616#issuecomment-1236428053). Ideally, `Service.Environment` should be left blank, so that systemd can carry-over whatever has been set on `systemd --user show-environment`. If the user is missing some path, they can added manually by overriding the service config.

**Comment by mochabear97** [comment]
Please commit this. It's a real headache.
