### ISSUE TITLE
`mkAliasOptionModule` descriptions are not shown in the manual

### ISSUE THREAD

**Issue by phpcitizen** [nix-community/home-manager#3543]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

xsession.pointerCursor options definitions needs to be corrected at https://rycee.gitlab.io/home-manager/options.html.

### System information

```markdown
Not important.
```

**Comment by ncfavier** [comment]
They're [aliases](https://github.com/nix-community/home-manager/blob/dd99675ee81fef051809bc87d67eb07f5ba022e8/modules/config/home-cursor.nix#L59-L79) to the new `home.pointerCursor` options.

The underlying issue here is that nmd does not support [Markdown descriptions](https://github.com/NixOS/nixpkgs/issues/175586), which are used by `mkAliasOptionModule` and friends.

**Comment by rycee** [comment]
In this case I think these options need `visible = false` to make them not show up in the manual at all.

**Comment by ncfavier** [comment]
Beware the difference between `mkRenamedOptionModule` and `mkAliasOptionModule`: the former have `visible = false` while the latter have a helpful description. Maybe we just want to use `mkRenamedOptionModule` everywhere?

**Comment by ncfavier** [comment]
Fixed by https://github.com/nix-community/home-manager/pull/3570
