### ISSUE TITLE
bug: neovim ignores `queries/{language}/injections.scm` files

### ISSUE THREAD

**Issue by sestrella** [nix-community/home-manager#3591]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The following tree-sitter query highlights embedded LUA configuration inside home-manager Nix configurations files:

```scm
(binding_set
  (binding
    (attrpath
      attr: (identifier) @_config (#eq? @_config "config"))
  
    (indented_string_expression
      (string_fragment) @lua))

  (binding
    (attrpath
      attr: (identifier) @_type (#eq? @_type "type"))

    (string_expression
      (string_fragment) @_value (#eq? @_value "lua"))))

```

Based on [tree-sitter](https://github.com/nvim-treesitter/nvim-treesitter#adding-queries) documentation, placing the query below at `~/.config/nvim/queries/nix/injections.nix` should be enough to get proper highlighting for embedded LUA scripts, in fact, it works with a Neovim version installed via Homebrew, but it doesn't work with the one installed via home-manager.

Passing the query directly to `set_query` LUA function works, but this overrides other existing queries:

> If you want to completely override a query, you can use :h set_query().

```lua
require("vim.treesitter.query").set_query("nix", "injections", [[
  (binding_set
    (binding
      (attrpath
        attr: (identifier) @_config (#eq? @_config "config"))
    
      (indented_string_expression
        (string_fragment) @lua))
  
    (binding
      (attrpath
        attr: (identifier) @_type (#eq? @_type "type"))
  
      (string_expression
        (string_fragment) @_value (#eq? @_value "lua"))))
]])
```

> Queries are what nvim-treesitter uses to extract information from the syntax tree; they are located in the queries/{language}/* runtime directories (see :h rtp)

After checking the output of `set runtimepath?` for my home-manager Neovim installation, `~/.config/nvim` is included.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(sestrella): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by stasjok** [comment]
There is a problem with **neovim** from nixpkgs (not home-manager, but nixpkgs in general): it *prepends* vim-pack-dir, but instead it should insert it *after* XDG_CONFIG_HOME. For this reason a user can't override a file in user config dir (when first file from `rtp` should be used).

Specifically for your problem here, AFAIK modern neovim uses only first query found. If you want to extend a query from the plugin, you should add `; extends` at the top of your query file. Then both queries should be used. If you want to override query file completely, then you have to place your home config directory first in `rtp`.

For additional information read: `:h treesitter-query`, `:h treesitter-query-modeline-extends`. Also try `:lua=vim.treesitter.get_query_files("nix", "injections")`. It should return both files if you are using `; extends` or only one first file if you don't.

> placing the query below at `~/.config/nvim/queries/nix/injections.nix` should be enough to get proper highlighting for embedded LUA scripts

It's probably a typo here, but file extension should be `.scm`.

**Comment by sestrella** [comment]
@stasjok thank you so much for the well-detailed explanation, I'm going to try adding the `extends` statement to the query.

> It's probably a typo here, but file extension should be .scm.

Good catch, however, I do have the file with the right extension on my local. I fixed the typo in the description.
