### ISSUE TITLE
bug: readline quoting breaks "keyname: function-name or macro" style

### ISSUE THREAD

**Issue by n8henrie** [nix-community/home-manager#3611]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html

The (IMO) much more readable alternative to the "keyseq" style as used in the example:
https://github.com/nix-community/home-manager/blob/275ab728912006eecb549338a50f24f294a7cfb7/modules/programs/readline.nix#L34

would be:  `{ Control-h = "backward-kill-word"; }`

Unfortunately the current implementation quotes `Control-h` and outputs `"Control-h"`, which doesn't work. Obviously one could still put it in `extraConfig`, but it would be nice if it didn't default to adding quotes that I didn't ask for.

I think it makes sense to expect users to explicitly escape quotes if they want them, since it seems equally valid and more readable to *not* have them in many cases.

https://github.com/nix-community/home-manager/blob/275ab728912006eecb549338a50f24f294a7cfb7/modules/programs/readline.nix#L24

It seems like the most straightforward backward-compatible way to go about this would be adding a new option (`keynames`? `unquotedBindings`?) happy to make a PR if it seems reasonable. 

### Maintainer CC

@vojta001 
@rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(n8henrie): `"darwin, nixpkgs-22.11"`
 - channels(root): `""`
 - nixpkgs: `/Users/n8henrie/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
A simple heuristic would be to consider that a key is a keyseq if it contains a backslash, and a keyname otherwise. I'm pretty confident that keynames can't contain backslashes, less confident about the other way around unfortunately. Does it make sense at all to define a keyseq without any modifiers?

If this can't be done I'd go with adding a new option `keynameBindings`.

**Comment by n8henrie** [comment]
Don't think that will always work. This is a valid `keyseq`:

```
"ab": "asdf"
```

**Comment by hpfr** [comment]
#3947 does not fully resolve this. From the [Readline manual](https://tiswww.case.edu/php/chet/readline/rluserman.html#Readline-Init-File-Syntax): 
> A number of symbolic character names are recognized while processing this key binding syntax: DEL, ESC, ESCAPE, LFD, NEWLINE, RET, RETURN, RUBOUT, SPACE, SPC, and TAB.

The implementation in #3947 treats these character names as key sequences. For example, `"TAB" = "menu-complete"` binds `menu-complete` to the literal sequence `T A B`.

Just adding those names to the list at https://github.com/nix-community/home-manager/blob/d9b88b43524db1591fb3d9410a21428198d75d49/modules/programs/readline.nix#L27-L30 would probably fix it. Otherwise, it might just be best to have separate attributes for key names and key sequences.

**Comment by n8henrie** [comment]
True! I made some of these points in the discussion in the PR, and read (and believe i linked to) the manual as well.
