### ISSUE TITLE
bug: programs.aerc.enable seems to always create binds.conf

### ISSUE THREAD

**Issue by BurNiinTRee** [nix-community/home-manager#3621]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The `aerc` module seems to unconditionally crate an almost empty file at `~/.config/aerc/binds.conf` even when no binds are set. This overwrites all the default bindings.

### Maintainer CC

@lukasngl

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.7-200.fc37.x86_64, Fedora Linux, 37.20230123.0 (Kinoite), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/var/home/user/.nixpkgs`
```
```

**Comment by lukasngl** [comment]
Hi, this is a known issue which would be fixed with #3150 merged.

**Comment by BurNiinTRee** [comment]
Ahh, ok, I only searched through the issues, but not the pull requests.
Should this then be closed or kept open until #3150 is merged?

**Comment by trev-dev** [comment]
This may  be stale but it's still unresolved. I am not sure what the rationale for using programs.aerc would be if it straight up breaks aerc.

I can't re-configure the defaults as there are top level bindings that have no nested category:

https://github.com/philips/aerc/blob/master/config/binds.conf

**Comment by lukasngl** [comment]
> I am not sure what the rationale for using programs.aerc would be if it straight up breaks aerc.

Well, the rational is configuring aerc using home-manager and getting account setup more or less for free.
Sadly due to weak defaults one has to reconfigure some binds from the example config.

> This may  be stale but it's still unresolved.

I personally don't know a great way to resolve it due to reasons laid out before.
I also do not personally care lot about this issue as I already invested the 5 minutes to copy the example binds and lived happily ever after.

In my opinion it would be great to make the setup quicker, so someone (maybe you?) could share the example configuration as a gist[1] and link it here or in the manual.

[1]: https://gist.github.com/

> I can't re-configure the defaults as there are top level bindings that have no nested category:

As (maybe not clearly enough) stated in the manual, you can put the unnested/top-level/global binds into the `global` section:

```nix
program.aerc = {
    extraBinds = {
        global = {
            "<c-h>" = ":prev-tab<Enter>";
            "<c-l>" = ":next-tab<Enter>";
            "<c-t>" = ":term<Enter>";
        };
    };
};
```

**Comment by trev-dev** [comment]
The global key is very helpful.  The binds aren't the only thing overwritten - the aerc.conf is also wiped out.

I would propose implementing the defaults as the defaults, if I felt confident in being able to write that myself.  I'm only starting to get good at the expression language
