### ISSUE TITLE
bug: error: fcitx4 is deprecated, please use fcitx5 instead.

### ISSUE THREAD

**Issue by DavHau** [nix-community/home-manager#3814]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

```command
$ NIX_PATH= nix-shell '<home-manager>' -A install -I nixpkgs=https://github.com/nixos/nixpkgs/tarball/nixos-22.11 -I home-manager=https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz
this derivation will be built:
  /nix/store/g72klry47wiwkj96lhbw8ql0b9sqrwnm-home-manager.drv
building '/nix/store/g72klry47wiwkj96lhbw8ql0b9sqrwnm-home-manager.drv'...
install: creating directory '/nix/store/zi4mx662chbgy5gpf0sfxmrxnz3z7dbs-home-manager'
install: creating directory '/nix/store/zi4mx662chbgy5gpf0sfxmrxnz3z7dbs-home-manager/bin'
'/nix/store/dlc5qzrvm301jlsibx37npswfns6b22c-home-manager' -> '/nix/store/zi4mx662chbgy5gpf0sfxmrxnz3z7dbs-home-manager/bin/home-manager'

Creating initial Home Manager generation...

error: fcitx4 is deprecated, please use fcitx5 instead.
(use '--show-trace' to show detailed location information)
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.19.0-35-generic, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(dave): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/store/v4alr5pcln6h03406f3s9hd89jkfl13y-source`
```

**Comment by ncfavier** [comment]
Not a bug, see https://github.com/NixOS/nixpkgs/pull/220776

**Comment by DavHau** [comment]
I'm a bit confused, because what I did above is following the instructions to install home-manager `22.11` which appears to be a stable release.

Is that failure something users should expect from a stable software?

**Comment by ncfavier** [comment]
Then you should use the `release-22.11` branch of home-manager.

**Comment by ELD** [comment]
> Then you should use the release-22.11 branch of home-manager.

@ncfavier The concern is that 3ace6a31dd859710e7b7666a9d456b611f9376dc hasn't been backported to the `release-22.11` branch, so the only way to receive the fix is to track `master`. This creates a bizarre mismatch between tracking `nixpkgs/nixos-22.11` and `home-manager/release-22.11` where you need `home-manager/master` to not have a broken evaluation.

**Comment by DavHau** [comment]
Am I not doing this in the above example?

**Comment by ncfavier** [comment]
fcitx 4 has only been removed on nixpkgs unstable, and the home-manager option to configure fcitx 4 has only been removed on home-manager unstable. I see no mismatch here.

> that's the branch that home-manager/release-22.11 tracks

Not sure what you're referring to. It's true that the [flake](https://github.com/nix-community/home-manager/blob/release-22.11/flake.nix#L4) tracks nixos-unstable even on the stable branch, but this is not supposed to determine the version of nixpkgs used for `pkgs`.

**Comment by ELD** [comment]
I see what was causing my issue. I'm using the experimental `bootspec` support in my NixOS configurations and that sets `nixpkgs-unstable` as the global package, thus _I_ was introducing the mismatch between `release-22.11` and `nixpkgs-unstable`.

**Comment by anund** [comment]
I'm running into this too. I'm using nixpkgs unstable and home-manager master. `home-manager build` fails with this message. I don't set `i18n.inputMethod` directly anywhere. Fixing the deprecation message ambiguity it turns out it's `fcitx-engines` that the build is catching on. I don't currently know why.

**Comment by ncfavier** [comment]
`--show-trace` to figure out where `fcitx-engines` is used.

**Comment by anund** [comment]
Looks like it's a bit of not quite getting the install correct and a bit of nixpkgs unstable needs a version bump of home-manager. https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/home-manager/default.nix#L8-L16 is currently pointed at a commit from 2022. 

Following the [nixos-module](https://nix-community.github.io/home-manager/index.html#sec-install-nixos-module) install route I find a still need to include home-manager in `environment.systemPackages` to actually see `home-manager` on my `PATH`. That's why the `fcitx-engines` was being pulled in.

Two questions come up now:
- What's the correct version of home-manager to bump `unstable` to using? The pattern appears to be someone picks _a_ commit which is not great.
- What's the correct install home-manager following the nixos-module way that allows invoking `home-manager news`to use the 'right' version of `home-manager-path`?

**Comment by rycee** [comment]
@anund Yeah, unfortunately the home-manager package in Nixpkgs is completely unmaintained, as far as I know, and it would probably be best to completely remove it to avoid confusion. The preferred way to install HM is through the documented methods. In principle it may be possible to maintain the package in Nixpkgs but it requires quite a bit of churn to keep up to date, so I don't think it is worth it. Especially with the general move towards Nix flakes.

And there is not really any way, at the moment, to have the home-manager tool installed while using the NixOS module version of Home Manager. If you want the tool then you should use the standalone installation method. At some point I would like to make the tool available but we would need to remove some functionality like building and switching configurations. We could probably keep the news functionality of the command but it would have to be reworked a bit.

**Comment by timokau** [comment]
I have created a PR to update the nixpkgs version for now: https://github.com/NixOS/nixpkgs/pull/224476

It's true that it is not updated frequently (mostly whenever it breaks). It's still my preferred installation method though, since it makes it easy to pin the entire system (nixos and home-manger) and update the components together. Flakes would be an alternative, but they are not stable yet.

If you prefer we can still remove it of course, I understand that it adds maintenance overhead for you and may confuse new users.

**Comment by zeratax** [comment]
I am getting this error on nixos-23.05 with home-manager 23.05

```md
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.419.3a70dd92993`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(jonaa): `"home-manager, release-23.05.tar.gz-23.05.tar.gz"`
 - channels(root): `"nixos-23.05, nixos-hardware, nixos-unstable, sops-nix"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

the unstable release works, but shouldnt 23.05 be the correct one for me? I only have the unstable channel for my video driver

**Comment by ncfavier** [comment]
Looks like you have two home-manager channels?

**Comment by rycee** [comment]
Indeed, the channel "release-23.05.tar.gz-23.05.tar.gz" looks quite suspicious. Perhaps something happened when you copy/pasted the `nix-channel --add command`? It should be

    nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz home-manager

**Comment by zeratax** [comment]
yeah something like that must have happened, now it works! thank you!
