### ISSUE TITLE
services.owncloud-client does not install owncloud-client nor tray icon

### ISSUE THREAD

**Issue by turion** [nix-community/home-manager#382]
Activating `services.owncloud-client.enable = true;` in my config doesn't put the owncloud client executable in the path, nor does it create a tray icon in plasma. It should do at least one of them.

**Comment by rycee** [comment]
Unfortunately I have no insight into owncloud. Perhaps @uvNikita has some idea if this could be achieved?

**Comment by turion** [comment]
I guess it makes sense that the executable is not in path, but the tray icon should definitely appear.

**Comment by uvNikita** [comment]
I haven't tried to use owncloud module with KDE  but I guess it should work. What do you see in `$ systemctl --user status owncloud-client.service` and `$ journalctl --user -u owncloud-client.service`?

**Comment by turion** [comment]
When I restart, owncloud comes up immediately after login, even before the tray is there. Maybe it just needs to be reordered so it starts after the tray has initialised?

**Comment by uvNikita** [comment]
Try to run `$ systemclt --user restart owncloud-client`. If it will appear, then you are right and it's probably something with the order, if not then we will have to troubleshoot why it's failing in the first place.

**Comment by turion** [comment]
Running that command immediately brings up the owncloud tray!

**Comment by turion** [comment]
It would also be good to run owncloud after PAM has unlocked the kwallet.

**Comment by uvNikita** [comment]
Yes  so it seems that the issue is with the order. I'm using i3 with polybar which are managed by home-manager, so the fix in my case was to configure owncloud service to run after the polybar service. But I'm not sure how to achieve the same with KDE since home-manager doesn't control when the tray will be started in this case. @ryccee, maybe you have some ideas how we could address this?

**Comment by turion** [comment]
https://github.com/rycee/home-manager/blob/701b4130bd38d4ada810994aa089f7e9f23998d2/modules/services/owncloud-client.nix#L17

Maybe `After = [ "graphical-session.target" ];`?

**Comment by rycee** [comment]
Yeah, I guess the first thing is to add the status bars to the `After` section of owncloud-client so that it is reliably working with, e.g., polybar.

For plasma, though, I guess the tray is started by plasma itself, which you have configured as the window manager? That makes it a bit tricky since we, for unfortunate reasons, cannot run the window manager as a systemd user service. But I wonder if it would be possible to "cheat" by creating a fake `plasma-tray.service` that is defined roughly like
```nix
systemd.user.services.plasma-tray = {
  Unit = {
    Description = "Fake plasma tray";
    After = [ "graphical-session-pre.target" ];
    PartOf = [ "graphical-session.target" ];
  };

  Service = {
    Type = "oneshot";
    RemainAfterExit = "yes";
    ExecStart = pkgs.writeScript "fake-plasma-tray" ''
      #!${pkgs.stdenv.shell}
      until ${pkgs.procps}/bin/pgrep -u $USER PLASMATRAYPROGRAMNAME ; do
        sleep 0.5
      done
      sleep 0.5
    '';
  };

  Install = {
    WantedBy = [ "graphical-session.target" ];
  };
};
```
where `PLASMATRAYPROGRAMNAME` is the name of the program that should be running if the plasma tray is available.

Then also add
```nix
systemd.user.services.owncloud-client.Unit.After = [ "graphical-session-pre.target" "plasma-tray.service" ];
```
to your configuration to make the owncloud-client service start after `plasma-tray.service` finishes.

Think of it as a experiment for science. If it seems to work then we could try making it look a bit nicer 🙂

**Comment by turion** [comment]
That sounds quite complicated :/

I just tried my idea, it doesn't seem to work, although I don't understand why. Apparently `systemd` doesn't wait until the tray has fully initialised.

Note also: https://github.com/owncloud/client/issues/6117

**Comment by turion** [comment]
That's what I don't understand. The window manager _is_ run as a systemd service, right? It doesn't matter whether home-manager starts it or not. We just need to make sure that owncloud-client starts long enough after that. Maybe if we have `After = [ "graphical-session.target" ];` and change the owncloud command to `sleep 10 && owncloud-client`? That's what some people do, I think.

**Comment by turion** [comment]
Are you saying that if I configure the window manager over home manager, this should work?

**Comment by turion** [comment]
Owncloud has long since been replaced by nextcloud which seems to work fine.
