### ISSUE TITLE
bug: `services.gpg-agent` not supported for Apple Silicon M1

### ISSUE THREAD

**Issue by shackra** [nix-community/home-manager#3864]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

trying to install home-manager on an Macbook Pro with Apple Silicone M1 chip:

```shell
% nix-shell '<home-manager>' -A install --show-trace
The file /Users/jorge/.config/home-manager/home.nix already exists, leaving it unchanged...

Creating initial Home Manager generation...

error:
       Failed assertions:
       - The module services.gpg-agent does not support your platform. It only supports

         - aarch64-linux
         - armv5tel-linux
         - armv6l-linux
         - armv7a-linux
         - armv7l-linux
         - i686-linux
         - m68k-linux
         - microblaze-linux
         - microblazeel-linux
         - mips64el-linux
         - mipsel-linux
         - powerpc64-linux
         - powerpc64le-linux
         - riscv32-linux
         - riscv64-linux
         - s390-linux
         - s390x-linux
         - x86_64-linux
(use '--show-trace' to show detailed location information)
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(jorge): `"darwin, home-manager, nixpkgs"`
 - nixpkgs: `/Users/jorge/.nix-defexpr/channels/nixpkgs`
```
```

**Comment by berbiche** [comment]
Hi,

It seems that your existing Home Manager configuration uses services that are only configured for Linux at the moment.

You can set `services.gpg-agent.enable = pkgs.hostPlatform.isLinux` in the meantime.

This is likely going to be an issue for other "services" that don't/won't support Darwin/Mac in your configuration.

**Comment by shackra** [comment]
> You can set `services.gpg-agent.enable = pkgs.hostPlatform.isLinux` in the meantime.
> 
> This is likely going to be an issue for other "services" that don't/won't support Darwin/Mac in your configuration.

yes, I just did that. Sharing configuration between GNU/Linux and macOS is not that hard tbh

**Comment by dogayuksel** [comment]
Looks like for the error message displayed, the assertion is made here:

https://github.com/nix-community/home-manager/blob/58eb968c21d309a6c2b020ea8d64e25c38ceebba/modules/services/gpg-agent.nix#L267

It safeguards against all darwins, that block might need some adjustments to make sure it works on darwin's too.

**Comment by aymanbagabas** [comment]
I managed to get this working with https://github.com/nix-community/home-manager/pull/5786, please let me know if you encounter any issues with these changes :)

**Comment by cmacrae** [comment]
@aymanbagabas thanks for the contribution! :) i switched to `master` to test out your changes and have experienced some odd behaviour. perhaps you could clarify some points 🙏 

1. since the macOS system LaunchAgent `com.openssh.ssh-agent` uses `SecureSocketWithKey` for exposing `SSH_AUTH_SOCK` - this is injected into the environment by launchd. being a system managed LaunchAgent, this boots early for the user and thus proliferates throughout every process managed by launchd (read: everyting). this socket and its resulting env var **even stick around when the service is disabled**. here's the expression home-manager uses to expose the `SSH_AUTH_SOCK` var to the user's environment:
```nix
home.sessionVariablesExtra = optionalString cfg.enableSshSupport ''
  if [[ -z "$SSH_AUTH_SOCK" ]]; then
    export SSH_AUTH_SOCK="$(${gpgPkg}/bin/gpgconf --list-dirs agent-ssh-socket)"
  fi
'';
```

since `-z "$SSH_AUTH_SOCK"` will always be false (because of the above described behaviour), this `export` is then never evaluated. i tested the following hack on my machine, which additionally pattern matches `com.apple.launchd` in the socket path, and it works:
```nix
home.sessionVariablesExtra = optionalString cfg.enableSshSupport ''
  if [[ -z "$SSH_AUTH_SOCK" ${optionalString pkgs.stdenv.isDarwin "|| \"$SSH_AUTH_SOCK\" == *com.apple.launchd*"} ]]; then
    export SSH_AUTH_SOCK="$(${gpgPkg}/bin/gpgconf --list-dirs agent-ssh-socket)"
  fi
'';
```

this essentially circumvents the use of the default system `SSH_AUTH_SOCKET`, but i'm not sure i'd count this as a solution.

2. i was excited to see the use of native launchd sockets in your PR, however, it's not clear to me how the resulting socket(s) are then used. a couple points here:
    i. despite the launchd service loading, the sockets don't appear to ever get created (simply inspecting the filesystem shows they're not at the specified paths).
    ii. how would the gpg-agent ever know to use these sockets? there's nothing in the configuration that instructs gpg-angent that these paths are where we want to load the sockets
    iii. how would these socket paths be exposed to the user, such that gpg operations use said sockets? perhaps, if gpg-agent is configured in the previous point, then the current approach of `gpgconf --list-dirs agent-ssh-socket` would work?

on my system, running `gpgconf --list-dirs agent-ssh-socket` just returns the canonical `/Users/<username>/.gnupg/S.gpg-agent.ssh` and `/Users/<username>/.gnupg/S.gpg-agent` for `agent-socket`

---
so, i'm just curious to hear how you have things working on your darwin system(s). it doesn't seem like all the pieces connect, to me. but perhaps i've got something configured wrong :)

it looks like gpg-agent [can be configured with custom socket locations](https://askubuntu.com/questions/777900/how-to-configure-gnupgs-s-gpg-agent-socket-location)... albeit with quite a strange method

**Comment by cmacrae** [comment]
in fact, things are perhaps a little worse than outlined in my above comment. the `--supervised` flag is deprecated and running the agent with it causes it to fail:
```
/nix/store/dk1r0xcgyp837dx9mar7yd5rdrcydmby-gnupg-2.4.5/bin/gpg-agent --supervised 

gpg-agent[1402]: WARNING: "--supervised" is a deprecated option
gpg-agent (GnuPG) 2.4.5 starting in supervised mode.
no LISTEN_PID environment variable found in --supervised mode (ignoring)
no LISTEN_FDS or LISTEN_FDNAMES environment variables found in --supervised mode (assuming 1 active descriptor)
Fatal: file descriptor 3 must be valid in --supervised mode if LISTEN_FDNAMES is not set
```

as indicated by the output, it looks like there are some required variables missing to support supervised mode. however, i'd say, since it's deprecated, we probably shouldn't be using it

**Comment by cmacrae** [comment]
i've started maintaining a branch of what i think should be fixes for the launchd service [here](https://github.com/cmacrae/home-manager/tree/fix/gpg-agent_launchd). curious to hear back about how the launchd sockets work, if they indeed do :) for the time being, these changes have got things working again for me

**Comment by aymanbagabas** [comment]
@cmacrae Great finds! I've opened https://github.com/nix-community/home-manager/pull/5901 to resolve those issues. Please review and let me know if you find any bugs or issues

You're right, gpg-agent was managing its own sockets instead of using launchd. On Darwin, we should always use the canonical socket paths. The `--supervised` option is deprecated. I'm surprised it works on NixOS :/
