### ISSUE TITLE
Drop CODEOWNERS?

### ISSUE THREAD

**Issue by ncfavier** [nix-community/home-manager#3979]
It only automatically requests reviews from people with write access to the repository, which is... not a lot of people. Other than that, it's mostly redundant with `meta.maintainers`.

There isn't a clear division of the repository among the people who do have write access, and people who want to be notified of *everything* should just watch the repository anyway.

Should we get rid of it? Or at least remove the lines with non-committers, and don't mention it in the docs?

**Comment by sumnerevans** [comment]
In addition to all of the things mentioned, it's annoying to maintain as well since it can easily cause merge conflicts. I think it has very limited utility and would be in favor of removing it.

GitHub shows all of the errors it has:

![image](https://github.com/nix-community/home-manager/assets/16734772/b9444a5f-92b8-455b-9e55-c21a7210c21a)

**Comment by rycee** [comment]
Yeah, I fine with either removing it altogether or just removing non-committers. Anybody willing to make a PR?

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3990
