### ISSUE TITLE
bug: Running switch with sudo puts symbolic links into `/root` eventhough `homeDirectory` is defined

### ISSUE THREAD

**Issue by zmrocze** [nix-community/home-manager#4019]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I was running `home-manager switch` as sudo, mistakenly

```sh
sudo home-manager switch --flake '.#'
```

and it turns out the command updates symlinked files defined with `home.file` at `/root`.
Eventhough my `home.nix` contains:

```nix
  home = {
    inherit username;
    homeDirectory = "/home/${username}";
  };
```

Is it expected? I definitely didn't.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 22.11 (Raccoon), 22.11.20230219.0cf4274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/hbg5gjcr6bzya30advl28k4ynafhclhn-source`
```

**Comment by rycee** [comment]
One of the first things the activation script does is to change directory to `$HOME`: https://github.com/nix-community/home-manager/blob/d1f04b0f365a34896a37d9015637796537ec88a3/modules/home-environment.nix#L700

I guess this could be changed to `${config.home.homeDirectory}` but then ownership and permissions will be messed up. I imagine the best would be to verify that `$USER` and `$HOME` match the values of `config.home.username` and `config.home.homeDirectory` and exit early with an error message if they don't.

**Comment by zmrocze** [comment]
if changing the script working directory is a bad idea, then simply such a check would be beneficial imo. Running switch command with sudo seems to be something many poeple may run into. And my first intuition was to check if I set correct options and it took my a while to find this one out.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
hello there, first time interacting with this project.
been using HM for a while now (on multiple systems).

I was in fact relying on the behaviour that was reported here and fixed by the linked PR, in order to not have to care what username I picked, the configuration would still apply.
only noticed now when upgrading state from `22.11` to `23.05`.

would you happen to have any ideas on how to get the `$USER` value now that the behaviour has changed? I noticed some escaping has been introduced, which means `home.username = "$USER"` does not work anymore (..."USER is set to <theactualusername> but we expect $USER"). I also tried `getEnv "USER"` but that in turn yields empty string (as if "$USER" was not set at all)... is there a way to read the variable and force the evaluation before it's passed to e.g. `home.username`?

**Comment by rycee** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf [Hmm](https://xkcd.com/1172/), I haven't thought of that use case and I think it is not really something we will ever officially support. That said, I've been thinking to add an explicit way to skip this check and then you could use that. When I open that PR I will reference this issue.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
This is awesome, thank you!
A workaround would be great.

Nice reference btw :)) sorry I'm *that* person... :see_no_evil:

**Comment by rycee** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf With the above change, if you define a `SKIP_SANITY_CHECKS` environment variable, then the home directory and username checks should be skipped.

For example, `SKIP_SANITY_CHECKS=1 home-manager switch`. Maybe we'll add a `--skip-sanity-checks` option to the switch command later but for now hopefully the variable is enough.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf With the above change, if you define a `SKIP_SANITY_CHECKS` environment variable, then the home directory and username checks should be skipped.
> 
> For example, `SKIP_SANITY_CHECKS=1 home-manager switch`. Maybe we'll add a `--skip-sanity-checks` option to the switch command later but for now hopefully the variable is enough.

That is awesome, thanks @rycee.
Env var would be great.
The only thing I'd perhaps suggest is to name it with a prefix, as in `HM_SKIP_SANITY_CHECKS`, so as to prevent possible clashes with other programs/signify what it's affecting.

**Comment by sykloid** [comment]
Apologies for resurrecting this thread, but I've been banging my head against this issue (specifically the one referred to by @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf) and I'm not sure how to get the workaround working.

More concretely:

1. I'm trying to run `home-manager` within a docker container, where I'm installing `nix` under single-user mode using the Determinate Systems installer.
2. The flake I'm using is as follows:

```
{
  description = "MWE for sudo errors";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { nixpkgs, home-manager, ... }:
    let
       homeConfig = { config, pkgs, ... }: {
    	  home.username = "sykloid";
      	  home.homeDirectory = "/home/sykloid";
      	  home.stateVersion = "24.05";
      	  imports = [ homeDefs ];
        };
       homeDefs = { pkgs, ... }: {
         home.file = { ".test".text = "test"; };
       };
    in {
      homeConfigurations.test = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.aarch64-linux;
        modules = [ homeConfig ];
      };
    };
}
```
3. The user `sykloid` and the corresponding directory `/home/sykloid` have been created. The user `sykloid` is in addition added to `sudoers` with no password.
4. I am setting `SKIP_SANITY_CHECKS=1` in `root`'s `.bash_profile`, if I don't set this, I do get the error message as above so I figure that the setting itself is working as expected.
5. If I run `sudo -i nix run home-manager/release-24.05 -- switch --flake /path/to/flake-dir#test`. The nix profile and file (`.test`) are created in `/root`, and not `/home/sykloid`. In fact it doesn't seem to matter what I give as `home.username` and `home.homeDirectory`, the links and profile are always created in `/root`.

Is this the expected behavior? Is there any way to get the `sudo`-based invocation to provision my user's home directory rather than `root`'s?
