### ISSUE TITLE
nixos-install doesn't work when home-manager is used as nixos module

### ISSUE THREAD

**Issue by balsoft** [nix-community/home-manager#417]
The title says it all. I am upgrading my machines to SSD and nixos-18.09, therefore I am using nixos-install. I also have home-manager as nixos module in [my configuration](https://github.com/balsoft/nixos-config). nixos-install fails with the following error:
```
[0.1/0.0 MiB DL] downloading 'https://github.com/rycee/home-manager/archive/master.tar.gz'nix: src/libexpr/primops.cc:56: void nix::EvalState::realiseContext(const PathSet&): Assertion `store->isStorePath(ctx)' failed.
/run/current-system/sw/bin/nixos-install: line 98:  1416 Aborted               nix build --out-link "$outLink" --store "$mountPoint" "${extraBuildFlags[@]}" --extra-substituters "$sub" -f '<nixpkgs/nixos>' system -I "nixos-config=$NIXOS_CONFIG"
```
It's pretty unfortunate, as I dreamed of completely automatic installation of my system straight from nixos iso. Is there any fix or workaround or am I missing something obvious?

**Comment by balsoft** [comment]
Actually, if I use builtins.fetchGit instead of builtins.fetchTarball, it works. Maybe we could change instructions on using home-manager as a module?

**Comment by rycee** [comment]
Apologies for taking so long! Yeah, this seems to be a known issue in Nix. I'm hoping to rework the manual before too long and will make sure to note this.

**Comment by balsoft** [comment]
No problem! Thanks for the reply.

**Comment by worldofpeace** [comment]
@rycee Any way we could fix this?

**Comment by fricklerhandwerk** [comment]
The issue in question is https://github.com/NixOS/nix/issues/2405. It will take a while before the fix is merged into any release, as it seems.

Until then a viable workaround is to use `builtins.fetchGit`. The disadvantage is that it is slightly slower and puts more load on GitHub. Or keep the `home-manager` repo as a git submodule, as @balsoft [does](https://github.com/balsoft/nixos-config/tree/master/imports/github/rycee), which is in some ways equivalent.
