### ISSUE TITLE
`pueue` service fails with default settings

### ISSUE THREAD

**Issue by spietras** [nix-community/home-manager#4295]
If we don't provide any value for settings, the configuration file for `pueued` is not generated:

https://github.com/nix-community/home-manager/blob/8c731978f0916b9a904d67a0e53744ceff47882c/modules/services/pueue.nix#L42-L43

But the configuration file is always passed in when invoking `pueued`:

https://github.com/nix-community/home-manager/blob/8c731978f0916b9a904d67a0e53744ceff47882c/modules/services/pueue.nix#L51-L54

This makes the service fail.

I think there are two ways to resolve this:
1. Don't pass the configuration file to `pueued` if no settings were provided (and therefore no file generated)
2. Always create the configuration file, even if it's empty (note here that an empty file is actually invalid, `pueued` expects to find at least `shared` key, so the minimal working file looks like this: `shared:`)

Both are pretty easy to achieve, but I'm not sure which is better.

**Comment by koalp** [comment]
I think that the best would be to generate an empty working config file by default (with the `shared` key so that pueue runs) so that `pueue` works immediatly after enabling it.

But it would also be nice to allow the user to manually write their own config file. 

The default could be `{ shared = {}; }` and the `null` config value could used to remove the generation of the config, thus allowing the user to write their own config.

Unfortunately, I haven’t seen this pattern used in other `home-manager` `settings` field.
What do you think ?

**Comment by rycee** [comment]
Made a temporary fix in #5075. Also created https://github.com/Nukesor/pueue/pull/505 for a proper fix.

**Comment by rycee** [comment]
This may be obsolete now with the release of Pueue 3.4.0 (and update in Nixpkgs https://github.com/NixOS/nixpkgs/pull/297908). If somebody wants they can check and submit a PR.
