### ISSUE TITLE
programs.neomutt: Configure imap accounts

### ISSUE THREAD

**Issue by arjan-s** [nix-community/home-manager#4376]
### Description
The `programs.neomutt` module currently configures the accounts as configured in `accounts.email.accounts.<name> `, with the exception of imap. It only configures local maildirs, while neomutt itself does have support for imap. So instead of having to run mbsync to sync my mailbox locally, I would like to request that imap can be enabled directly in the mutt module.

**Comment by Cybolic** [comment]
I have a [PR in progress](https://github.com/Cybolic/home-manager/tree/feature-4376). It works for my use so far, but I'd like to get a bit of feedback before I submit it.
Specifically, I've currently written it so `imap` takes priority over `maildir`, but as this changes the current expected behaviour, I'd love to get feedback on how to handle this.
Would something like `accounts.<name>.neomutt.imap.enable` be the preferred way or is there a different settled standard (I'm fairly new to Nix).
