### ISSUE TITLE
bug: xdg.configFile duplicating file contents

### ISSUE THREAD

**Issue by adammitha** [nix-community/home-manager#4437]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When I specify the contents of xdg.configFile.\<file-name\>.text, the resulting file's contents are duplicated.

Example:

The following setting placed inside home.nix
```
xdg.configFile."git/test".text = "test config file";
```

Produces the following file contents:
```
❯ cat ~/.config/git/test
test config file
test config file⏎ 
```

Additionally, when evaluating the file's contents via `nix repl`:
```
❯ nix repl -f '<nixpkgs>'
Welcome to Nix 2.17.0. Type :? for help.

Loading installable ''...
Added 19208 variables.
nix-repl> :lf .
warning: Git tree '/home/adam/src/nixos-configuration' is dirty
Added 12 variables.

nix-repl> outputs.nixosConfigurations.adams-nixos-desktop.config.home-manager.users.adam.xdg.configFile."git/test".text
"test config file\ntest config file"
```

Full NixOS configuration can be found here: https://github.com/adammitha/nixos-configuration

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.11 (Tapir), 23.11.20230908.db9208a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by testplayername** [comment]
I saw this problem recently when using `xdg.configFile` to define a XML file. The duplicated text appears to be caused by calling the definition twice, in this case `xdg.configFile."git/test".text = "test config file";`.

In [your repository](https://github.com/adammitha/nixos-configuration/tree/30968fba0297888043c6730424f6c816f75ddb9e) (which does not have `xdg.configFile."git/test".text = "test config file";` in `home.nix`, so I added that line in `home.nix`) the trace of the two imports look like:

1. `flake.nix`, line 27 -> `configuration.nix`, line 127 `home.nix`
2. `flake.nix`, line 32 -> `home.nix`

`home.nix` is imported twice, thus  `xdg.configFile."git/test".text = "test config file";` is seen twice, and the text is duplicated.

To solve this issue right now, eliminate one of the imports of `home.nix`. In your specific case, the configuration defines the same Home Manager settings in two place; I think you should delete [these definitions](https://github.com/adammitha/nixos-configuration/blob/30968fba0297888043c6730424f6c816f75ddb9e/flake.nix#L28-L32) because they are exactly the same as [these lines](https://github.com/adammitha/nixos-configuration/blob/30968fba0297888043c6730424f6c816f75ddb9e/configuration.nix#L124-L127), and it makes sense (to me) to put the home manager high-level settings along with the rest of the NixOS settings in `configuration.nix`.

**Comment by adammitha** [comment]
Oh brilliant, that solved it! I probably left the extra home.nix import in when I converted my config to a flake. Thanks for the quick response 😄
