### ISSUE TITLE
bug: broot configuration files are generated when not asked to

### ISSUE THREAD

**Issue by tomasol** [nix-community/home-manager#4524]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I prefer managing the dotfiles outside of my Home Manager configuration. However, even though I do not configure `broot.settings`, the module still attempts to overwrite my files:
```
Existing file '/home/tomas/.config/broot/verbs.hjson' is in the way ...
```

My Home Manager section only contains:
```
      programs.broot = {
        enable = true;
      };
```

### Maintainer CC

@dermetfan

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.3759.261abe8a44a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dermetfan** [comment]
Most modules do this as it requires additional code to handle the special case of empty settings. I think it's reasonable to write the default settings so that you can predict the effective end result from just reading the declarative configuration. The default is checked purely declarative configuration, and if you want to configure some programs out of band, you have to opt in by disabling specific config files:

```nix
xdg.configFile.broot.enable = false;
```

I'm closing this issue as changing this should probably be a general decision to be implemented in all modules, which would warrant a new issue for discussion.
