### ISSUE TITLE
bug: The cfg.enableTridactylNative argument for `firefox.override` is deprecated

### ISSUE THREAD

**Issue by jvanbruegge** [nix-community/home-manager#4630]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Specifying tridactyl-native using `pks.firefox.override` like in the docs is deprecated in nixpkgs unstable now and the warning says:
```
The cfg.enableTridactylNative argument for `firefox.override` is deprecated, please add `pkgs.tridactyl-native` to `nativeMessagingHosts` instead
```
However, this does not work with home-manager, because it is part of the nixpkgs firefox module

### Maintainer CC

@rycee 
@kira-bruneau 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/store/qh8csq0r8jg5mcsl2ajm1r428j5finja-4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source`
```
```

**Comment by montchr** [comment]
This issue is a lot more widespread than Tridactyl. It also applies to any other native messaging connectors with attributes in the `firefox` package declaration:

https://github.com/NixOS/nixpkgs/blob/cf28ee258fd5f9a52de6b9865cdb93a1f96d09b7/pkgs/applications/networking/browsers/firefox/wrapper.nix#L73-L86

Affects integrations with the following:

- browserpass
- bukubrow
- tridactyl native
- gnome desktop environment
- uget
- plasma desktop environment
- fxcast
- keepassxc

Each usage generates a new warning, so this can get quite noisy.
