### ISSUE TITLE
Hyprpaper support

### ISSUE THREAD

**Issue by kacperwyczawski** [nix-community/home-manager#4632]
It would be nice to have hyprpaper support.

Links:
- [GitHub](https://github.com/hyprwm/hyprpaper)
- [Nixpkgs](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hyprpaper)

**Comment by rdvdev2** [comment]
I will make an attempt at this.

**Comment by silmarp** [comment]
> I will make an attempt at this.

Hey, did you made any progress ?

I'm thinking of making an attempt too

**Comment by LennyLizowzskiy** [comment]
@silmarp

Hey. I wrote a module for Hyprpaper and I've been using it since then.
You can freely copy it to your own config if you want to: https://github.com/LennyLizowzskiy/nix-repo/blob/main/modules/home-manager/hyprpaper/default.nix

Also if some home-manager contributor want to take this code to this repo then it's good too. No need to credit me. 

Example of usage: https://github.com/LennyLizowzskiy/nixfiles/blob/main/home-manager/presets/per-user/lennylizowzskiy/configs/gui/de/hypr/hyprpaper.nix


_(quite randomly sending you this message because I got a notification because I was subscribed to this issue)_

**Comment by silmarp** [comment]
@LennyLizowzskiy 

Thanks a lot, I will use your module.

I started writing one myself yesterday, made the configuration work, however yours is much better, so I will be using it for now on. 

> 
> Also if some home-manager contributor or you want to take this code to this repo then it's good too. No need to credit me.

And if you really don't mind I will try to make a PR to add this module to home-manager

**Comment by LennyLizowzskiy** [comment]
@silmarp no problem

**Comment by rdvdev2** [comment]
> > I will make an attempt at this.
> 
> Hey, did you made any progress ?
> 
> I'm thinking of making an attempt too

I'm sorry, life got in the way and I totally forgot about this. I don't think right now I can take on this, and I invite anyone with more time in their hands to do this. I apologize for anyone that was waiting for my contribution.

**Comment by silmarp** [comment]
>
> I'm sorry, life got in the way and I totally forgot about this. I don't think right now I can take on this, and I invite anyone with more time in their hands to do this. I apologize for anyone that was waiting for my contribution.

No wories, LennyLizowzskiy already shared  a module, if you're still interested you can use it too.

When I get some free time I will try to write a PR to add the module to HM.
