### ISSUE TITLE
KeePassX is no longer actively maintained

### ISSUE THREAD

**Issue by hervyqa** [nix-community/home-manager#4949]
### Description

`services.keepassx.enable`

[Development stopped](https://www.keepassx.org/index.html%3Fp=636.html)

KeePassX is no longer actively maintained.
You might want to switch to [KeePassXC](https://keepassxc.org/) which is based on KeePassX.

**Comment by sumnerevans** [comment]
Looks like it probably doesn't even work anyway since the package was removed: https://github.com/NixOS/nixpkgs/pull/216748

The option doesn't look very interesting (it just starts a systemd service), so I wonder if it's worth it to even migrate to KeePassXC. I have a feeling nobody is actually using this option (since it probably doesn't work), so it might just be better to just delete it.

**Comment by rycee** [comment]
Agreed, at some point (years ago) I tried switching the module to KeePassXC but couldn't get it to work well enough so I gave up. Eventually I switched to [pass](https://www.passwordstore.org/) and don't really use KeePass any more. So, like @sumnerevans suggests, I'm up for simply removing the module and if somebody would like to contribute a KeePassXC one, they are free to do so.
