### ISSUE TITLE
bug: Firefox native-messaging-host

### ISSUE THREAD

**Issue by xenoxanite** [nix-community/home-manager#4959]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I cant install pywalfox-native by home-manager. 

home-manager added a new in firefox to install native messaging hosts, but its not working with pywalfox-native. and even without installing any native messaging host using it, it creates a file called native-messaging-host in ~/.mozilla, which prevents me from manually installing pywalfox-native.

so make it optional, if the nativeMessagingHosts list is empty, then don't create the file, or make it compatible with pywalfox-native package.

### Maintainer CC

@rycee @Lillecarl 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.10-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240121.612f972`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Lillecarl** [comment]
Sorry for the caused inconvenience, as a "first" time contributor I had no thought whatsoever that people are using non packaged native messenger hosts. We've got a fix incoming that'll be the best of both worlds, we'll only link individual hosts rather than the entire directory, so you can use home-manager to install hosts, or install them manually.
