### ISSUE TITLE
Add module for hyprlock

### ISSUE THREAD

**Issue by cloudlena** [nix-community/home-manager#5127]
https://github.com/hyprwm/hyprlock

It would be awesome to have this available as `programs.hyprlock` and be able to configure it via home manager.

**Comment by charludo** [comment]
In the mean time, I think you can [already do this](https://github.com/fufexan/dotfiles/blob/main/home/programs/wayland/hyprlock.nix), at least in a flake setup, since `hyprlock` [provides a flake](https://github.com/hyprwm/hyprlock/blob/main/flake.nix) (just add `hyprlock.url = "github:hyprwm/hyprlock";` to your inputs)

**Comment by cloudlena** [comment]
Fixed by https://github.com/nix-community/home-manager/commit/c6ddd80fb1e5a286b3a5cb32ef94a2e4e346a9d3
