### ISSUE TITLE
bug: Warning about version mismatch between HM 24.05 and Nixpkgs 24.11 on HM master/NixOS unstable

### ISSUE THREAD

**Issue by hgouni** [nix-community/home-manager#5453]
### Are you following the right branch?

- [ ] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've started getting a warning from home manager about a version mismatch between HM and Nixpkgs. I'm on HM master and NixOS unstable, so it seems like this shouldn't be the case. Error below:

![image](https://github.com/nix-community/home-manager/assets/68922389/1fb8193d-e40e-412b-87e4-eccf6e42af4e)

NixOS flake inputs:

```
nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
home-manager.url = "github:nix-community/home-manager";
```

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.6.31, NixOS, 24.11 (Vicuña), 24.11.20240524.bfb7a88`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- channels(root): `"nixos-23.05"`
- nixpkgs: `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source`
```

**Comment by dmizelle** [comment]
The current version of `home-manager` is set in [`release.json`](https://github.com/nix-community/home-manager/blob/master/release.json) at the root of this repo.

You'll usually see this when https://github.com/NixOS/nixpkgs cuts a new release branch and moves unstable/master to the next release version. This was [just done a couple of days ago](https://github.com/NixOS/nixpkgs/commit/4a817d2083d6cd7068dc55511fbf90f84653b301) so now any recent commit of `nixpkgs` that is either `unstable` or `master` is now `24.11` instead of `24.05`. 

To resolve the warning here, `home-manager` maintainers need to cut a branch for 24.05 and then bump the version in `master`. Takes a bit of time, they're only human. :) See #4013 as an example.

You should be able to run as-is until then and probably bump the flake on your side in the next couple of days. You shouldn't run into problems (probably) for now as this has happened a few times over the past year as the release cycle goes. I wouldn't set `home.enableNixpkgsReleaseCheck = false` though, as you probably want to catch this in between releases just in case.

**Comment by hgouni** [comment]
Ah, okay-- makes sense. Thanks!

**Comment by jackwilsdon** [comment]
#5450 looks like the release PR to keep an eye on.

**Comment by rycee** [comment]
Yeah, apologies for the confusion caused. It's a bit tricky to keep everything nice and clean around release time but hopefully things should be better now.

**Comment by Noisy-K** [comment]
I have the exact same warning even though the problem seems to have been solved. It appeared when I decided to switch from stable to unstable.

My inputs in _flake.nix_ looks like that:
`    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/release-24.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    plasma-manager = {
      url = "github:nix-community/plasma-manager";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
` 

Do you know what could be the problem in my case ?

**Comment by pkoch** [comment]
This is happening again:
```
trace: warning: You are using

  Home Manager version 24.11 and
  Nixpkgs version 25.05.

Using mismatched versions is likely to cause errors and unexpected
behavior. It is therefore highly recommended to use a release of Home
Manager that corresponds with your chosen release of Nixpkgs.

If you insist then you can disable this warning by adding

  home.enableNixpkgsReleaseCheck = false;

to your configuration.
```

Nixpkgs was indeed bumped 3 days ago: https://github.com/NixOS/nixpkgs/commit/90fcf3aa7eba70f18dad15b634e9336b997d25ac

> Takes a bit of time, they're only human. :)

Can we perhaps automate this? I'd love to make @rycee's life easier! :)

**Comment by kastl-ars** [comment]
Sorry to piggyback, but I encounter the error message from @pkoch 's last comment on one of my machines now.

- Nix and home-manager on a Fedora 41 system.
- Channels for the non-privileged user are set to 24.11 for both home-manager and nixpkgs
- (nixgl is added as it is needed for some apps on this machine)

The setup is (AFAICS) the same as on another Fedora box, but there everything works. While on this one home-manager spits out the warning. Not sure why it thinks I am using the 25.05 nixpkgs channel...
