### ISSUE TITLE
bug: Firefox no longer launches with custom profiles

### ISSUE THREAD

**Issue by dairyisscary** [nix-community/home-manager#5717]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have a home module that looks something like this:

```nix
  programs.firefox = {
    enable = true;
    package = lib.mkIf isDarwin (pkgs.firefox-bin.overrideAttrs (prevAttrs: {
      postInstall = ''
        folder="$out/Applications/Firefox.app/Contents/Resources/distribution"
        mkdir -p "$folder"
        echo '{
          "policies": {
            "AppAutoUpdate": false,
            "DisableAppUpdate": true
          }
        }' > "$folder/policies.json"
      '';
    }));
    profiles.${config.home.username} = {
      settings = {
        "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
      };
      userChrome = builtins.readFile ./firefox-userchrome.css;
      search = {
        force = true;
        default = "Kagi";
        engines = {
           # elided...
        };
      };
    };
  };
```

After #5128, firefox no longer opens on aarch64-darwin (I have not tested any other platform). I have verified that the commit _before_ is not affected.

I noticed that `profiles.ini` file looks exactly the same between the two profiles, with #5128 and without, except for this notable line:
```ini
[General]
StartWithLastProfile=1
Version=2 # <- this one.

[Profile0]
Default=1
IsRelative=1
Name=eric
Path=Profiles/eric
```

And that seems to be new configuration in #5128. If i just manually link this file to the older profile without this `Version` line, but keep the newer profile, firefox does seem to open correctly. I can't find any mozilla documentation on this property.

### System information

```markdown
nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`
```

**Comment by khaneliman** [comment]
Same behavior here.. I saw it immediately after that got merged too. My workaround for the time being has been to create a rw profiles.ini with the same contents after a flake switch...

**Comment by brckd** [comment]
My bad. I added that property since I observed that it fixed profiles on most other derivarives such as LibreWolf. I couldn't find any docs on it either, so I just hoped it wouldn't affect browsers that use version 1. Am I correct to assume this only breaks stock FF on Darwin?

**Comment by dairyisscary** [comment]
> My bad. I added that property since I observed that it fixed profiles on most other derivarives such as LibreWolf. I couldn't find any docs on it either, so I just hoped it wouldn't affect browsers that use version 1. Am I correct to assume this only breaks stock FF on Darwin?

I think its only stock Firefox on Darwin, yes. I tried a x86 linux nixos box today, and it worked just fine with the v2 property. For reference, I'm using the overlays provided here for Darwin since nixpkgs doesn't have good Darwin support for Firefox: https://github.com/bandithedoge/nixpkgs-firefox-darwin

**Comment by booxter** [comment]
@dairyisscary I suspect `firefox-bin` is also affected, even for Linux, see: https://github.com/nix-community/home-manager/pull/5724#issuecomment-2323655812 I don't have access to a Linux box with nixos to try it out. Can you by chance check it?

**Comment by brckd** [comment]
Why would `firefox-bin` be affected if it was never used in the module? Is there any reason to use `firefox-bin` over `firefox` or `firefox-unwrapped`?

**Comment by booxter** [comment]
It *can* be used. I don't know why one would use it though, but that's an official binary from Mozilla. The reason I think it may be affected is that it probably doesn't use `MOZ_LEGACY_PROFILES=1`, and as per my [theory](https://github.com/nix-community/home-manager/pull/5724#issuecomment-2323655812), it means it won't be comatible with `profiles.ini` of `Version=2` that implies `[Install]` sections are part of the `profiles.ini` file and no `installs.ini` "backup" is created.

**Comment by booxter** [comment]
> I added that property since I observed that it fixed profiles on most other derivarives such as LibreWolf

@brckd do you have any details as to how LibreWolf failed without `Version=2`? I'd think since it uses the same code base as Firefox (with minor adjustments that probably don't affect profile loading), it would handle `profiles.ini` the same way.

**Comment by brckd** [comment]
I only saw that it was failing and that LibreWolf's own config includes `Version = 2`. I never dived into the question as to why this happens, but will try to check the logs today.

**Comment by dairyisscary** [comment]
> @dairyisscary I suspect `firefox-bin` is also affected, even for Linux, see: [#5724 (comment)](https://github.com/nix-community/home-manager/pull/5724#issuecomment-2323655812) I don't have access to a Linux box with nixos to try it out. Can you by chance check it?

I did try the `pkgs.firefox-bin` (both wrapped and unwrapped) from `nixpkgs` for x86 nixos and they seemed to work for me, even with the version=2 thing.

**Comment by booxter** [comment]
I did some more reading of Firefox code yesterday. This is my current thinking. I [copied](https://github.com/nix-community/home-manager/pull/5790#issuecomment-2326436862) it from a Thunderbird PR. It is referring to Thunderbird, but the same applies to Firefox.

---

There are two scenarios that seem to work correctly with a read-only `profiles.ini` (regardless of the platform):

1. Set `MOZ_LEGACY_PROFILES=1` *and* set `Version=2`.
2. Use default (dedicated profiles per installation) *and* leave the `profiles.ini` file without `Version` set. (Which implies v1.)

When (1) is used, no `installs.ini` is created in `Flush` (this is a function in the Mozilla engine). Nor the file is loaded when parsing `profiles.ini`. This is fine because in this mode Thunderbird does not work with per-install configs.

When (2) is used, `installs.ini` *is* loaded as a "backup"; *and* it's dumped to on `Flush`. So while `profiles.ini` still cannot be overridden (because it's read-only), Thunderbird can effectively update its per-install profile config.

The package from `nixpkgs`, thanks to the `wrapThunderbird`, sets `MOZ_LEGACY_PROFILES=1` for the app. This is why (1) works for Linux but not for Darwin.

[This PR](https://github.com/nix-community/home-manager/pull/5790) proposed to switch to (2). But I think this may break `nixpkgs` Thunderbird. For this to work, `nixpkgs` would have to switch to "dedicated profiles" (remove `MOZ_LEGACY_PROFILES=1` from the wrapper.) I don't think this is going to happen any time soon (probably never unless Mozilla ever rips of "legacy" profile support from its code base.) So I have to rethink the approach here.

---

I think in the end, we may have to stick to `Version=2` here. As to Darwin users, we can help them by setting `MOZ_LEGACY_PROFILES=1` in their session variables. (Right now we only instruct them to do so with a warning.)

This can probably be safely done for all platforms, not just Darwin. The `nixpkgs` packages already pass this variable to the wrapped apps. And it may be helpful in an (unusual) scenario where a Linux, non-NixOS user may use home-manager without `nixpkgs` package.

**Comment by booxter** [comment]
There seems to be a similar, related bug reported earlier here: https://github.com/nix-community/home-manager/issues/3323

**Comment by booxter** [comment]
I think I have a solution for the problem that doesn't require a removal of the `Version=2` line in the `profiles.ini` file for Darwin. The solution is two-fold:

1. [Set](https://github.com/nix-community/home-manager/pull/5801) MOZ_* variables for Firefox and Thunderbird modules to mimic `nixpkgs` ("legacy") behavior.
2. [Expose](https://github.com/nix-community/home-manager/pull/5808) `sessionVariables` to `launchd` environment (used to start apps from UI).

With these two pieces in place, I was able to enable `firefox` and `thunderbird` modules with the unchanged `profiles.ini` and then run the apps (installed from `homebrew`) with Mac UI.

Let me know what you think.

**Comment by booxter** [comment]
One more comment on the above solution. `nix-darwin` has a [bug](https://github.com/LnL7/nix-darwin/issues/420) where `activate-user` is not initialized on reboot. So the solution currently requires a manual activation, or an [addition](https://github.com/LnL7/nix-darwin/issues/420#issuecomment-2336325441) of a user launchd service to run the `activate-user` script, or [this patch](https://github.com/LnL7/nix-darwin/pull/1061) for `nix-darwin`.
