### ISSUE TITLE
bug: eza completions not working

### ISSUE THREAD

**Issue by cgahr** [nix-community/home-manager#5800]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The shell completions for `eza` in zsh are not working correctly. 

with `enableZshIntegration = true`, this only happens for `ls`, not for i.e. `ll` or others.

If I run `ls`, I get the follwing output
```
ls <TAB>
always auto automatic never
``` 
This options match the `--classify` options, what ever that means.

With `enableZshIntegration = false`, I have the alias `eza --icons` in my config. Running `eza <TAB>` show the same, wrong completions while `eza --icons <TAB>` shows correct completions (using the same alias of course).

### Maintainer CC

@stasjok 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-40-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by cgahr** [comment]
I cannot reproduce this issue anymore... Closing it for now

**Comment by kuznetsss** [comment]
I got the same issue. There is a problem with `icons` option. When there is `icons = true` home manager creates an alias `alias -- eza='eza --icons'` but `--icons` flag requires a value, one of `always`, `auto`, `automatic`, `never`.

I'm not sure which solution would be better, use `--icons=always` or change nix option `icons` from bool to string.

**Comment by stasjok** [comment]
> `--icons` flag requires a value, one of `always`, `auto`, `automatic`, `never`.

That's not true, value is not required, it defaults to auto if there is no value. Probably it's for backward compatibility (in the past it was `--icons` / `--no-icons`). But I found one caveat: if one have directory named 'auto', then `eza --icons auto` won't work, so it's better to specify value explicitly.

> I'm not sure which solution would be better, use --icons=always or change nix option icons from bool to string.

I think it can be safely changed to `--icons=auto`. It would be backward compatible. Most of the time you want it to be auto, so that when you pipe it to other commands icons won't interfere. Another solution can be to change its type to `enum ["auto" "always" "never"]` or to `either bool (enum ["auto" "always" "never"])` (true means `--icons=auto`).

**Comment by kuznetsss** [comment]
> That's not true, value is not required

I just checked `eza --icons` works fine, but at the same time `eza --help` contains a line:
```
--icons=WHEN               when to display icons (always, auto, never)
```
Eza's completion file follows help:
https://github.com/eza-community/eza/blob/main/completions/zsh/_eza#L26

I will create a PR with fix as you suggested, thanks!
