### ISSUE TITLE
XDG_RUNTIME_DIR isn't set for `root` user, logged in via `sudo` inside SSH session

### ISSUE THREAD

**Issue by danbst** [nix-community/home-manager#601]
My setup (pretty scary):
- Ubuntu 18.04
- connect to remote host as `ubuntu` user
- `sudo su -` to obtain root
- home-manager with some 18.09 checkout installed into `root`-s home
- custom user service defined
- linger enabled:
```
    home.activation.linger = dag.entryBefore ["reloadSystemD"] ''
        loginctl enable-linger $USER
    '';
```
I get a problem that `systemctl --user` can't reach DBus:
```
root@nomad-02:~# systemctl --user -a
Failed to connect to bus: No such file or directory
```
I fix it with
```
    home.sessionVariables.XDG_RUNTIME_DIR = "/run/user/$UID";
```
but I wonder why this isn't default.

**Comment by wedens** [comment]
You don't even need to do that remotely. 

Doing something like `sudo -u other_user zsh -c 'systemctl --user show-environment'` will result in the same problem. Providing `XDG_RUNTIME_DIR` makes it work.

**Comment by rycee** [comment]
Seems this is (mostly) by design. See, e.g., https://github.com/systemd/systemd/issues/7451#issuecomment-346787237

Specifically, the su and sudo PAM configurations intentionally don't include `pam_systemd.so` (at least on NixOS) so `XDG_RUNTIME_DIR` will not be set for those commands. You can bypass this by setting `XDG_RUNTIME_DIR` as you've found out but reading Poettering's response it seems to me that this comes with implications that makes it a bad idea to include it by default in HM.

Using `machinectl` does indeed seem to work to give you a proper login shell with a functional systemd. E.g.
```console
$ machinectl shell test@
```
to make a login shell for the user "test" on the local system. So I would suggest using `machinectl` instead of `sudo` when you want a full login shell with a user systemd session. This seems like an extra good idea for root logins since the `machinectl` way appears to isolate the root login more from your user login.

**Comment by danbst** [comment]
interesting. So `sudo su -` considered wrong, use `sudo machinectl shell root@`...

**Comment by wedens** [comment]
One of the problems with `machinectl shell` is that it doesn't propagate exit code. man says that systemd-run should be used in this case, but I can't figure out the correct way to use it.
