### ISSUE TITLE
Add ZSH plugin from Nixpkgs

### ISSUE THREAD

**Issue by axelkar** [nix-community/home-manager#6183]
### Description

Add a feature to add ZSH plugins from Nixpkgs (e.g. [zsh-you-should-use](https://search.nixos.org/packages?query=zsh-you-should-use).

Currently it's impossible via `programs.zsh.plugins` and `home.packages`

**Comment by NovaViper** [comment]
I'm pretty sure you write this to install it
```
    programs.zsh.plugins = [{
      name = "zsh-you-should-use";
      src = pkgs.zsh-you-should-use;
      file = "share/zsh/plugins/zsh-you-should-use/you-should-use.plugin.zsh";
    }];
```

**Comment by axelkar** [comment]
> I'm pretty sure you write this to install it

Could a cleaner solution for that be added?

**Comment by NovaViper** [comment]
> Could a cleaner solution for that be added?

Afaik, no. Partly because there isn't a way to predict where the contents of the plugin gets placed on the system; which depends on where the nix package decided to put the contents. Most seem to go under `$out/share/zsh` but some go under `$out/share/zsh/plugins` and some don't (i.e. the zsh-vi-mode package puts its contents under `$out/share/` but the zsh-clipboard package puts its contents `$out/share/zsh/plugins`.)

And then the `name` variable is also unpredictable for the same reason as mentioned before: depends on how it's named in the nix package.
