### ISSUE TITLE
Why is there both services.mbsync and programs.mbsync?

### ISSUE THREAD

**Issue by loewenheim** [nix-community/home-manager#642]
`mbsync` can be configured both under `services` and under `programs`, and they don’t have the same options. For instance, there is `services.mbsync.configFile` that allows one to specify an alternative config file path, but everything that refers to `programs.mbsync` ignores this and writes its options to `.mbsyncrc`. On the other hand, `programs.mbsync` has an `extraConfig` option and `services.mbsync` doesn’t. I assume this is not intentional?

**Comment by teto** [comment]
the program one adds it to PATH while the service one makes it run in background (as a service/systemd/cron stuff) so the difference is legitimate.

**Comment by rycee** [comment]
Yeah, they serve different purposes. Also, the service module was contributed before the email infrastructure was in place so the two modules may not be perfectly matched. I think it might be worth looking the service module over in the future to see if it can harmonize better with the program module.

**Comment by ejpcmac** [comment]
It seems that currently:

* the `accounts.emails.accounts.*.mbsync` can be used for the configuration, but no configuration file is written *per se*;
* `programs.mbsync.enable = true;` generates the config file from the account configuration;
* `services.mbsync.enable = true;` enables the service, but does not use the configuration from the accounts infrastructure.

To get it to work, I thus need to configure the three.

Also, I noted that the example for `services.mbsync.postExec` (`"mu index"`) cannot work, because the service uses a dummy `PATH` variable. `"${mu}/bin/mu index"` works better.

**Comment by rycee** [comment]
@ejpcmac Yeah, the mbsync service came before the mail infrastructure so I doesn't use it. I guess enabling the service implicitly should enable the program configuration, for state version 19.09 onwards.
